### ISSUE TITLE
[Docs]: In fresh generated app url points to legacy react doc

### ISSUE THREAD

**Issue by rxx** [redwoodjs/redwood#10273]
### Summary and description

There is a comment in "entry.client.tsx":

## Wrong comment with a legacy link

```
/**
 * When `#redwood-app` isn't empty then it's very likely that you're using
 * prerendering. So React attaches event listeners to the existing markup
 * rather than replacing it.
 * https://reactjs.org/docs/react-dom-client.html#hydrateroot
 */
```

## Expected comment:

```
/**
 * When `#redwood-app` isn't empty then it's very likely that you're using
 * prerendering. So React attaches event listeners to the existing markup
 * rather than replacing it.
 * https://react.dev/reference/react-dom/client/hydrateRoot
 */
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @rxx :wave

Thanks for opening this and marking that you'd like to work on it. I agree that the doc link is outdated and the one you suggest is a good replacement.

When it comes to implementing this change I can try and give a bit of context/understanding of the repository in case anything isn't immediately clear.

We have a `create-redwood-app` directory in our `packages` directory where the code for this lives. Specifically, you'll find the entry client files at:
TS - https://github.com/redwoodjs/redwood/blob/f8c47957f256cf8f573f00d264ee35a932dcbccf/packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
JS - https://github.com/redwoodjs/redwood/blob/f8c47957f256cf8f573f00d264ee35a932dcbccf/packages/create-redwood-app/templates/js/web/src/entry.client.jsx

Since it's just a comment you could simply update both those files directly. If this was a larger code change we would typically update the TS version and then run the `ts-to-js` script within that `create-redwood-app` package to regenerate the JS version from the TS version. 

Another thing is that because this changes the template you will likely also have to run the `yarn rebuild-test-project-fixture` command from the root of the repository. We use this command to keep our test project fixture up to date. Changes to the project template will mean we'd need to update the fixture. Running that command should run through a bunch of steps automatically (it might take a bit of time 😬) and then you should hopefully see a small git diff that looks like your docs changes - simply add a commit with those changes too. 

Hopefully, that wasn't too much upfront haha! I just wanted to lay everything out a little. Happy to help out if you want to open a PR for this but there's also no rush at all.

**Comment by rxx** [comment]
@Josh-Walker-GM I've created a pull request
