### ISSUE TITLE
[Bug]: Seeing Unknown Fragment after migration to use `registerFragment`

### ISSUE THREAD

**Issue by shivghai** [redwoodjs/redwood#10322]
### What's not working?

I was previously, pre rw 7, using fragments (successfully) using string interpolation. Post upgrade, there are no changes to the actual query itself, except that the fragment is no longer interpolated, and is being registered instead.

I have a GQL Fragment, F_Fragment, which is being used in a query, Q_QUERY.

*UPDATE - file info* Here's the code for the fragment, in `fragment.ts`:
```
import { registerFragment } from '@redwoodjs/web/apollo'

const F_Fragment = gql`
  fragment F_Fragment on F {
  field1
  field2
}`

registerFragment(F_Fragment)
```

*UPDATE - file info* The code for the query, in `query.ts`:
```
const Q_QUERY = gql`
  query QQuery {
     f {
        ...F_Fragment
     }
 }
```

We can no longer fetch the required data using the query, and get the `Unknown fragment A_Fragment` error. 

The query is called in this way:

```
import { useQuery } from '@redwoodjs/web'

export default () => {
  return useQuery(Q_QUERY)
}
```

Interestingly, the graphql types are generated correctly. The query also still works with string interpolation (minus types). Any ideas here?

### How do we reproduce the bug?

**UPDATED**
Declare and register fragment in a different file than the query

### What's your environment? (If it applies)

  System:
    OS: macOS 13.6
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /private/var/folders/8y/99byt5ms31d1z8jgjfmyvcg80000gn/T/xfs-d437a37e/node
    Yarn: 3.2.1 - /private/var/folders/8y/99byt5ms31d1z8jgjfmyvcg80000gn/T/xfs-d437a37e/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 16.6
  npmPackages:
    @redwoodjs/auth-auth0-setup: 7.1.3 => 7.1.3 
    @redwoodjs/cli-data-migrate: 7.1.3 => 7.1.3 
    @redwoodjs/core: 7.1.3 => 7.1.3 

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by shivghai** [comment]
I think I see the issue.

We stored all our fragments in a `src/graphql/fragments` directory. By the time the *query* itself is initialized, the fragment is unavailable/hasn't been registered yet.

Going to have to rework this whole bit. Unsure how to make fragments *actually* shareable across our different queries if this is the issue, will give it some more thought later.

Any ideas?

**Comment by shivghai** [comment]
Not that anyone would ever do this in production code, but here's something I tried out with initialization in the same files.

## Case 1: 1 ms delay before registering

This does not work (throws "Unknown Fragment"):
```
import { registerFragment } from '@redwoodjs/web/apollo'
const USERS_FRAGMENT = gql`
  fragment UsersFragmentTest on User {
    id
    fullName
  }
`

export const USERS_QUERY = () => {
  setTimeout(
    () => registerFragment(USERS_FRAGMENT),
    1)
  return gql`
  query UsersQuery {
    users {
      ...UsersFragmentTest
    }
  }
`}
```


## Case 2: No delay before registering
This works:
```
import { registerFragment } from '@redwoodjs/web/apollo'
const USERS_FRAGMENT = gql`
  fragment UsersFragmentTest on User {
    id
    fullName
  }
`

export const USERS_QUERY = () => {
  registerFragment(USERS_FRAGMENT)
  return gql`
  query UsersQuery {
    users {
      ...UsersFragmentTest
    }
  }
`}
```

## Case 3: 0ms delay before registering
This makes it flakey (*sometimes* throws "Unknown Fragment"):
```
import { registerFragment } from '@redwoodjs/web/apollo'
const USERS_FRAGMENT = gql`
  fragment UsersFragmentTest on User {
    id
    fullName
  }
`

export const USERS_QUERY = () => {
  setTimeout(() => registerFragment(USERS_FRAGMENT), 0)
  return gql`
  query UsersQuery {
    users {
      ...UsersFragmentTest
    }
  }
`}

```

**Comment by shivghai** [comment]
I'm a React noob, but does this need to re-run any time the fragments are changed? https://github.com/redwoodjs/redwood/pull/9140/files#diff-f19decdeb6ec45e8c3e8a7a9bed807dc693a46d9fb5254bf579291c7e17fa524R322-R325

**Comment by thedavidprice** [comment]
@dthyresson has been working on this — looping him in here.

**Comment by dthyresson** [comment]
Hi @shivghai thanks for the detailed info and apologies for the bumps in using fragments -- my intention was to 1)  make things easier 2) I did review the approach with folks at Apollo 3) do the heavy lifting of being able to support unions and such.  

Some background:

First, I've been surprised to see that people had fragments with string interpolation working as when we saw that, the specific graphql codegen loader we used could not do interpolation, so generating types failed. This was one of the factors in moving to the client preset codegen and fragment registration. So, I didn't expect much of a breaking change than it turned out to be honestly. So apologies for that.

Second, I based the fragment design and pattern off of the approach the Guild takes here: https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen . Specifically, "Colocate GraphQL documents with the component code. Instead of writing GraphQL operations in a dedicated file, the operations are written within the component code."

In talking to the Guild and others, it was the desire to build a "component tree" that drove the graphQL developers to come up with the concept of fragments. In fact I went back to my notes:

- fragments are one the few graphql primitives
- graphql people said fragments are why build graphql
- goal of gql is to replicate view hierarchies
- a reusable view needs reusable data for the view
- light on query high on fragment

The key here is the "view hierarchy" or as the Guild puts it:

> A fragmentized component tree. Instead of writing a single GraphQL operation document per visible component or extracting the component properties from a single query operation document type, which is often cumbersome), multiple fragment definitions can be composed up to a single query operation that is sent to the server. This reduces the amount of concurrent requests 

So, fragments are most often not just a way to move out parts of a query to be reusing in queries, but the goal is to collocate the data needed to render a comment with the presentation of that data.

Thus:

> I stored and registered the fragment separately from the query, in a different file.

I guess was not the use case I was designing for. And I confess I didn't consider it as the pattern I was aiming for was that view hierarchy and colocation of component data.

Third, may I ask why in your examples you'd want to delay registration of the fragment? Or was that just a way to reproduce when the fragment was in a separate file?


Last: the line you point to:

```ts
  // Auto register fragments
  if (fragments) {
    fragmentRegistry.register(...fragments)
  }
```

That's another way fragments can be registered: You can pass them into the Apollo provider which is kinda tricky -- or use the `registerFragment` which adds them individually. 

So -- to answer the question: "Is there a recommended directory structure? What is the goal for registerFragment if it doesn't help with code reuse outside of the same file? Am I missing something?"

The goal was to let developers create the view hierarchies and collocate the data with the component. This lets Apollo manage the cache for each fragment really nicely. In addition, it will let us implement upcoming features such as fragment masking which is in RFC here: https://github.com/apollographql/apollo-client/issues/11666

Hope this extra background helps. If there's something I can do to make the experience better, let me know. In the mean time, I'll ask the Guild and others about the "keeping queries all in one file using fragments" pattern and get their thought on how and when to use that.

**Comment by shivghai** [comment]
Hi @dthyresson - appreciate the thoughtful response. I have a couple of clarifications, and some explanation of how we've set up our fragments.

> Third, may I ask why in your examples you'd want to delay registration of the fragment? Or was that just a way to reproduce when the fragment was in a separate file?

Yep just to reproduce different files. Ignore that.

> So, fragments are most often not just a way to move out parts of a query to be reusing in queries, but the goal is to collocate the data needed to render a comment with the presentation of that data.

I see the benefit here for heavily performance-dependent teams, but I also see an increase in verbosity (for eg, having to redefine fragments which differ by one field because of different of usage in data. for example, if Component1 needs `fullName`, `email` and Component2 needs `fullName` only, now we need to have 2 different fragments when we could have just used a single fragment which includes both `fullName`, `email`) and a significant decrease in code maintainability (e.g. if we need a new field, `initials` to be added, I now need to update 2 fragments instead of just one). We've gone for simplicity and speed over performance, and this heavily breaks our codebase.

>  In the mean time, I'll ask the Guild and others about the "keeping queries all in one file using fragments" pattern and get their thought on how and when to use that.

Just a clarification - that's not exactly how we do things. We have `web/src/fragments/user` which includes the user fragments for example, which is then used in any queries related to users by importing the fragment and using it in the required query using string interpolation. Our data is heavily relational, and having to redefine fragments every time we want a new component with a different view of the data will be extremely painful.

What I meant by "keeping queries all in one file using fragments" is that would be what I'd have to resort to, given the current limitations. 


> If there's something I can do to make the experience better, let me know. 
Bringing back string interpolation would be great, since that worked well for us

Let me know if I can answer any other questions on our usage!

**Comment by shivghai** [comment]
What would work best would be to bring back string interpolation, or to somehow hoist certain files/directories in Redwood so we can guarantee fragment registration first. If there's already a way to do that, that'd be perfect

**Comment by dthyresson** [comment]
> @dthyresson What would work best would be to bring back string interpolation, or to somehow hoist certain files/directories in Redwood so we can guarantee fragment registration first. If there's already a way to do that, that'd be perfect

That’s the mystery to me — I never saw string interpolation in fragment code working. It always threw an error when doing type/code generation. 

Unless a newer version of the code file loader now supports it. I’ll look into that.

**Comment by dthyresson** [comment]
FYI this said that the loader did not permit interpolation https://stackoverflow.com/questions/62749847/graphql-codegen-dynamic-fields-with-interpolation

**Comment by pvenable** [comment]
That stack overflow question appears to be about interpolating _fields_ into fragments rather than including _fragment definitions_ into other fragments or queries, which was the way to reference other components' fragments prior to the `fragmentRegistry`.  See my first code block in https://github.com/redwoodjs/redwood/issues/10120#issue-2172782798 for an example of the latter.  As mentioned in that issue, the steps described there did work in Redwood 6.5.1, and that's how we always used fragments from Redwood 1.x until v7 (though we did start migrating _some_ of our fragments to Apollo's fragment registry before Redwood added the native integration).

Personally I think the `fragmentRegistry` is an improvement overall, but I do think there is a potential footgun in that (as far as I know) there's nothing guaranteeing at runtime that a particular fragment has indeed been registered before referencing it from elsewhere.  For example, it seems one could (accidentally) reference a fragment that has been code-split into a separate bundle or whose registration code has otherwise not been imported.  (That could be what's going on in this issue.)

This may just be the nature of the thing, and when following "normal" patterns like referencing fragments of imported child components it does seem safe to assume that registration will have occurred due to having directly imported the component file that registers that fragment.  But I could see cases -- like including a fragment into a mutation* to ensure the cache is updated appropriately -- that could fail depending on whether the bundle that registers a given fragment has been loaded. 🤔 If my theory is correct, the answer (for now?) may just be "don't do that!", but I haven't confirmed this problem.

(*: This seems like a reasonable use case to me, but I don't think I've done this much, and perhaps it's a mistake. 🤷‍♂️)

**Comment by shivghai** [comment]
@pvenable 

> But I could see cases -- like including a fragment into a mutation* to ensure the cache is updated appropriately -- that could fail depending on whether the bundle that registers a given fragment has been loaded.

We currently do this, part of the reason why we share fragments across multiple queries/mutations

**Comment by dthyresson** [comment]
I think I’ll have to create a small demo app and try to recreate the issue and then work to see if I can restore the 6.5.1 behavior. 

Can I ask if in your toml you have any of the GraphQL settings enabled like fragments https://redwoodjs.com/docs/cli-commands or trusted documents?

The fragments config will try to swap out the gql function with one that supports possible types.

For my test app, I’d turn those off.

**Comment by shivghai** [comment]
Thanks for looking into this @dthyresson !

Pre-upgrade, I didn't have any gql related settings set up
Post upgrade, I had 
```
[graphql]
  fragments = true
```
to get the fragment registry working

I'm happy to hop on a call to discuss and post findings here if that's helpful, unless if you prefer async in which case that's fine too

**Comment by shivghai** [comment]
Demo app should be easy and I imagine it's top of mind for you, but I can outline what it could look like in case that's helpful:

If you're starting with Redwood 6.x:

`web/src/fragments/users.ts` -> declare a fragment for user info here
`web/src/components/UserCard` -> use the fragment in a query here, using string interpolation. You can also add a mutation here which uses the same fragment 
`web/src/components/UserChip` -> use the same fragment here, using string interpolation

**Comment by dthyresson** [comment]
> I'm happy to hop on a call to discuss and post findings here if that's helpful, unless if you prefer async in which case that's fine too

I might take you up on that :)

To clarify, this is the behavior I was familiar with in v6 and before and what the entire register fragment DX intended to make "easier" -- or so I hoped.

* All is happy because the fragment and using the fragment are all in the same gql so it can know what BookParts is
![image](https://github.com/redwoodjs/redwood/assets/1051633/fc188feb-1d0d-4edc-9119-8d5818721f50)

* Not happy as the fragment is unknown

![image](https://github.com/redwoodjs/redwood/assets/1051633/592ff306-2e35-4b8d-88b5-a5ebc4f5378a)


* Squiggles not happy but the fragment did actually work (little surprised frankly as not what I expected)
![image](https://github.com/redwoodjs/redwood/assets/1051633/91eb2e88-59e0-445d-ae24-d4bf277d5657)

but the type check shows the error:

```bash
fragment-test main % yarn rw tc
✔ Generating the Prisma client...
✔ Generating types
src/components/BooksCell/BooksCell.tsx:26:5 - error TS2554: Expected 1 arguments, but got 2.

26   ${bookPartsFragment}
       ~~~~~~~~~~~~~~~~~


Found 1 error in src/components/BooksCell/BooksCell.tsx:26
```

Again, little surprised by this as not what expected.

**Comment by dthyresson** [comment]
Interesting ... manually importing graphql pluck seems to help:

![image](https://github.com/redwoodjs/redwood/assets/1051633/cb5c92ef-6b75-4dd1-8933-9e656c2fc431)

No squiggles and types and tc passes:

```bash
ragment-test main % yarn rw g types && yarn rw tc
Generating...

- .redwood/schema.graphql
- .redwood/types/mirror/api/src/directives/requireAuth/index.d.ts
- .redwood/types/mirror/api/src/directives/skipAuth/index.d.ts
- .redwood/types/mirror/api/src/services/books/index.d.ts
- .redwood/types/mirror/web/src/pages/BooksPage/index.d.ts
- .redwood/types/mirror/web/src/pages/FatalErrorPage/index.d.ts
- .redwood/types/mirror/web/src/pages/NotFoundPage/index.d.ts
- .redwood/types/mirror/web/src/components/BooksCell/index.d.ts
- .redwood/types/includes/web-routesPages.d.ts
- .redwood/types/includes/all-currentUser.d.ts
- .redwood/types/includes/web-routerRoutes.d.ts
- .redwood/types/includes/api-globImports.d.ts
- .redwood/types/includes/api-globalContext.d.ts
- .redwood/types/includes/api-scenarios.d.ts
- .redwood/types/includes/api-test-globals.d.ts
- .redwood/types/includes/web-test-globals.d.ts
- .redwood/types/includes/web-storybook.d.ts
- api/types/graphql.d.ts
- web/types/graphql.d.ts

... done.

✔ Generating the Prisma client...
✔ Generating types
fragment-test main % 
```

**Comment by dthyresson** [comment]
@shivghai and @pvenable I *think* I may have found the culprit and even why I may not have seen it when working on fragments as the change to help support Trusted Documents aka Persisted Operations changed the type of the global gql.

The generic type we had made for TD support seems to be incompatible with the graphql-tag:

![image](https://github.com/redwoodjs/redwood/assets/1051633/01968585-7bfc-45b3-bf06-4ca4803fc0c8)

With this change, TS and GraphQL seem to be happy:

![image](https://github.com/redwoodjs/redwood/assets/1051633/d5ea8f5d-6a33-4b98-b6f0-09ac5062301a)


I need to do some tests that TD still works, but I think you have two workarounds:

1. import graphql-tag on own
2. patch the `global.web-auto-imports.d.ts` in web node modules dist (web/node_modules/@redwoodjs/web/dist/global.web-auto-imports.d.ts) to 
```
// ...
declare global {
  const gql: (
    source: string | TemplateStringsArray | readonly string[],
    ...args: any[]
  ) => DocumentNode;
//...
```

It's that `...args` that we didn't have that seems to be the root of the expecrtect 1 but got 2 etc.

I also been to test that this is ok with the fragments setting turns on -- but I think I am on the right track.

Since TD was implemented after, and our e2e/CI/test suite used the collocated fragments pattern this got missed unfortunately.

**Comment by shivghai** [comment]
Awesome, thanks for looking into this @dthyresson . I'll wait to upgrade till we have a fix for this in RW, but this would get us all the way there!

**Comment by shivghai** [comment]
@dthyresson is this something i can help with? just want to make sure this can be resourced

**Comment by shivghai** [comment]
@dthyresson  - just following up here.
