### ISSUE TITLE
setting up CI/CD runs for redwood Repo

### ISSUE THREAD

**Issue by sw-yx** [redwoodjs/redwood#105]
i noticed that there isnt any CI running going on here - sometimes it can get in the way (so for example you may not want it to block merges until it is stable) but as the project matures you're probably going to want it? could set up a basic one with gh actions and when you feel it is ready, netlify deploy previews.

**Comment by thedavidprice** [comment]
See #110

I’ve been wanting to take a stab at GHActions having previous used CircleCI. Seems to be working ok but limited due to:
- total run time is long without caching
- can’t cache ‘cause of yarn workspaces

**Re: Netlify deploy previews** — that sounds rad to me. If you want to take an initial stab, venture over to ["create-redwood-app"](https://github.com/redwoodjs/create-redwood-app) But be warned we’re still haven’t some general issues with overall deploy process. Seems like it will be resolved by end of week. (And, lastly, there aren’t any tests for the app side of things at this time.)

**Comment by sw-yx** [comment]
yeah i would say dont bother with netlify deploy previews until your CRA is stable. if the run time is long... that might be a developer experience issue. could look into splitting up the CI based on which folders have changed.

**Comment by thedavidprice** [comment]
To research: https://github.com/prisma/prisma2-e2e-tests

**Comment by peterp** [comment]
This seems to be working!
