### ISSUE TITLE
[Bug?]: yarn scaffold script shows 404 when fetching packages

### ISSUE THREAD

**Issue by byhow** [redwoodjs/redwood#10758]
### What's not working?

Following this [quickstart](https://redwoodjs.com/docs/quick-start) on the versions and commands.

Tried running `yarn create redwood-app ./redwoodblog` shows 404 fetching a package off of `codeload`:
```
> yarn create redwood-app ./redwoodblog
yarn create v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Error: https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed "404 Not Found"
...
at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
Currently running on yarn version `1.22.x` and node `20.x`
```
> yarn -v
1.22.22
> node -v
v20.14.0
```
Yarn installs on other repo works as expected. Some pointers to troubleshoot is appreciated. Thanks!

### What's your environment? (If it applies)

```shell
System:
	OS: macOS 14.5 23F79 arm64
	Shell: zsh 5.9
Binaries:
	Node: 20.14.0
	Yarn: 1.22.22
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by byhow** [comment]
Hi @Josh-Walker-GM , thanks for the reply! 

I've tried `yarn cache clean` couple times, and the issue still persists. If I follow the link from the logs to where `concat-stream` is supposed to be, for me it shows `404` not found for that tarball.

I can opt-in for other package manager if possible to test out the `create` command. I only did it with `yarn@v1` following what the documentation suggest. I am open to test out other ways to see if I can reproduce this.

**Comment by dthyresson** [comment]
Hi @byhow am following up here to see if this is still an issue or if you got it resolved.

**Comment by byhow** [comment]
Hi @dthyresson, thanks for the reply. Yes I am still facing the same issue. Do you recommend an alternative way of scaffolding the project?

**Comment by Josh-Walker-GM** [comment]
Do you know how you have installed yarn on your system? If you are using corepack (which is built into new versions of node) you could run:
```
corepack prepare yarn@stable --activate
```
That would switch your global version of yarn to the latest stable version (v4) rather than the old v1. This might help with this issue and might be a general improvement regardless. Although if you have a need to stay on yarn v1 then we can try something else.

**Comment by byhow** [comment]
Hi @Josh-Walker-GM, appreciate the pointer. I am able to run this now with yarn `stable` (v4) ! I think it might be something related to some issues in yarn v1. I was under the assumption that the scaffold runs with yarn v1.22.x only with the [doc](https://docs.redwoodjs.com/docs/quick-start/) specs here. Thanks for walking me through this yarn issue :)

**Comment by Josh-Walker-GM** [comment]
Okay awesome so this is solved now yeah?

You said the docs made it seem like we wanted you to use v1 because of the way we listed the dependency? If so we can look at updating that to be clearer for sure!

**Comment by byhow** [comment]
@Josh-Walker-GM Yes, this is solved :) Trying out the framework rn and it looks great.

> You said the docs made it seem like we wanted you to use v1 because of the way we listed the dependency? If so we can look at updating that to be clearer for sure!

Maybe it is just me lol, since v4 is indeed > v1.22 so... I can make the update too if the docs are public. I think limiting the `yarn` version to `stable` is good for dependency maintenance, but maybe leaving the options for `v1` or `stable` is good too, up to you folks.

**Comment by Josh-Walker-GM** [comment]
Thanks! We'd always love to hear any feedback you've got while you try redwood out. The forums [here](https://community.redwoodjs.com/) are the best place for general feedback. Of course any bugs are best as GitHub issues.

Our docs are in this repo in the top level [docs](https://github.com/redwoodjs/redwood/tree/main/docs) directory. Feel free to make a PR with any suggestions and we can iterate on any changes that might be needed.

I think we probably aim to keep supporting yarn v1 since a lot of people still have that version globally. Inside of a project we do require the stable version of yarn and this is preferably handled by corepack automatically with you having to do any work at that stage.
