### ISSUE TITLE
[Bug?]: `web/src/auto-imports.d.ts` file generated after running `yarn rw storybook-vite`

### ISSUE THREAD

**Issue by oliwheeler** [redwoodjs/redwood#10848]
### What's not working?

After upgrading to Redwood 7.7.1, running `yarn rw storybook-vite` generates 3 files:
1. `web/.storybook/main.ts` *(expected)*
2. `web/.storybook/preview-body.html` *(expected)*
3. `web/src/auto-imports.d.ts` **(unexpected)**

1 and 2 are explained here: https://community.redwoodjs.com/t/storybook-in-redwood-is-moving-to-vite/7212.

File contents of `web/src/auto-imports.d.ts`:

```ts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const mockCurrentUser: typeof import('@redwoodjs/testing/web')['mockCurrentUser']
  const mockGraphQLMutation: typeof import('@redwoodjs/testing/web')['mockGraphQLMutation']
  const mockGraphQLQuery: typeof import('@redwoodjs/testing/web')['mockGraphQLQuery']
}
```

Should this file just be added to `.gitignore` or is it a bug that it is generated in the first place?

### How do we reproduce the bug?

RedwoodJS 7.7.1

Run `yarn rw storybook-vite`.

`web/src/auto-imports.d.ts` is generated.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dthyresson** [comment]
Hi @oliwheeler and thanks for reporting this issue. I'm checking with the rest of the Core Team to get some more context around storybook in this case.

**Comment by arimendelow** [comment]
Hi @oliwheeler, leaving this out of the forum post was actually an oversight on my part — because it's something that you'll never need to interact with (unlike the Storybook config files), I didn't think to include it. It's created by [this](https://github.com/unplugin/unplugin-auto-import), which is used by the Framework Package [here](https://github.com/redwoodjs/redwood/blob/main/packages/storybook/src/plugins/auto-imports.ts).

I've also updated the forum post to reflect this. Thanks for the callout!

**Comment by dthyresson** [comment]
@oliwheeler does the community post update help? If so, let me know and I'll close -- or if need more clarification do let me or @arimendelow know. Cheers!

**Comment by oliwheeler** [comment]
@dthyresson the updates community post helps! Thank you!
