### ISSUE TITLE
[Bug?]: Storybook won't work with Mantine

### ISSUE THREAD

**Issue by ladderschool** [redwoodjs/redwood#11177]
### What's not working?

When you try to view components made with Mantine in Storybook you get this error:
```
Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
```

Forum thread: [here](https://community.redwoodjs.com/t/storybook-in-redwood-is-moving-to-vite/7212/23?u=jamesj) 

Also I noticed when you run 'yarn rw setup ui mantine' the mantine.config file is created under web/config, but the import path in App.tsx is wrong. It should be:
```
import theme from 'web/config/mantine.config'
```
The repo below has this fixed as well and provides a storybook.preview.js file that wraps the mantine provider according to what Mantine suggests [here](https://mantine.dev/guides/storybook/).

### How do we reproduce the bug?

Here's a test repo you can use: [Mantine Storybook test repo](https://github.com/ladderschool/mantineRW)

Just start storybook and click on the Test component or the Home page that uses it. You'll see the error.

### What's your environment? (If it applies)

```shell
This is for the latest RedwoodJS 8.0.0-rc.1130
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by arimendelow** [comment]
Hi @ladderschool, thanks for opening this issue with a repro repo!

What's happening here is that you're putting the config in the old location — as noted in forum post, you'll need to now instead follow the [official Storybook docs](https://storybook.js.org/docs/writing-stories/decorators#global-decorators) on configuring your preview file, etc.

Instead of `web/config/storybook.preview.tsx`, you'll need to create a new file, `web/.storybook/preview.tsx`.

The contents of this file are different — as noted in the Storybook docs, your preview file should look like this (example is right out of the docs):

```tsx
import React from 'react';

import { Preview } from '@storybook/react';

const preview: Preview = {
  decorators: [
    (Story) => (
      <div style={{ margin: '3em' }}>
        {/* 👇 Decorators in Storybook also accept a function. Replace <Story/> with Story() to enable it  */}
        <Story />
      </div>
    ),
  ],
};

export default preview;
```


A start to moving over your old config looks like this:

```tsx
import * as React from 'react'

import { MantineProvider } from '@mantine/core'
// import { addons } from '@storybook/preview-api'
import type { StoryFn, StoryContext } from '@storybook/react'

// import {  useMantineColorScheme } from '@mantine/core'
// import { DARK_MODE_EVENT_NAME } from 'storybook-dark-mode'

import type { Preview } from '@storybook/react'

import theme from '../config/mantine.config'
import '@mantine/core/styles.css'

// const channel = addons.getChannel()

// function ColorSchemeWrapper({ children }: { children: React.ReactNode }) {
//   const { setColorScheme } = useMantineColorScheme()
//   const handleColorScheme = (value: boolean) =>
//     setColorScheme(value ? 'dark' : 'light')

//   React.useEffect(() => {
//     channel.on(DARK_MODE_EVENT_NAME, handleColorScheme)
//     return () => channel.off(DARK_MODE_EVENT_NAME, handleColorScheme)
//   }, [channel])

//   return children
// }

const withMantine = (StoryFn: StoryFn, context: StoryContext) => {
  return (
    <MantineProvider theme={theme}>
      {/* <ColorSchemeWrapper> */}
        <StoryFn {...context} />
      {/* </ColorSchemeWrapper> */}
    </MantineProvider>
  )
}

const preview: Preview = {
  decorators: [withMantine]
}

export default preview
```

Note that I've commented out everything related to `ColorSchemeWrapper` as that seems to have some issues, possibly with package version mismatches? I'm not sure, but at least now you know that Storybook and global decorators are working as expected :) As proof:

<img width="564" alt="Screenshot 2024-08-12 at 12 40 33" src="https://github.com/user-attachments/assets/53949306-3959-477a-a2ec-33ce07e771d6">

<img width="635" alt="Screenshot 2024-08-12 at 12 42 23" src="https://github.com/user-attachments/assets/23b64120-e3b9-4a35-ba60-c3f9507aec14">

On updating the `yarn rw setup ui mantine` command — @Josh-Walker-GM, who would be the correct person to route that to?

**Comment by ladderschool** [comment]
Perfect, thank you so much! I can't believe I didn't see the thread on the vite upgrade guide 😅 That solves it!
