### ISSUE TITLE
Adding a Test Template to Function Generator

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1147]
@peterp @cannikin @jtoar 

Currently, there is no test generated alongside a Function but, given that functions are both unique and central to RW's serverless API, it seems like there should be. What should a bare-bones test cover... how should it directionally inform a developer about what's important to test?
- check for server response
- Rob, is there anything you've learned from building Repeater.dev that might inform a basic test?
- is there a need for MSW setup/inclusion
- ?

At a minimum, we could add some copy with instructions to learn more about setting up tests in Redwood as well as suggestions about what should be tested based on how the function is being used.

> NOTE: Dom and I are prioritizing the v1 requirements for the [Testing Project](https://github.com/redwoodjs/redwood/projects/4). This is currently one of the priority tasks to address.

**Comment by cannikin** [comment]
Hmmmmm the function itself is just a plain JS function, we should be able to test it however we want. I think the base generated one just returns an object with `{ status: 200 }` and maybe an empty body? The test could just test that the return contains that 200 status and DONE.

**Comment by peterp** [comment]
If we want to provide a decent way of testing this, then we need to provide a way to emulate, or at least document,  the event and context arguments that are passed to the serverless function.

The reason for this is because if a user wants to test "input" into the function: headers, or query string parameters, then they need to pass in the correct formats.

The consideration should be made that we want to move from "aws lambda handlers" to "express handlers" in the near future, so might not want to put a lot of blood, sweat, and tears into this.

**Comment by thedavidprice** [comment]
@peterp let's attempt to loop back to this after the move to "express handlers" is complete (which will likely open us up to use more existing test tooling). 

For the near-term, here's @RobertBroersma suggestion for a simple status return test:
```js
import { handler } from './${name}'
test('${name} returns http 200', async () => {
  const result = await handler()
  expect(result).toEqual({
    statusCode: 200,
    body: JSON.stringify({
      data: '${name} function',
    }),
  })
})
```

**Comment by jtoar** [comment]
This is being discussed in #2765.

**Comment by thedavidprice** [comment]
Closing in favor of #2765
