### ISSUE TITLE
Add Redwood.js version to VSCode's status bar

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#1258]
* Currently, the status bar only says "Redwood.js" when Redwood is detected
* It would be helpful it if also stated the detected version (ex: "Redwood.js 0.19.1"). Other languages do this (including TypeScript) and, at least personally, I rely on it constantly

<img width="343" alt="Screen Shot 2020-10-02 at 9 46 22 AM" src="https://user-images.githubusercontent.com/154884/94948648-7f290e00-0494-11eb-8f61-2a0f7b3eceee.png">

**Comment by aldonline** [comment]
@thedavidprice I think this one should be tagged "vscode"  (I'm trying to put myself in the shoes of a regular redwood user)

**Comment by aldonline** [comment]
@thedavidprice  you can file an issue to transform Redwood.js to Redwood JS

**Comment by thedavidprice** [comment]
@aldonline Once upon a time we started down the route of the CLI watching for new versions and messaging the user accordingly. Turns out I didn't find a simple way to "check for more recent version" at the time. Might be a good next step after this feature is implemented.

**Note**: one important implementation detail is that there are often breaking changes or code mods required between minor versions (as you know well). So the priority UX became 1) alert user about a new version and 2) direct user to release notes URL VS. _make it super simple to upgrade_. We give upgrade instructions in Release Notes. In the future post v1, we'll want to just "make it simple to upgrade".

**Comment by aldonline** [comment]
Implemented in 0.0.12
@thedavidprice I also added an 'info' icon if there is a new version. you can click on the version to learn more
<img width="660" alt="Screen Shot 2020-10-03 at 3 12 24 PM" src="https://user-images.githubusercontent.com/154884/95002648-44ee6800-058b-11eb-85ec-96af9ec820ab.png">
