### ISSUE TITLE
getCurrentUser query is ignoring CORS configuration

### ISSUE THREAD

**Issue by jmcmullen** [redwoodjs/redwood#1303]
After setting a cors configuration inside my `graphql.js`, it seems to work for every request except the built-in `getCurrentUser` query.

```
export const handler = createGraphQLHandler({
  schema: makeMergedSchema({
    schemas,
    services: makeServices({ services }),
  }),
  cors: {
    origin: '*',
    credentials: true,
  },
  db,
  getCurrentUser,
})
```

Request headers:
```
Provisional headers are shown
auth-provider: custom
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5NjM2Y2UzLTE1NTUtNDkwYi1hMDQ2LWE3YmFjYzc3ZmI3MyIsIm5hbWUiOiJKYXkiLCJlbWFpbCI6ImpheUBmaXNoZWQuaW8iLCJyb2xlIjoiQ1VTVE9NRVIiLCJ2ZXJpZmllZCI6ZmFsc2UsImNvbXBhbnlJZCI6IjNhYzlkMGQzLTA5MjYtNDc2NC1iYjkxLTAzNjc2ODBkMjhlYiIsImlhdCI6MTYwMjE0MzA0MH0.qVvxWB4VJwx34fsIX0gm4i_--a-SPXtTpA1TXBPU_1g
content-type: application/json
Referer: https://example.com/log-in
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.70
```

**Comment by thedavidprice** [comment]
@jmcmullen thanks for creating this issue! Bummed it's not working correctly, but glad to hear the issue seems to be narrowed down to this.

@dthyresson @dac09 Any chance either of you has enough familiarity with this to take a look? Understood if not. I'll put it on a list for Peter to look into next week if that's the case. Just let me know.

**Comment by dac09** [comment]
Hey! So this isn't an issue I personally face, since we use a custom auth client (at the moment). 

However, it looks like the main reason we have this issue is this line here: https://github.com/redwoodjs/redwood/blob/820982917c9bb45b72b2438d4be41c3de8be588a/packages/auth/src/AuthProvider.tsx#L116

Can I ask a few more questions to clarify @jmcmullen? 
a) What is the endpoint you're using for your graphql API?
b) Where are you deploying your code?
c) Could you please try setting the apiProxyPath to the URL in `redwood.toml` I'm assuming from the forum post that your API is probably deployed elsewhere.

My thoughts right now:
- **Option 1:** Allow overriding of specific functions on the AuthProvider
- **Option 2:** Provide another environment variable in redwood.toml that RW will use if the variable is defined e.g.
```
[web]
  graphQLEndpoint = "https://api.mycustomlocation.com/api/graphql"
```

**Comment by thedavidprice** [comment]
Form topic for reference: https://community.redwoodjs.com/t/deploying-to-aws-and-hosting-the-api-on-a-subdomain/1251

Agreed @dac09 I feel like it's accidental a full URL is working. Or, better said, it wasn't an intentional part of the design.

I think Option 2 is the correct direction. Effectively I'd like us to:
1. assume the host is the same, so apiProxyPath is truly for the path
2. if the host is _not_ the same (for API, Web), have a config for `host` or `domain`

In the Auth example above, don't we need it end with `/graphql` because that's the API function? I guess people might roll their own endpoint, but then they won't be using the Redwood Auth provider, correct?

**Comment by jmcmullen** [comment]
>What is the endpoint you're using for your graphql API?

/graphql

>Where are you deploying your code?

AWS Lambda via Serverless

>Could you please try setting the apiProxyPath to the URL in redwood.toml I'm assuming from the forum post that your API is probably deployed elsewhere.

That's what I've done. 

I've created an example repo. Hopefully, it helps convey what I'm attempting to achieve:
https://github.com/jmcmullen/redwood-custom-auth/tree/sls-example

**Comment by dac09** [comment]
Hey, I'm going to continue the conversation on the forums! Thanks for the example repo @jmcmullen

**Comment by peterp** [comment]
I personally haven't experienced this either; I'm hosting mine API on` api.example.com` and my app on `app.example.com`

**Comment by jtoar** [comment]
> Hey, I'm going to continue the conversation on the forums!

@dac09 it's been a while but do you remember how this one went over on the forums?

**Comment by dthyresson** [comment]
Kurt raised a similar issue in Forums https://community.redwoodjs.com/t/cors-issue-specific-to-auth-request/2575 @Irev-Dev but I think it turned out to be serverless  yaml configuration. But maybe bear to check with him if this is the same thing he experienced.

**Comment by dac09** [comment]
These settings have likely changed since we moved to envelop. Worth looking into it, there's probably an envelop plugin but really this feels more in the realm of infrastructure.

**Comment by ajcwebdev** [comment]
We should check to see if the current [CORS docs](https://redwoodjs.com/docs/graphql#cors-configuration) handle this case just as written. I've used it for setting the configuration when using different domains with Docker containers, but I did not have any auth in the equation.

**Comment by Irev-Dev** [comment]
@jmcmullen How are you deploying?

If you're deploying such that the API is on a different domain than origin: '*', won't work as the wild card is not allowed for requests with credentials. Has nothing to do with RW, just a cors thing.

https://www.moesif.com/blog/technical/cors/Authoritative-Guide-to-CORS-Cross-Origin-Resource-Sharing-for-REST-APIs/#7--using-wildcard-when-access-control-allow-credentials-is-set-to-true

**Comment by dac09** [comment]
Closing this issue, as it actually has been resolved. 

Here's a walk through of using Tape configured with CORS, using firebase auth.


https://user-images.githubusercontent.com/1521877/156306904-1befa02a-60c7-4264-9c87-f40adae4cc4f.mp4



Db Auth working on CORS is a separate issue, and something that is covered in #4103
