### ISSUE TITLE
¿The next release will include the option to deploy on our own servers?

### ISSUE THREAD

**Issue by ad798** [redwoodjs/redwood#1315]
Hi, first things first so... I've been looking a while for a framework like Redwood! Awesome 🥳🙌🏼

Now my question. In docs is pretty obvious that deploy on cloud providers is covered. But, what if we want to run an awesome app built in Redwood in our own humble server?

Sorry if I wasn't meant to ask this here. Thank you for Redwood anyway. 🙌🏼

**Comment by ajcwebdev** [comment]
Peter has been working on a version of Redwood that can run in a Docker container so it can be easily deployed in various environments. I think it's still currently a work in progress but you can check out his talk about it from the [September 24th meetup](https://www.youtube.com/watch?v=bWxsgsd2GAQ&t=2460s).

**Comment by thedavidprice** [comment]
+1 to what Anthony wrote.

So overall things are close but there's no official support yet. In addition to the link to the video above:
- [Recap of notes and links from the Meetup](https://community.redwoodjs.com/t/sept-24th-meetup-recap-recording-topics-and-links/1217): see the section "Redwood + Production API Server"
- this [Serverful](https://community.redwoodjs.com/t/serverfull-hosting/1182) forum thread

You'll need to create your own Dockerfiles, etc. But otherwise, I believe all the pieces are in these links.

If you'd like to continue the conversation from here, why don't you reply to the Serverful forum thread? That way more people will see it and can help out. 

Good luck! And please keep us updated.

**Comment by ad798** [comment]
Thank you for that useful information. I am glad to read this answers, I will try to set up a production server based in the information provided and will continue this topic in the Serverful thread.
We all gonna love Redwood for a while.
