### ISSUE TITLE
Cookie based auth

### ISSUE THREAD

**Issue by Sventenhaaf** [redwoodjs/redwood#1329]
I'm orienting on Redwood (and so far loving it!)

Just wondering about Auth - I see all kinds of 3rd party auth providers being offered. Maybe not all of them are 3rd party, but every alternative still seems to use JWT based auth - using session tokens to be sent to the frontend and managed there.

Assuming (but not sure?) that, when using the out-of-the-box deployment options, the api and the frontend code are both hosted from the same domain, I'd say that plain old (http-only) cookie-based sessions would be a very good auth option to have. (Just like Devise does out-of-the-box for Rails). See also [this article](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/)

Like I said, I'm new to this so I may be missing something: 
- Maybe backend and frontend are actually hosted from a different domain?
- Maybe something with Serverless functions that doesn't make this a viable option?
- Maybe the whole thing doesn't work in combination with GraphQL (I'm new to GraphQL too, so I'm not sure how it works under the hood)
- Maybe one of the auth options is exactly this, and I'm too blind to see it?
- Something else?

Or maybe, which is the thing I hope for, the answer is: "Yes, this would be a good idea, but proper auth implementation is not easy - think about Oauth, forgot password flows, invite tokens, etc etc. Long story short - we'd love to offer this as an option but we don't consider it essential for version 1.0."

Anyway, I would love to learn more about Redwoodjs, and love to hear more about Redwoods current vision regarding auth. 

Keep up the good work and thanks,

Sven

**Comment by thedavidprice** [comment]
Hi @Sventenhaaf All great questions! I'm not an expert on Auth by any means, but I can connect you to a few great resources. The first of which is @dthyresson who's done a lot of Redwood work on Auth and RBAC. (DT, I recalled some conversations about experiments you tried regarding custom Auth... but was I just making that up?)

Secondly, there's been a lot of conversation about custom auth in our Forums, which is also a better context to continue this conversation:
- https://community.redwoodjs.com/t/custom-github-jwt-auth-with-redwood-auth/610
- https://community.redwoodjs.com/t/custom-auth-problem-with-getcurrentuser-and-protected-routes/1006

Regarding cookies vs. JWT, the short answer is "security", I believe. It's not always the case API and Web/Client are on the same domain, but if they are I'm not sure how/if cookies provide best security practices.

> "Yes, this would be a good idea, but proper auth implementation is not easy - think about Oauth, forgot password flows, invite tokens, etc etc. Long story short - we'd love to offer this as an option but we don't consider it essential for version 1.0."

^^ there are definitely use cases for custom auth. But for sure it's not easy. Yes to all those things and more. Given that Auth0 allows for 7,000 free users before charging you anything, if it's a possible vendor you can use then I'd 100% recommend going with Auth0 over rolling your own.

**Comment by dthyresson** [comment]
Hi @Sventenhaaf ... thanks for your interest in (and love of :) ) Redwood and for what you wrote.

I'm not sure I would consider how JWT is being used in RedwoodJS as "using JWT for sessions" ... in fact, the JWT's are rather short-lived and auto-refresh. In fact, the shorter the better. Auth0 will auto refresh as needed.

The tokens can have an expiration, set to be specifically for a particular audience, be issued from a certain authority, etc -- and all validated either via a secret or other keys.

Also, there really isn't a "session" per se as is done with Rails. See: https://medium.com/@sherryhsu/session-vs-token-based-authentication-11a6c5ac45e4 since this provides a nice overview:

![image](https://user-images.githubusercontent.com/1051633/95780102-490c3b00-0c99-11eb-8d94-261b91d78fa7.png)

vs

![image](https://user-images.githubusercontent.com/1051633/95780113-50334900-0c99-11eb-9c45-e54e7212f496.png)

Note that the "Server" in the JWT case for RW is a serverless function that extracts the token, validates and decodes on the api side ... and for the client side, the SDKs would talk to the auth provider's servers to fetch and often decode and validate the access token.

Sessions would be stored in memory (SPAs and serverless functions don't really have that) and the cookie is a reference to that session. There's no state. For example, if one was implementing a shopping cart, the cart contents would not be stored in the JWT.

That said, there is much discussion of storing JWT's **in cookies** vs localStorage. In fact, Auth0 recommends this.

JWT also allows the token to include metadata like profile info and role info that otherwise would have to be queried from a database based on that session reference.

On the whole, I have bee using Auth0 and other identity providers for 4+ years and I'm never going back. Given the responsibility and work to store, protect, manage, reset, change, invalidate, whitelist, audit, ensure PIAA is ok, email, confirm ... I'd rather build my app and integrate auth. 

My take is -- with most things new -- try it out and see what you like or don't like about it. And then I bet we can improve on the experience.

**Comment by thedavidprice** [comment]
Thanks @dthyresson for this amazing reply. And now I'm _really_ wishing this was happening on the Forums so others could find it more easily!

**Comment by Sventenhaaf** [comment]
Thanks so much for your elaborate replies. I'm definitely gonna try it out and see.  If I encounter discussions about Auth where this thread might be useful, I'll refer to this issue. 

And I hope to be able to contribute to anything meaningful to this project in the future. 

🚀

**Comment by dthyresson** [comment]
Just saw that Blitz is looking for testing their auth -- that has sessions: https://github.com/blitz-js/blitz/issues/1308

>  to see if we possibly have any vulnerabilities.

Good glimpse into everything it has to do: https://blitzjs.com/docs/session-management#how-it-works

**Comment by flybayer** [comment]
@dthyresson we're also going to be adding an advanced session management option that uses short lived JWTs plus refresh tokens. That will be a non-default, advanced option for us because that method introduces UX regressions with SSR (multiple redirects).

https://github.com/blitz-js/blitz/blob/canary/rfc-docs/03-session-management.md#advanced-short-lived-jwts-plus-refresh-tokens
