### ISSUE TITLE
VSCode extension using port 8000. Can this be configurable or use an uncommon port?

### ISSUE THREAD

**Issue by bennettrogers** [redwoodjs/redwood#1589]
I'm working on a Django API backend project (with a Redwood-frontend). I've got the Redwood IDE VSCode extension installed globally. I'm not sure when this started, but I've recently noticed that the Django development server wouldn't start, complaining that port 8000 is already in use. Disabling the Redwood IDE extension fixes the issue.

I'm not sure what the extension is using the port for, but would it be possible to use a less common port?

Thank you!

**Comment by Tobbe** [comment]
The extension has two parts. One which is the `structure` package in this repo. Another which lives in a repo of its own. I don't have access to the "other" part. But from what I can see in the `structure` package there is no mention of 8000 (or any port stuff at all really).

@aldonline This one is for you :)

**Comment by Darth-Knoppix** [comment]
I've been experiencing this too, I run multiple servers as part of development and have to disable the extension or run `kill $(lsof -t -i:8000)` to free the port beforehand.

**Comment by thedavidprice** [comment]
@aldonline this looks like a possible feature addition for the current re-write

**Comment by justinkuntz** [comment]
Constantly running into this as well. Would be good to have control over the port or when it runs.

**Comment by jtoar** [comment]
@justinkuntz do you still use the VS Code extension? We've been meaning to deprecate it for quite some time, so I wasn't actually aware of whether it still worked or not.

**Comment by justinkuntz** [comment]
@jtoar I disabled it.

**Comment by jtoar** [comment]
@robertwt7 It's not because we don't want it or don't think it's valuable, but just for the more usual reasons: not enough time, and no one is point on it at the moment so it's inevitably behind. We've been planning to deprecate it for a bit now (see https://github.com/redwoodjs/redwood/issues/4625).

If there's strong community interest in it, I can try to make the case to the core team that it should be reprioritized. It does seem like there's more interest in it than we initially thought.

**Comment by Josh-Walker-GM** [comment]
Hey all! I'm going to close this issue because we have fully deprecated and dropped support for the redwood vscode extension for the time being. We could in the future implement a new redwood extension but this isn't a priority for us right now unless there was a significant community demand. Feel free to reopen and start the discussion again at anytime!
