### ISSUE TITLE
RFC - API side utilities to help work with functions

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#1618]
In recent projects, I have been repeating code to do some common tasks related to api side functions and it could be helpful to add this utilities to the RedwoodJS api package:

1. Get the Netlify functions endpoint regardless of branch.

You will need to know the function endpoint url when invoking a background function from a RW api service -- especially when you have multiple environments or deploy previews.

Something like:

```
export const siteUrl = () => {
  const defaultUrl = `http://localhost:8910`

  try {
    const netlifySignature = context.clientContext?.custom?.netlify

    if (netlifySignature === undefined) {
      throw new Error('Undefined signature')
    }

    const signature = Buffer.from(netlifySignature, 'base64').toString('ascii')
    const decoded = JSON.parse(signature)

    if (decoded['site_url']) {
      return decoded['site_url']
    } else {
      throw new Error('Could not find site_url in jwt')
    }
  } catch (error) {
    console.error(`Unable to decode Netlify token from context: ${error}`)
    return defaultUrl
  }
}

const functionsUrl = ({ url }) => {
  return `${url}/.netlify/functions`
}
```

2. Sign function/background functions like webhooks to ensure these are not 100% open to execution by verifying the signature.

See https://github.com/quirrel-dev/secure-webhooks for some examples to sign a payload and verify it.

One might use JWS instead to sign the payload (the above uses a different technique).

3. A utility to wrap signing and sending in a single method

**Comment by dthyresson** [comment]
Some questions:

* good idea? ;)
* where could this go? in same place as `db`? make a `utlils` and import?

**Comment by peterp** [comment]
@dthyresson I think this is a great idea, but I also have some concerns about where we would place them. Since this example is specific to Netlify would you write a single function that knows the hosting environment? Or would you create separate files for each hosting environment?

Maybe this is just a module that you publish to npm?

**Comment by cannikin** [comment]
Is this the RFC for secure webhooks/functions? I had an idea for creating a function secured by a token. When you create, it could generate a random token and give it to you on the command line:

```terminal
rob$ yarn rw g function myEndpoint --secure-token

Generating secure function /api/src/functions/myEndpoint.js...done

myEndpoint is secured with token 912ec803b2ce49e4a541068d495ab570
An ENV var has been added to `.env` with this token.  Keep it secret, keep it safe! 

To access this endpoint remotely, include the token in an Bearer Authorization header:
{ 'Authorization': 'Bearer 912ec803b2ce49e4a541068d495ab570' }
```

So it appends a var to `.env`, something like `SECURE_FUNCTION_MY_ENDPOINT_TOKEN` and references it in the function itself when it comes time to check for the token:

```javascript
// @redwoodjs/api

const tokenAuthorization = (event, authToken) => {
  const headerToken = event.headers['Authorization'].split(' ')[1]
  return headerToken === authToken
}

const forbiddenResponse = {
  statusCode: 401,
  body: JSON.stringify({ error: "Invalid authorization token" })
};

// api/src/functions/myEndpoint.js

import { tokenAuthorization, forbiddenResponse } from '@redwoodjs/api'

exports.handler = async (event, context) => {
  if (!tokenAuthorization(event, SECURE_FUNCTION_MY_ENDPOINT_TOKEN)) {
    return forbiddenResponse
  }

  // implement your function here

  return {
    statusCode: 200,
    body: JSON.stringify({ message: `Hello world ${Math.floor(Math.random() * 10)}` })
  };
}
```

I'm sure there's a much cleaner way to implement this but you get the idea. And this to do a lot more work to make sure the header is present first, etc etc. Maybe we make a `secureHandler` instead of the generic `handler` and then the token checks can be hidden away in there:

```javascript
exports.secureHandler = async (event, context) => {
  securedWith("token", SECURE_FUNCTION_MY_ENDPOINT_TOKEN) 

  // implement your function here

  return {
    statusCode: 200,
    body: JSON.stringify({ message: `Hello world ${Math.floor(Math.random() * 10)}` })
  };
}
```

And then we can expand `securedWith()` to include more strategies, like "signature" or "allowList", "denyList"... although I'm not sure how you short-circuit the handler here if `securedWith()` finds that you're authorized...implementation details!

Anyway, that was my vision from yesterday had to get it out of my brain!

**Comment by jtoar** [comment]
Webhook helpers have been added! #1843

**Comment by dthyresson** [comment]
@jtoar Honestly, I forgot I wrote up this issue. The new webhook signature verifiers supports the features I needed when I wrote up this issue, so I think we can close this out.
