### ISSUE TITLE
`form.js` lint errors

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#162]
Running `yarn lint` results in the following errors:
```terminal
/redwoodjs-redwood/packages/web/src/form/form.js
  18:32  error  React Hook "useFormContext" is called in function "inputTagProps" that is neither a React function component nor a custom React Hook function  react-hooks/rules-of-hooks
  22:30  error  React Hook "useContext" is called in function "inputTagProps" that is neither a React function component nor a custom React Hook function 
```

@cannikin could you take a look?

**Comment by cannikin** [comment]
Yeah this happened to me before. The problem is that the form components are written in a standalone file that's meant to be used inside other components. So the calls to the hooks are "illegal" if you're only looking at `form.js` in isolation. But when you include these components inside your actual app's components they're being used correctly and don't cause a problem (that I've come across, anyway).

Maybe @peterp can look at this with me at some point and help confirm that it's not actually a bad thing.

In the meantime can we write an exception for the linter so it doesn't complain about these cases only in `form.js`, so you can get past that part?

**Comment by thedavidprice** [comment]
👍 I’ll add the linter exception for the two lines to get passing now in CI. 

Will leave this open for PP to take a look and confirm whether or not it’s an issue or not.

**Comment by thedavidprice** [comment]
has been fixed via exceptions
