### ISSUE TITLE
FetchConfigProvider and auth tokens

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#1759]
`FetchConfigProvider` used to provide the correct configuration when a user is authenticated or not:

1. The GraphQL endpoint
2. The authentication type
3. The authentication token

But, we no longer cache the authentication token. Instead we query the authentication client and ask for an auth-token on each request. Which is the correct thing to do.

So when creating a custom client you must request a new token on each request. In order to make that clear we need to do the following:

1. Remove the auth-token headers from `FetchConfigProvider` (or consider deprecating fetch config provider and replacing it with better documentation.)
2. Update https://github.com/MarceloAlves/redwoodjs-react-query-provider/tree/main/src so that is fetches a new auth token on each request.

**Comment by MarceloAlves** [comment]
I've updated my provider so that the token is requested before firing off 🚀

**Comment by doesnotexist** [comment]
If this issue is only about tokens (and not about deprecating FetchConfigProvider wholesale) then I think this issue can be closed.  This comment in FetchConfigProvider.tsx is accurate:

```js
/**
 * The `FetchConfigProvider` understands Redwood's Auth and determines the
 * correct request-headers based on a user's authentication state.
 * Note that the auth bearer token is now passed in packages/web/src/apollo/index.tsx
 * as the token is retrieved async
 */
```
https://github.com/doesnotexist/redwood/blob/main/packages/web/src/components/FetchConfigProvider.tsx#L19-L24

That is request to the api have bearer tokens populated by the graphql client which requests the token from the auth context/provider on each request https://github.com/doesnotexist/redwood/blob/main/packages/web/src/apollo/index.tsx#L117-L125

and similarly @MarceloAlves updated the redwoodjs-react-query-provider repo to request a token from Auth provider on each request.
https://github.com/MarceloAlves/redwoodjs-react-query-provider/blob/main/src/index.tsx#L60-L67

**Comment by jtoar** [comment]
Well said @doesnotexist, agreed!
