### ISSUE TITLE
re-deploy results in logged-in user encountering error message (screen of death)

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#1778]
@dac09 @Tobbe @dthyresson 
Something new I'm noticing when deploying using v0.25 release candidate (i.e. canary) --> If a user was previously logged in and then tries to visit the site after re-deployment, they hit the dreadful "Something Went Wrong" error (screenshot below).

I'm using my test repo which is a duplicate of the Redwood Tutorial project codebase. [Repo here](https://github.com/thedavidprice/redwood-tutorial-test). The file that results in the error [is here](https://github.com/thedavidprice/redwood-tutorial-test/blob/main/web/src/layouts/BlogLayout/BlogLayout.js) and specifically the `{isAuthenticated && <li>{currentUser.email}</li>}`. All my tests and re-deploys on previous versions have always worked seamlessly for logged in users.

> Note: I can confirm I've now replicated this locally

Right now my workaround is to delete `key: gotrue.user` from the browser Application Local Storage. I'm not sure if this effect is due to the implementation of `{isAuthenticated && <li>{currentUser.email}</li>}` or something due to change in the auth token behavior. Either way, not ideal 😬

<img width="800" alt="Screen Shot 2021-02-10 at 1 44 09 PM" src="https://user-images.githubusercontent.com/2951/107577384-381bf980-6ba7-11eb-85c7-7f566222bbc9.png">

**Comment by thedavidprice** [comment]
**Update:**
After an initial deploy that resulted in ScreenOfDeath, I deleted `gotrue.user`, refreshed to live page, then logged back in. From there, I just re-deployed (cleared-cache and redeploy on Netlify) and NO ISSUES. Stayed logged in. Page refreshed fine.

Possible path to replicate locally:
- Start with [this repo](https://github.com/thedavidprice/redwood-tutorial-test/tree/v0.24.0) on branch `v0.24.0` (still using SQLite locally)
- Yarn, rw dev, Setup Netlify Identity, Log In
- shut down server, upgrade to canary, then rw dev

**Comment by thedavidprice** [comment]
Well, bummer, I ran into this again today in production when upgrading my Netlify deployment (using Netlify Identity) from Redwood v0.25 to v0.25.1.

Same error as before.

Need to escalate this one. @dac09 any ideas?

**Comment by dthyresson** [comment]
One thing to test is to remove

```
    restoreAuthState: async () => {
      return client.currentUser()
    },
```

https://github.com/redwoodjs/redwood/blob/a9dc069749e91ce084e9afbbc5a0e7748ab45d05/packages/auth/src/authClients/netlify.ts#L50

from the Netlify AuthProvider.

I added this because several people had described cases when logging in and signing up via the Netlify Identity widget that the widget would close, but the page would have to be refreshed in order for `isAuthenticated` to take effect.

By adding this `restoreAuthState` no such refresh was needed.

This was tested in Auth Playground -- and these restoreAuthStates also helped in other providers when an OAuth provider did a callback.

Some differences between Auth Playground and this test repo is how `currentUser` is accessed:

```
  const { type, userMetadata, currentUser, isAuthenticated } = useAuth()
  const typeOk = type && type === currentUser?.type
  const emailOk = /^\w+@\w+.*\.\w\w+$/.test(userMetadata?.email)
  const tokenOk = currentUser?.token && currentUser?.token !== 'null'
```

https://github.com/redwoodjs/playground-auth/blob/main/web/src/components/AuthResults/AuthResults.js

* currentUser is safely optionally chained
* email is fetched from userMetadata an not currentUser

In the example repo https://github.com/thedavidprice/redwood-tutorial-test/blob/6b27e9fae0e74bd01d2fa14f60d55d78a6898348/web/src/layouts/BlogLayout/BlogLayout.js#L26

```
            {isAuthenticated && <li>{currentUser.email}</li>}
```

The question is why is a user authenticated but currentUser null?

Could the userMetadata data be valid but currentUser not?

https://github.com/redwoodjs/redwood/blob/a9dc069749e91ce084e9afbbc5a0e7748ab45d05/packages/auth/src/AuthProvider.tsx#L195

getCurrentUserMetadat may have the client decode the token client-side, but currentUser will make a graphql call:

https://github.com/redwoodjs/redwood/blob/a9dc069749e91ce084e9afbbc5a0e7748ab45d05/packages/auth/src/AuthProvider.tsx#L120

I would want to inspect the access token stored locally and then trace the api call to fetch the currentUser and compare.

**Comment by thedavidprice** [comment]
This is happening with every release and is going to bite someone's production app. Escalating to a high priority for current release sprint.

**Comment by dthyresson** [comment]
@thedavidprice Do you see this happen if:

* logged in to app via Netlify Identity
* trigger redeploy of app (no code changes)
* after done
* use app with same auth
* see error?

**Comment by thedavidprice** [comment]
Just tests this process. It does _NOT_ result in "Something went wrong" screen. Here's what I did:
1. logged into my deployed app. Then closed browser window.
2. from Netlify dashboard, Clear Cache and Redeploy
3. Once redeploy complete, visited the deployed app from new browser window
4. Page loaded successfully. Still logged in.

Just weird.

I stayed logged in so I can watch more closely during this upcoming release process.

**Comment by thedavidprice** [comment]
**Update:** I have not re-deployed. Visited my app today and re-encountered the screen-of-death.

Next time will try hard browser reset and cache clearing. And a bit more time.

**Comment by thedavidprice** [comment]
This just happened again upgrading to v0.28.3 https://redwoodjs-tutorial-test.netlify.app/

**Comment by dthyresson** [comment]
Do you build locally and set the widget? I still think there are leftover artifacts from identity's config in your browser local storage and the two tokens are not compatible.

**Comment by thedavidprice** [comment]
Ah, great idea. I'll definitely test that. Have a couple ideas. Thanks!

**Comment by thedavidprice** [comment]
@dthyresson I think you nailed it here. I did some (limited) experimenting with this during the QA process for v0.29 release. The failure does seem to correlate with 1) being logged in locally using `rw dev` 2) using the same browser, visiting the application after a deploy having been logged in on production prior to deloy.

Thanks for the help here!

Closing out.
