### ISSUE TITLE
How to enable SSR by default?

### ISSUE THREAD

**Issue by adrianmg** [redwoodjs/redwood#18]
Hi! First of all, thanks for making this happen, I've been playing with the different examples and I can't wait to see the progress on this, it's already really promising. I love the idea of having an end-to-end framework that answers the most recurrent questions.

I was wondering what will be the easiest way to enable SSR. I understand it shouldn't be that difficult as the stack is already using Apollo, any pointers?

I also would love to know how much of an impact will be on SEO having/not having SSR in the modern world, I've heard mixed opinions on the matter.

Thanks!

**Comment by mojombo** [comment]
We don't currently have any mechanism for SSR, as the only "server side" element right now is the GraphQL API deployed to Lambda functions. We do intend to provide an option for routes that will allow you to prerender portions of your website, which for certain cases, will provide similar benefits to SSR (especially around SEO).

As far as SEO in general, the latest I've read on the matter indicates that while the Google indexer will run Javascript just fine, there is always the chance that you deliver some JS code that is incompatible with their indexer and it fails to run your SPA as intended, leading to poor SEO. It's also possible that the way they run your JavaScript leads to slow "page loads" and your SEO suffers because of that.

Our main focus with Redwood right now is around developer experience and smooth integration of the fundamental technologies. We are definitely thinking about the impact of SEO and will be addressing that in the future, but for now Redwood is client-rendered only.

**Comment by ahmedosama5200** [comment]
So redwood is like `create-react-app` + `serverless node.js graphql api`. Am I right about that ?
What make `redwood` better that `next.js`. `Next.js` does `SSR`, `SSG` and client side rendering.

**Comment by thedavidprice** [comment]
Hi @ahmedosama5200 thanks for asking! A better place for this question would be the Redwood [Forums](https://community.redwoodjs.com) or Discord [Chat](https://discord.gg/redwoodjs) — the community is vibrant and helpful. Likely much more so than I can be!

Your comparison of Redwood to Next.js has solely focused on the Client in your example above. And that's where the difference lies. Redwood is a framework with first-class integration of a GraphQL API and Database integration; thus full-stack. Yes, it's designed for targeting serverless deployment, but you can also run it in traditional servers like AWS EC2. And, because it's a GraphQL API, you automatically get multi-client functionality. For example, many Redwood apps run more Clients than Web from a single API such as CLIs, Electron apps, React Native, and even Next.js (as a Web client).

SSR and SSG are all acronyms to descript various forms of managing assets with caching strategies, which ultimately is about managing performance aspects of an application. The next Redwood release will include a [built-in prerendering feature](https://github.com/redwoodjs/redwood/pull/1641) (so SSG). And there will be more improvements in 2021 to address features that improve Redwood at Scale.

**Comment by ahmedosama5200** [comment]
Thanks for replying @thedavidprice 
Why reinventing the wheel ? Why don't you use `next.js` under the hood ? It's really a great framework and It's only getting better.
I think your end goal is, having a full stack serverless framework without much boilerplate code. Next.js will save you a ton of work unless you're trying to compete with it.

**Comment by andresgutgon** [comment]
@ahmedosama5200 I think if you read carefully the docs or if you try to build a prototype with Redwood you would understand the benefits.

NextJs is great and they're building something awesome. But is less complete than Redwood in terms of what you can build. With nextjs you have to put your own conventions in things nlikebhow to store your data or how to authenticate your users nor how to fetch that data in the client. With Redwood all of that is built in the framework and that's where I think Redwood shines in my opinion :)

**Comment by andresgutgon** [comment]
A project that's trying to do what Redwood nodes is https://blitzjs.com/ and they're building not on top of Nextjs but that also has their tradeoffs. Like having to maintain compatibility with Nextjs.

I'm super happy to see so many awesome projects.

These are what I like:
- Nextjs
- Remix
- Redwood
- Blitz.js

**Comment by jtoar** [comment]
@ahmedosama5200 in the future when we work more on Redwood's concept of "sides", there's a good chance that Next.js can be one of Redwood's sides the way `web` is right now
