### ISSUE TITLE
v0.26.2 browser console warning

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#1894]
This warning is appearing in my Windows Chrome browser console after I upgraded Redwoodjs from v0.25.1 to v0.26.2

![image](https://user-images.githubusercontent.com/61768800/109595415-71fd7180-7b4f-11eb-8322-10e50c8d0c67.png)

Does anyone have this problem?

**Comment by realStandal** [comment]
Hiya, just so you don't feel alone I am getting this as well. I think it's because we're running the dev-server and it's not actively prerendering your content, and this is React complaining you're using `hydrate`. I'm not sure why the error persist _after_ removing `<%= prerenderPlaceholder %>` from `index.html`, because `@redwoodjs/web`-s source [should use the lack of it and a self-closed `<div id="redwood-app" />` as a means to not hydrate](https://github.com/redwoodjs/redwood/blob/main/packages/web/src/entry/index.js#L12). That's assuming the `<App />` there is the App-component you [created when upgrading](https://community.redwoodjs.com/t/redwood-v0-26-the-prerender-release/1872).

Back to the issue, sorry for getting side-tracked by curiosity, I think the fact that `yarn rw dev` produces no errors for my app, yet `yarn rw build` (including prerendering) does supports what I _think_ is happening. The prerender error is due to a library I'm using, not Redwood. But you see where my minds at with it; that is, unless Redwood silently prerenders and fails when running the dev server.

**Comment by thedavidprice** [comment]
Hi @andrew-hwahin Could you provide us more information:
1. can you confirm you completed the Code Modification steps in the [v0.26 Release Notes](https://community.redwoodjs.com/t/redwood-v0-26-the-prerender-release/1872)?
2. is this the home page, i.e. `/`, of your app? and did you set the `prerender` prop on this route (or any other routes)?
3. possible you could share the code for this project? Or at least your `web/src/App.js` and `web/src/index.html`? (Assuming you do not have a `web/src/index.js`, correct?)

@dac09 any other thoughts here?

**Comment by Tobbe** [comment]
The same error has also been reported as part of https://github.com/redwoodjs/redwood/issues/1887

**Comment by dac09** [comment]
@peterp has suggested a solution here https://github.com/redwoodjs/redwood/issues/1887#issuecomment-788758024

Thank you for raising this @andrew-hwahin, but from my understanding its just a warning and doesn't break your dev process?

**Comment by andrew-hwahin** [comment]
> Thank you for raising this @andrew-hwahin, but from my understanding its just a warning and doesn't break your dev process?

Yes, it doesn't break my dev process, I'm raising the issue to confirm if I upgraded Redwood correctly. 🙏😁

**Comment by thedavidprice** [comment]
> ... I'm raising the issue to confirm if I upgraded Redwood correctly. 🙏😁

Yes indeed! This one is on us, not you. 😉

Closing this in favor of #1887

Thanks, all!
