### ISSUE TITLE
`netlify dev` and `yarn rw dev` do not play well together

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#190]
When integrating Netlify Identity you ned to run `netlify dev`. Normally this will run whatever your app's dev process is and then inject netlify-specific stuff that it needs. `netlify.toml` can be updated to tell netlify-cli what command to run for your dev environment (this is already present in create-redwood-app).

However when running `netlify dev` the site doesn't really work and then hitting ctrl-c seems to start `rw dev` again (starting with Generating Prisma client...) and then ctrl-c on THAT process finally quits, but there are 8 `node` processes that continue running.

**Comment by thedavidprice** [comment]
@cannikin should we close out this issue for now? 

Assuming it’s going to come back around as we move forward on Auth integration work in the next few weeks… what say you?

**Comment by cannikin** [comment]
I meannnnnn it's definitely something we need to fix. You should be able to use `netlify dev` if you want to, even outside of any auth concerns (I just noticed the issue because I was trying to build out the auth section of the tutorial).

Are we going to create a new issue for it as part of the auth stuff? Or as a TODO checkmark in that issue?

**Comment by thedavidprice** [comment]
Fine either way. Was just assuming this would _have_ to come up once the Auth work was initiated. But there's not a tracking issue yet. 

I'll create a label for Auth and add it to this! We'll see if we can find it again that way when the time is right.

**Comment by peterp** [comment]
@cannikin Since we now mock the Netlify identitty experience in development we can probably close this off?

**Comment by cannikin** [comment]
Oh yes!

**Comment by marccantwell** [comment]
@peterp I read your comment about mocking the Netlify Identity experience, should that include the Identity Functions like identity-signup, identity-login, etc.? When I authenticate they are triggered, but they are triggered on the latest deployed version of the function to Netlify and interacting against my prod env config which includes my prod db. Is there a way to use Netlify Dev so that identity functions can get triggered locally rather than over the network?
