### ISSUE TITLE
ESBuild/Snowpack?

### ISSUE THREAD

**Issue by corysimmons** [redwoodjs/redwood#1905]
ESBuild is insanely fast.
https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0 is insanely fast and cool (streaming imports 🤤).

The reason some big OSS projects don't immediately adopt them is because they are waiting for more widespread 3rd-party plugins that map to already existing Babel/Webpack plugins... just in general.

Since Redwood is heavily opinionated, it might be possible to start using these tools today even if it requires creating a few ESBuild/Snowpack plugins yourself (it might not).

It might not be worth doing since devs using Redwood might lose access to being able to tweak their Webpack config (something you're proud of), but if you're just trying to make the best opinionated framework possible, it might be worth researching.

**Comment by thedavidprice** [comment]
Hi @corysimmons Thanks for this.

Internally we are already running some experiments with ESBuild and have indeed been excited about the results. So expect more to come in the form of an RFC for discussion or possibly a future PR for testing.

I'm going to close out this Issue for now since it's not actionable — don't get me wrong, we ❤️ the topic and discussion. This might make for a better Forum post in the meantime. Please don't hesitate to jump in and kick things off over here: https://community.redwoodjs.com (maybe try a search first... I believe ESBuild has come up a few times.)

**Comment by jtoar** [comment]
@corysimmons just to second what David said, there's definitely been some experimental integrations with it. Most of the action has been happening on our Discord chat: https://discord.com/channels/679514959968993311/747258086569541703/813699340542935040. 

It'd be awesome to have a forum post about it! It's definitely something a lot of people want to see and have thoughts on.
