### ISSUE TITLE
Initial app creation time is still too long

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1935]
Attached at the end is the log: note the **107.20s.** clock time

I used many different JavaScript development tools and frameworks - all of them take a lot less time to create the minimalistic app skeleton. Even making the needed accommodation for the fact that RW creates the full-stack app, **107.2 secs** is a too big number.

Probably the fastest way to address this initially is to not run the `yarn install` as a part of the first-time app creation, resulting in 107.0 shrunk to likely 15.0 The developer would have to type **both** commands `yarn create redwood-app ./test` followed by `yarn install` - the developer would not mind that and RW would not be blamed for a long lasting `install` phase.

I am not sure how to handle the creation of the information which follows the `yarn install` (is there some "callback" for `yarn install`??)

---

```
yarn create redwood-app ./test
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-redwood-app@0.26.2" with binaries:
      - create-redwood-app
  √ Creating Redwood app
    √ Creating directory 'c:\work\temp1\test'
  √ Installing packages
    √ Checking node and yarn compatibility
    √ Running 'yarn install'... (This could take a while)

Thanks for trying out Redwood!

We've created your app in 'c:\work\temp1\test'
Enter the directory and run 'yarn rw dev' to start the development server.

 ⚡️ Get up and running fast with this Quick Start guide: https://redwoodjs.com/docs/quick-start

Join the Community

 ❖ Join our Forums: https://community.redwoodjs.com
 ❖ Join our Chat: https://discord.gg/redwoodjs

Get some help

 ❖ Get started with the Tutorial: https://redwoodjs.com/tutorial
 ❖ Read the Documentation: https://redwoodjs.com/docs

Stay updated

 ❖ Sign up for our Newsletter: https://www.redwoodjs.com/newsletter
 ❖ Follow us on Twitter: https://twitter.com/redwoodjs

Become a Contributor ❤

 ❖ Learn how to get started: https://redwoodjs.com/docs/contributing
 ❖ Find a Good First Issue: https://redwoodjs.com/good-first-issue

Done in 107.20s.
```

**Comment by peterp** [comment]
I don't think the ideal situation involves moving the work from the framework to the user. I think the problem is that we install too many packages.

We mention in the step that `Running 'yarn install'... (This could take a while)` can take some time.

How do you think we should solve this @adriatic?

**Comment by adriatic** [comment]
> We mention in the step that Running 'yarn install'... (This could take a while) can take some time.

Yes, I am aware of that step, but in my opinion, it is not convincing enough. At least it is not convincing to me. 

>How do you think we should solve this @adriatic?

Let me explain my reasoning for providing more data to your question (quoted below).

> Probably the fastest way to address this initially is to not run the yarn install as a part of the first-time app creation, resulting in 107.0 shrunk to likely 15.0 The developer would have to type both commands `yarn create redwood-app ./test` followed by `yarn install` - the developer would not mind that and RW would not be blamed for a long-lasting install phase.

We do not offer much help to the user by including `yarn install` at the end of the `yarn create redwood-app ./test` command (no other CLI tool does that, to the best of my knowledge). At the same time, we are "apologizing" for the length of time `yarn install` takes. So, I am proposing to address both:

1. Take out the `yarn install` from `yarn create redwood-app ./test` 
2. Find why is it that we include too much "stuff" into our application.

**Comment by peterp** [comment]
> We do not offer much help to the user by including yarn install at the end of the yarn create redwood-app ./test command (no other CLI tool does that, to the best of my knowledge)

I can't see how this would change anything? The user is still required to run `yarn install`, and that will still take the exact amount of time. Do you want to shift the perception of the slow installation from Redwood to yarn?

We're not going to remove the yarn installation step.

> Find why is it that we include too much "stuff" into our application.

Yes please! Very much looking forward to a pull-request that helps us solve these issues! I think we can get fairly far by moving more things out of `@redwoodjs/core` into `@redwoodjs/testing` and `@redwoodjs/storybook`.

**Comment by adriatic** [comment]
> I can't see how this would change anything? The user is still required to run yarn install, and that will still take the exact amount of time. Do you want to shift the perception of the slow installation from Redwood to yarn?

Absolutely! Perception is everything. A random user would say, RW application creating is too slow, do not use it 😄 On  a more serious note: you are the boss, I just want to share my opinion, not to impose ot

**Comment by peterp** [comment]
Totally, I think you've raised an important point! We've got to make RWJS a bit more modular, and fast to do the first install. The rest of the packages can be installed when they're needed.

**Comment by adriatic** [comment]
Written communication provides only 5-10% of the information that gets exchanged between two people voicing out the same "text" together with all components of the "body language". I am really happy it took me only a few paragraphs to convey the message you spelled out so nicely:

>### We've got to make RWJS a bit more modular, and fast to do the first install

**Comment by adriatic** [comment]
> Totally, I think you've raised an important point! 
By separating the `yarn install` from `yarn create redwood-app ./test` we gain approx 50 sec. This is not a small potato.

**Comment by jvanbaarsen** [comment]
@adriatic I'm wondering if we are all on the same wave, so let's check that :-)

What is it that you want to achieve? Is it "just" an appearance of things being fast? Because I feel that having a "super fast" create RW would kinda be useless if the user would still need to perform `yarn install` to do anything meaningful after the create RW command.

So yes, you gained 50 seconds, and then you lose the 50 seconds again by 100% of the time needing to run `yarn install` anyways (Disregarding the fact that we might be able to make that quicker).

You made me curious by your statement that other "frameworks" don't do this, I just checked Create React App, but they also run `yarn install` directly after you create the app, and if I look at for example Ruby on Rails, they run `bundle install` as well as part of the `rails new` command.

So yes, you get the perception of RW being fast, and Yarn being a bottleneck, but I'm personally not so sure if that is fair to our users. It's not as if they can run RW without dependencies being installed.

**Comment by thedavidprice** [comment]
@jtoar another post v1-rc "project" is the overall installation and setup experience. Ideally, it would be a lot more Redwoody, which we need to define.

This topic definitely belongs in the related discussion when the time comes.

**Comment by jtoar** [comment]
@thedavidprice I've got a project card aggregating issues for that here: https://github.com/redwoodjs/redwood/projects/23#card-62823278. I've mentioned this one actually, wondering if Peter's PR reorganizing node_modules helped this at all (haven't dug deeper into it yet)

#252 is already being handled by @callingmedic911 in #2810 🚀

**Comment by thedavidprice** [comment]
> I've mentioned this one actually, wondering if Peter's PR reorganizing node_modules helped this at all (haven't dug deeper into it yet)

Not yet. But the future possible roadmap would indeed be an improvement if implemented.

**Comment by Dave-Wagner** [comment]
In my opinion, not that it matters, this is a solution to a problem that doesn't exist. Redwood is targeted at developers with a little bit of experience. Developers at this level are likely aware of the limitations of NodeJS in storing everything in the node_modules folder and are likely expecting all those packages to take a couple of minutes to download. If they are that concerned about it they are probably using Deno or Bun instead.

This solution targets developers that are likely not ready to take on the challenge of using Redwood in the first place. The scenario laid out is that a user might see the long load time and decide to switch to another framework. I contend this user isn't likely to succeed with Redwood just yet anyways and thus catering to the lowest common denominator.

**Comment by pantheredeye** [comment]
Linking to Peter's discussion on CLI improvements. [Redwood Talks: CLI and Open Source Community Health](https://youtu.be/ZL4mYn5yCG8?t=1)

@Dave-Wagner I feel the same way at some level, as-well. When devs are in a day-in-day out workflow, some things like this seem like it would not matter as much. But, also - @peterp is very experienced and I also respect his opinions, and other's, which for me gives weight to this idea. One thing he mentioned in the linked video is that the bundle size is a turn off for some devs. That right there is a reason for me to want to look at speeding things up and reducing file size.  I can identify with this, because I have felt similar feelings when I have tested out other tools. 

Also, I have gone in and out of moments where I create multiple redwood apps within a 1-2-3 week span for random ideas, and I have felt the slowness then.

Something like `yarn create redwood-app --lean` vs the default full version, where certain options like storybook could be unbundled, is an attractive idea. However, what are the speed benefits here vs difficulty in achieving this functionality. From above: 

> Totally, I think you've raised an important point! We've got to make RWJS a bit more modular, and fast to do the first install. The rest of the packages can be installed when they're needed.

The initial idea from Tom is that Redwood sets your application up for the long haul, scaling with teams using storybook and tests, etc. right out of the box. That is important for many, but perhaps not for some who are looking to initially hack together an idea. I have started repeating others at this point. Thanks for dropping the comment in the bucket :D

**Comment by adriatic** [comment]
I started this discussion almost two years ago, a few weeks after I started using RedwoodJS. My previous experience was with Aurelia, Gatsby and NextJS, so my initial comments on "slow" RWJS were influenced by that experience. Now, I think that @pantheredeye's comment:

> The initial idea from Tom is that Redwood sets your application up for the long haul, scaling with teams using storybook and tests, etc. **right out of the box**.

is the most valuable contribution in this discussion (anyone interested in this thread may decide to scan a lot longer version [here](https://community.redwoodjs.com/t/basic-app-redwoodblog-creation-took-79-50-sec/1745/20)

Issues like shrinking the size of node_modules via tricks like [`.npmignore`](https://docs.npmjs.com/cli/v8/using-npm/developers#keeping-files-out-of-your-package) are not worth the likely introduced risks and are less effective than [`pnpm`](https://pnpm.io/) package manager that was designed to specifically attack this problem.

It is good that this issue survived as long as it did - user's perceptions are important, and we should care about them. 

---

Today's measurements for how long it takes to run `yarn create redwood-app ./redwoodblog`:
```
yarn create redwood-app ./redwoodblog  82.77s user 62.32s system 178% cpu 1:21.41 total
```
application size on disk: 1.2 GB, 864.4 MB of which taken by node_modules.

Just the link step (running yarn install after removing `node-modules`
```
yarn install  30.13s user 56.41s system 269% cpu 32.110 total
```

It will be interesting to see what the the yarn plug and play strategy would improve (if and when it gets used in RW)

**Comment by pantheredeye** [comment]
@Josh-Walker-GM has addressed some of this, it seems, with the goal of getting to `yarn install` improvements sometime in the future...

> Some create-redwood-app improvements:
> - Install size is 83% smaller (117MB to 19.2MB)
> - Overall package dependency count reduced by >60% (461 to 167)
> - Benchmarks on creating a project (without yarn-install) shows 60% speed improvement (avg of 13.7s to 5.4s)
>
> We've got more ideas on how to go even further

**Comment by thedavidprice** [comment]
100% this is now resolved! 

Keep us posted — feedback on the new experience is very welcome.
