### ISSUE TITLE
create-redwood-app should fail if the requirements are not met

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwood#1968]
At the moment 3/112021 6:05 pm EST it generates some code - and only then realizes that it should not have generated any

![image](https://user-images.githubusercontent.com/2712405/110867650-18a2ea00-8295-11eb-93d4-834fd149becb.png)

**Comment by callingmedic911** [comment]
@jtoar I just replicated this locally and makes sense to break early. Changes seems like straightforward to implement. Is it okay if I pick this one?

**Comment by thedavidprice** [comment]
help on this would be fantastic @callingmedic911 🚀

The problem right now is that the engines are _after_ creating a project directory and copying the template codebase. Ideally, this step should come first:
https://github.com/redwoodjs/redwood/blob/a83b3fd842d4e0440c287d750ffd56ccecd70c02/packages/create-redwood-app/src/create-redwood-app.js#L118

Not only does the script fail, but the process leaves behind the new directory — silently. The next time the use tries to run the script, they get another error because the directory already exists. Frustrating!

But there are probably two approaches:
1. Ideally, first run the engine check task, which you should be able to do because the template codebase is now included in the package itself at `template/package.json`
2. If for some reason that isn't efficient, you could keep the order of tasks but then run a clean-up task to remove the directory. (Or, at least warn the user that the directory was created and most likely should be removed.)

Nice to have:
- if engines fail, give link to help doc in the error console message
- at anytime in the process, if the script fails, check if the directory was created and warn use there is now a directory even though the process failed (depending on where this happened in the process, the user might be able to recover or need to debug, so it shouldn't be a default that the script always deletes the directory by default.)

**Comment by callingmedic911** [comment]
Thanks for the details @thedavidprice, very helpful!

I'm inclined towards first approach you explained. Failing early and providing info to the user fast will be better DX in my opinion.

Will raise the PR shortly.
