### ISSUE TITLE
Allow partial matches with NavLink

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/redwood#2362]
Currently the NavLink only matches on a full path match, there is a way to do some things yourself with `useMatch`, but also this one doesn't really allow you to set custom rules.

In my case for example I have these two routes that both should make the same item active:

```jsx
          <Route path="/tasks/completed" page={TasksPage} name="completedTasks" />
          <Route path="/tasks" page={TasksPage} name="tasks" />
```

Wouldn't it be awesome if we can also do partial matches? Or maybe use a regex or something. So you'd get an API like this:

```jsx
<NavLink to={routes.tasks()} match={^tasks\/.*$}>Tasks</NavLink>
```

Or if we don't want to enter the RegEx minefield we could maybe do something like this:

```jsx
<NavLink to={routes.tasks()} match="tasks/*">Tasks</NavLink>
```

**Comment by dthyresson** [comment]
I have also had cases where my link has a querystring (ie, for tab nav) and the NavLink cannot look into the param values to determine that a particular tab referenced in the url is the active tab.

**Comment by LBrian** [comment]
Hey,

I would love to take this one as my first contribution if I can get more context from team, since this is a really interesting topic when taking `prerender` into account, is that the primary reason of why `@redwoodjs/router` doesn't support partial match at the beginning? I remembered came across some discussions on RW community page about this.

**Comment by LBrian** [comment]
Yap, as I expected, so should we just ignore `prerender` then for partial match? also, to simplify things, should we just add a new boolean `exact` prop to toggle exact/partial match instead of supporting `match` for regex which I can think of many scenarios will need complicated path match using regex based on using `react-router` for years so far, but this is just my opinions, would like to hear you guys thought 😃 

![Screen Shot 2021-05-24 at 3 33 29 pm](https://user-images.githubusercontent.com/3888780/119301357-afccea80-bca5-11eb-8492-3e57266073de.png)

**Comment by jtoar** [comment]
@LBrian awesome! And wow you've done your research on this already.

> is that the primary reason of why @redwoodjs/router doesn't support partial match at the beginning?

This probably isn't the primary reason why, but I'll tag @dac09 who gave us prerender to get his thoughts here. 

> so should we just ignore prerender then for partial match?

Going to tentatively say yes but looking to @dac09 for the final yes/no. 

> to simplify things, should we just add a new boolean exact prop to toggle exact/partial match instead of supporting match for regex which I can think of many scenarios will need complicated path match using regex based on using react-router for years so far, but this is just my opinions, would like to hear you guys thought

That would be similar to what was suggested in https://github.com/redwoodjs/redwood/issues/156#issuecomment-592725261 for a similar problem, so that seems like the way forward to me. That or something similar to what @jvanbaarsen suggested above:

> ```
> <NavLink to={routes.tasks()} match="tasks/*">Tasks</NavLink>
> ```

@peterp was thinking about changing a glob syntax we use for services in https://github.com/redwoodjs/redwood/issues/2077, maybe there's some overlap?

Definitely feel free to work on this; I'll make sure we get feedback on the `exact` prop going in this thread.

**Comment by dac09** [comment]
@LBrian thanks for offering to help!

Re: prerender - no the router's internal logic actually doesn't really have anything to do with prerender, as prerender is a build time operation and it simply looks at your paths to give it the correct filename/folder. 

Just to make sure we're on the same page, the goal is to modify the `NavLink` component to be less specific but not really change the router logic correct?

**Comment by LBrian** [comment]
@dac09 Correct! Nothing to do with `prerender`, it just current architecture we will need to whitelist dynamic routes in order to generate static pages for `prerender` and I was suspecting that is one of the reason route partial matching is not supported at the first place.

This PR is mainly modifying `NavLink` to support partial match either a new prop `exact` or `match` for Regex.

**Comment by LBrian** [comment]
@jvanbaarsen Just to clarify your case to get more context, when you declare `<NavLink to={routes.tasks()}  />` you actually tell Redwood navigates to `/tasks` because `/tasks/completed` is `routes.completedTasks()` as exact 1-1 match, so you suggest `NavLink` to have partial match (wildcard) ability to navigate to the first match base on `Routes` order? (i.e. `/tasks/completed` will be the destination.

```jsx
<Route path="/tasks/completed" page={TasksPage} name="completedTasks" />
<Route path="/tasks" page={TasksPage} name="tasks" />
```
![Screen Shot 2021-05-25 at 10 00 30 am](https://user-images.githubusercontent.com/3888780/119420651-5665c980-bd40-11eb-9646-3ebc19c9a62f.png)

**Comment by jtoar** [comment]
@LBrian I've pinged some of the team to get more feedback for you!

**Comment by LBrian** [comment]
Quickly looked into the code base and tested it, this is my draft proposed solution, **I will wrap it up and create a PR later this evening** as I will need to test more scenarios and ensure this is robust

We should pass `location.search` to `matchPath` as well
![Screen Shot 2021-05-29 at 10 59 08 am](https://user-images.githubusercontent.com/3888780/120053330-eff8e800-c06c-11eb-80f0-e0824bd67092.png)

then in the `matchPath` we should just escape `?` in the queryString since we don't want to replace all other reserved characters in `typeRegex`
![Screen Shot 2021-05-29 at 10 58 57 am](https://user-images.githubusercontent.com/3888780/120053338-f4bd9c00-c06c-11eb-8d65-766d1fd24078.png)

**Comment by LBrian** [comment]
@dthyresson PR #2683 

@jtoar @jvanbaarsen After deep dive into the code, I am suspecting adding partial match to `NavLink` could potentially complicate the logic as we will need to consider search parameters too (aka `queryString`), could introduce more bugs and not easy to maintain. I will suggest to lower the priority fo this requirement for the moment and revisit once we have more use cases.

**Comment by jvanbaarsen** [comment]
@LBrian That would all still be possible with using a regex right? You can then basically ignore everything after a specific point? Or is that not what you mean?

**Comment by LBrian** [comment]
> @LBrian That would all still be possible with using a regex right? You can then basically ignore everything after a specific point? Or is that not what you mean?

@jvanbaarsen 100% agreed with your point and no doubt logically it is possible. However, if we take necessity and complexity factors into consideration, your example can also be achieved by

```jsx
<Route path="/tasks" page={TasksPage} name="tasks" />
```
navigate to `tasks`
```jsx
<NavLink to={routes.tasks()}>Tasks</NavLink>
```
navigate to `completedTasks `
```jsx
// activeMatchOptions is in PR https://github.com/redwoodjs/redwood/pull/2683
<NavLink to={routes.tasks({completed: true)} activeMatchOptions={{ignoreQueryString: true}}>Tasks</NavLink>
```

hopefully this makes sense to you
