### ISSUE TITLE
When node and yarn requirements aren't met fail gracefully

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#252]
Right now we rely on mechanisms with node/ yarn. It would be great to clean up after ourselves and let the user know what they can do next.

**Comment by jvanbaarsen** [comment]
@peterp Can you add to this issue what the requirements are? That would make it easier for people to pick it up. (@thedavidprice assuming you're not working on this?)

**Comment by thedavidprice** [comment]
Hi @jvanbaarsen Thanks for jumping in on this one. This is the [Redwood installation package code](https://github.com/redwoodjs/redwood/tree/main/packages/create-redwood-app). Here's what was going on at the time this was created. 

## Problem
When a user runs `yarn create redwood-app my-project`, the process begins by 1) creating a new directory `my-project/`, 2) copying the template codebases files, and then 3) running `yarn`. 

It's not until step 3 that the Yarn and Node.js engines are checked for matching requirements. If they are not met, the process will throw an error, quit, and leave the user with a new directory with files. There's no instructions to the user and the files being left behind is unexpected, which can lead to different failures when the installation script is run again, `error: directory exists...`. Frustration ensues. 

At the time, our Node and Yarn requirements were current, so it was more common for people to need to update first. One year later, it's not as much of a problem but likely still worth improving.

## A Better Way
Improvements to this experience would include:
- checking Node.js and Yarn engine requirements _as the first step_ of the installation process, 
- running a cleanup + outputting more helpful error and next step messaging, 
- or a combination of both. 

At the time this Issue was created, the Template codebases resided in a different repo. Now it is packaged with the installation script, which makes it very convenient to check engines at the start.

**Comment by jtoar** [comment]
For reference, this is what it looks like right now. It does say what's wrong in a fairly straightforward way, but it's mired in all this output:

![image](https://user-images.githubusercontent.com/32992335/119052782-f951c880-b979-11eb-8b50-8f1f86712e79.png)

**Comment by jtoar** [comment]
Closed by #2810
