### ISSUE TITLE
BUG: Insufficient permissions when running without sudo in Ubuntu

### ISSUE THREAD

**Issue by pdjota** [redwoodjs/redwood#2638]
Hello, I was redoing the steps of creating an app, such as
`yarn create redwood-app ./redwoodblog`

And I get permission errors with cordova, part of the output:
```
success Installed "create-redwood-app@0.32.2" with binaries:
      - create-redwood-app
error Cannot create "/usr/local/bin/cordova-res" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
Which halts the installation.
When I repeat the procedure with:
`sudo yarn create redwood-app ./redwoodblog`

It creates correctly the directory but it is a security challenge to run yarn with sudo permissions, and don't forget to chown from root to normal user.

Is there a better way to debug it?

If I actually clone `redwood` repo and create the the app with 
`yarn babel-node packages/create-redwood-app/src/create-redwood-app.js ../redwoodblog`
It works as expected.

Versions:
Ubuntu 20.04.2 LTS

**Comment by thedavidprice** [comment]
@pdjota This is a strange one. I believe it's something with your system and not directly related to Redwood. 

What versions of Node.js and Yarn are you using?

I ran this check:
```
$ yarn why cordova-res
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "cordova-res"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.82s.
```

`cordova-res` is not a Redwood dependency.

Sometimes this happens because of the way you've installed Node.js and/or Yarn. For your system we recommend nvm to manage Node.js installation and versions. Then you can use npm to install yarn v1.
- For nvm, see our Tutorial Prerequisites: https://learn.redwoodjs.com/docs/tutorial/prerequisites
- And then use npm to install yarn: https://classic.yarnpkg.com/en/docs/install/#mac-stable

Given that you've been doing development and having success, I'm not sure you need to go through those steps...

## Installation using create-redwood-app
### Options
When `yarn create` is run, it first installs the package globally and then runs the package contents. In your case, it looks like the first step to install globally is successful. 

You could try `yarn create redwood-app <directory> --no-yarn-install --ts`, which will skip the `yarn install` step and create a TypeScript project. After installation. You would need to manually:
- `yarn instal`l
- `yarn rw ts-to-js` (if you want JS as your language target)

### Try `npx`
Alternatively, you can use `npx` in place of `yarn create`. E.g.
- `npx create-redwood-app <directory>` uses NPM to download globally and run the package script, which will then switch over to yarn for the installation. All options can still be used.

----

Curious to know how it goes. Please keep me posted.

**Comment by pdjota** [comment]
Indeed there must be something wrong in my setup. I'll close it for now.
when running it with `--verbose` seems that yarn is doing some post-install setup
```bash
[4/4] Building fresh packages...
success Installed "create-redwood-app@0.32.2" with binaries:
      - create-redwood-app
verbose 5.195579816 Error: Cannot create "/usr/local/bin/cordova-res" due to insufficient permissions.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at throwPermError (/usr/share/yarn/lib/cli.js:35970:15)
    at /usr/share/yarn/lib/cli.js:36038:11
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
error Cannot create "/usr/local/bin/cordova-res" due to insufficient permissions.
```

```
yarn -v
1.22.5
nvm --version
nvm, version 2.2.1
node -v
v14.17.0
```

**Comment by thedavidprice** [comment]
Versions look good.

Very very strange... 🤔

**Comment by razzeee** [comment]
Getting a similar error in fedora

```
❯ yarn create redwood-app ./my-redwood-test
yarn create v1.22.17
[1/4] Resolving packages...
warning create-redwood-app > @redwoodjs/telemetry > @redwoodjs/structure > @prisma/sdk > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-redwood-app > @redwoodjs/internal > babel-plugin-graphql-tag@3.3.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript-react-apollo@3.2.14" has unmet peer dependency "graphql-tag@^2.0.0".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/disable-introspection@3.3.2" has unmet peer dependency "@envelop/core@^2.3.2".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/filter-operation-type@3.3.2" has unmet peer dependency "@envelop/core@^2.3.2".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/validation-cache@4.3.2" has unmet peer dependency "@envelop/core@^2.3.2".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/depth-limit@1.5.2" has unmet peer dependency "@envelop/core@^2.3.2".
warning "create-redwood-app > @redwoodjs/internal > @redwoodjs/graphql-server > @envelop/parser-cache@4.3.2" has unmet peer dependency "@envelop/core@^2.3.2".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/cli > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning "create-redwood-app > @redwoodjs/internal > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@12.0.0" has incorrect peer dependency "graphql@^15.0.0".
[4/4] Building fresh packages...
success Installed "create-redwood-app@1.5.1" with binaries:
      - create-redwood-app
error Cannot create "/usr/local/bin/create-redwood-app" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Running with sudo, would obviously work, but all files would get that permission level and it shouldn't be necessary.

Installing create-redwood-app via `npm i -g create-redwood-app` seems to work and I can see the binary being there, but the scrip still fails with the same error. Probably as it tries to create that link anyway?
