### ISSUE TITLE
Upgrading redwood from v0.32.2 to v0.33.2 causes react-hook-form error.

### ISSUE THREAD

**Issue by andrew-hwahin** [redwoodjs/redwood#2763]
![image](https://user-images.githubusercontent.com/61768800/121128419-f43bb700-c85d-11eb-9289-90e9e2691485.png)

![image](https://user-images.githubusercontent.com/61768800/121131711-c2791f00-c862-11eb-86da-4dc6f068c4d5.png)

![image](https://user-images.githubusercontent.com/61768800/121131929-0ff58c00-c863-11eb-8714-31462fbb91a8.png)

Related [release v0.33.0](https://github.com/redwoodjs/redwood/releases/tag/v0.33.0)
![image](https://user-images.githubusercontent.com/61768800/121133153-952d7080-c864-11eb-8888-6bc02342091c.png)

Related PR #2637
https://github.com/redwoodjs/redwood/commit/91537497646701faaf04105c5eb4508539806268#diff-91f7ef7efd69d5f368b11e29c197463c36691477cbb7164da8f617346fab96c7L15

After adding react-hook-form to my web workspace `yarn workspace web add react-hook-form@^6.15.7` the error is disappeared.✌🥂
May I ask if my approach appropriate and will it cause any problem down the road? 🙏🙇‍♂️
I'm concern that there might be a reason for the react-hook-form to be maintained at version 6.9.5 instead of 6.15.7

cc @thedavidprice

**Comment by thedavidprice** [comment]
Ah, this is very interesting (and definitely frustrating on your end!). You are correct that we made a change to "pin" package dependencies in the Redwood Framework. The reason being that we were seeing all kinds of strange, and often incorrect, Yarn dependency resolution issues. Yarn.lock was behaving strangely for some projects — just like in the case with yours where you were using an installed version of react-hook-form that should not have ever been semantically allowed. How did this happen? We don't know other than to believe it's a kind of systematic error with Yarn.

> May I ask if my approach appropriate and will it cause any problem down the road? 

^^ Your solution is exactly what I would have done. HOWEVER, there is one potential future catch --> once the Redwood Framework upgrades to a version beyond v6.15.7, your project will still be "forced" to use v6.15.7. 
- Just watch the Release Notes for Redwood and once RHF is upgraded in the Framework, remove it from your package.json in your project

### Upgrading to RHF v7
Our goal for Redwood v1 is to upgrade RHF to v7. The PR in progress is here https://github.com/redwoodjs/redwood/pull/2270

It has stalled out a bit due to a lot of breaking changes. If you are interested and available to help diagnose the upgrade, your help would be greatly appreciated! Just coordinate with Morgan Spencer in the PR. But no pressure, we'll get to it eventually.

---

If all this makes sense and resolves your question for now, please do close this Issue.

And keep us posted!

**Comment by andrew-hwahin** [comment]
@thedavidprice thank you very much for the detailed explanation 🙏🙇‍♂️
