### ISSUE TITLE
UUID in routes param is not working

### ISSUE THREAD

**Issue by bigint** [redwoodjs/redwood#2841]
![image](https://user-images.githubusercontent.com/69431456/122190979-f29e6e80-ceaf-11eb-97b8-218ab0c31daa.png)

## Route

```
<Route path="/@{id:String}" page={UserPage} name="user" />
```

## Schema

```
model User {
  id        String   @id @default(uuid())
  email     String   @unique
  username  String   @unique @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @default(now())
}
```

## Route call

```
<Link to={routes.home(currentUser.id)}>
    {currentUser.email}
</Link>
```

**Comment by peterp** [comment]
Hey @bigint, you  have to do something like `routes.home({ id: currentUser.id })`

**Comment by bigint** [comment]
@peterp The URL looks like this

![image](https://user-images.githubusercontent.com/69431456/122198969-41033b80-ceb7-11eb-8059-1f9a71fa20f4.png)

instead of `http://localhost:8000/@c5440bfc-d51b-4de1-8954-ab4cbf2cb686`

**Comment by dthyresson** [comment]
@bigint Looking at the Router docs here https://redwoodjs.com/docs/redwood-router#route-parameters see that:

```
<Route path="/blog/{year}/{month}/{day}/{slug}" page={PostPage} name="post" />
```

When the route parameter os a String, you don't need to set the type of string

```
<Route path="/@{id}" page={UserPage} name="user" />
```

Of course, I do see you want to prepend an `@` between the root and the id ... which might be the issue ... the root.

But, as @peter said:

> you have to do something like routes.home({ id: currentUser.id })

```
If a route has route parameters, then its named route function will take an object of those same parameters as an argument:

// SomePage.js

<Link to={routes.user({ id: 7 })}>...</Link>

All parameters will be converted to strings before being inserted into the generated URL.
```

> If you specify parameters to the named route function that do not correspond to parameters defined on the route, they will be appended to the end of the generated URL as search params in key=val format:

It might be the `:String` that is throwing it.

I'd give:

```
<Route path="/@{id}" page={UserPage} name="user" />
...
<Link to={routes.user({ id: currentUser.id  })}>...</Link>
```

or


```
<Route path="/@/{id}" page={UserPage} name="user" />
...
<Link to={routes.user({ id: currentUser.id  })}>...</Link>
```



Oh wait ...

```
<Route path="/@{id:String}" page={UserPage} name="user" />
```

You named the route `user` but are navigating to `home`?

Keep same but do 

```
<Link to={routes.user(currentUser.id)}>
    {currentUser.email}
</Link>
```

instead of

```
<Link to={routes.home(currentUser.id)}>
    {currentUser.email}
</Link>
```

**Comment by bigint** [comment]
Thanks @dthyresson 

It seems like working with

```
<Route path="/@/{id}" page={UserPage} name="user" />
```

but not with

```
<Route path="/@{id}" page={UserPage} name="user" />
```

**Comment by dthyresson** [comment]
Hi @bigint I'm not sure you can prepend string values in the param replacement. 

Like

```
<Route path="/@{id}" page={UserPage} name="user" />
```

It may be parsing the values within `/`s and `@+id` doesn't match up with the replacement of just `id`.

But, perhaps the `@` is troublesome?

**Comment by bigint** [comment]
> But, perhaps the @ is troublesome?

Yes!

**Comment by dthyresson** [comment]
Does 

```
<Route path="/u{id}" page={UserPage} name="user" />
```

`u` instead of `@` work?

**Comment by dthyresson** [comment]
I just don't think that the route path can have preprended info in the path.

But if you really need the `@` here's what you can do:

In your SDL for the user, define a `slug`

```
    slug: String!
```

Then, wherever you populate your user, maybe in `getUser`? ... set the 

```
slug: `@${decoded.sub}`
```

Or something such that now you have a named attribute

`slug: "@c5440bfc-d51b-4de1-8954-ab4cbf2cb686"`

And then use that:

```
<Route path="/{slug}" page={UserPage} name="user" />
```

and

```
<Link to={routes.user({ slug  })}>...</Link>
```

You don't need `slug: slug` here as you did with `id: currentUser.id` since it's the same name.

**Comment by bigint** [comment]
Great thanks 👍🏻

**Comment by dthyresson** [comment]
> Great thanks 👍🏻

Glad that helped. Can I close out this issue?

**Comment by bigint** [comment]
Sure @dthyresson

**Comment by Tobbe** [comment]
Here's another issue about the same thing: https://github.com/redwoodjs/redwood/issues/2019
And this one is linked from the one above https://github.com/redwoodjs/redwood/issues/1702
