### ISSUE TITLE
MissingBeforeResolver everywhere

### ISSUE THREAD

**Issue by noire-munich** [redwoodjs/redwood#2879]
So, I opted in secured services today, which felt easy to implement.
However, it appears I'd have to add the beforeResolver to any file in my api/src/services/**/* as per this which pops in my terminal:

```cli
api esbuild | MissingBeforeResolver: Must define a `beforeResolver()` in src/services/accountPaymentConfigurations/index/d
api esbuild |     at makeServices (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api/dist/makeServices.js:32:13)
api esbuild |     at Object.<anonymous> (/Workspace/Code/SportOffice/api/dist/functions/graphql.js:3823:45)
api esbuild |     at Module._compile (internal/modules/cjs/loader.js:1185:30)
api esbuild |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
api esbuild |     at Module.load (internal/modules/cjs/loader.js:1034:32)
api esbuild |     at Function.Module._load (internal/modules/cjs/loader.js:917:16)
api esbuild |     at Module.require (internal/modules/cjs/loader.js:1074:19)
api esbuild |     at require (internal/modules/cjs/helpers.js:72:18)
api esbuild |     at setLambdaFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:35:9)
api esbuild |     at withFunctions (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api-server/dist/middleware/withFunctions.js:79:3)
```

And I do mean any file, even the `index.d.ts` files to declare my module's types.

Is this really the desired behaviour?

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.0.0 - /tmp/yarn--1624454722295-0.4335277431123732/node
    Yarn: 1.22.5 - /tmp/yarn--1624454722295-0.4335277431123732/yarn
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    @redwoodjs/core: ^0.34.1 => 0.34.1 

Done in 11.04s.
```

**Comment by dthyresson** [comment]
Hi @noire-munich did you add 

```
export const beforeResolver = () => {}
```

as per: https://redwoodjs.com/docs/services#securing-your-services

And then implement a rule like:

```js
import { requireAuth } from 'src/lib/auth'

export const beforeResolver = (rules) => {
  rules.add(requireAuth)
}
```
?

If not, then yes, that error I believe is expected. 

@cannikin is that correct? Could we add some info to help direct the user as how to resolve that error message?

**Comment by noire-munich** [comment]
@dthyresson yes!
My bad, more info on the service in question, `api/src/services/accountPaymentConfiguration`:

it has a `accountPaymentConfiguration.ts` file at its root which contains the following:
```ts
import { UserInputError } from '@redwoodjs/api'
import type { BeforeResolverSpecType } from '@redwoodjs/api'

import { db } from 'src/lib/db'
import { requireAuth } from 'src/lib/auth'
import { logger } from 'src/lib/logger'
import StripeCreateAccount from './Stripe/createAccount'

// Used when the environment variable REDWOOD_SECURE_SERVICES=1
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.add(() => requireAuth({ roles: ['manager'] }), {
    only: ['createSellerAccount'],
  })
}

// ... endpoint methods
```

It has a `index.d.ts` at its root which contains the following type draft :

```ts
type Provider = 'Stripe'

type CreateSellerAccountArgs<Provider = 'stripe'> = {
  accountId: number
  email: string
}

type CreateSellerAccountPayload<Provider = 'stripe'> = Promise<{
  reference: string
}>

/**
 * Create the Seller's account on a chosen Provider.
 */
type CreateSellerAccount<Provider> = (
  args: CreateSellerAccountArgs<Provider>
) => CreateSellerAccountPayload<Provider>

type CreateSellerAccountEndpoint = (
  args: CreateSellerAccountArgs & { userId?: number; email?: string }
) => CreateSellerAccountPayload
```

And the error seems to bump on this `index.d.ts` file as if the extra "." was considered as a path separator ( my two cents though ):
```terminal
api esbuild | MissingBeforeResolver: Must define a `beforeResolver()` in src/services/accountPaymentConfigurations/index/d
api esbuild |     at makeServices (/Workspace/Code/SportOffice/node_modules/@redwoodjs/api/dist/makeServices.js:32:13)
api esbuild |     at Object.<anonymous> (/Workspace/Code/SportOffice/api/dist/functions/graphql.js:3840:45)
```


### BUT
Prior to that it bumped on a file which was a level deeper in the service: `src/services/accountPaymentConfigurations/accountPaymentConfigurations/Stripe/createAccount.ts`

where I solved the issue by adding, in a burst of worst practice, this:
```
// Used when the environment variable REDWOOD_SECURE_SERVICES=1
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.skip()
}
```

I feel like the `beforeResolver` export applies to any file within `src/services`, whatever their level may be.

Hence my question, is this indeed what we should expect, such a deep level of coverage for `REDWOOD_SECURE_SERVICES` ?

**Comment by dthyresson** [comment]
Ah @dac09 is this a Typescript item we'll need to add in the generators and docs?

```
export const beforeResolver = (rules: BeforeResolverSpecType) 
```

And then @cannikin I imagine we need to document that *every* service will need to define a rule ... even if it is a 

```js
export const beforeResolver = (rules: BeforeResolverSpecType) => {
  rules.skip()
}
```

for those one wants to leave open?

> Hence my question, is this indeed what we should expect, such a deep level of coverage for REDWOOD_SECURE_SERVICES ?

Great questions. Thanks for testing and trying out this feature! Very helpful.

I think it's clear that the DX could be a bit better in docs and in upgrades.

For new apps, the generators will stub out ... but for people updating or authoring their own services, they'll need some better warning and guidance perhaps.

**Comment by noire-munich** [comment]
> Great questions. Thanks for testing and trying out this feature! Very helpful.

Always glad to!

> I think it's clear that the DX could be a bit better in docs and in upgrades.

Ah, doc could help on this indeed!

The underlying problem this poses to me is that I don't like having bloated files.
With such a coverage I could still separate each service endpoint in their own file and have their very own `beforeResolver` there, however I also expect to have modules in `src/services` that may not contain any endpoint method, but could be very raw files containing some utility methods useful exclusively in the scope of said service.

I'd feel like I should put utils methods in `src/lib` somewhere but I'm unsure about the best practice here: if those utils are exclusive to a service, shouldn't they be bundled in the service and not be concerned by `beforeResolver` ?

**Comment by cannikin** [comment]
Hmm, it does output error messages if there's no `beforeResolver` defined, but we have 3 different places that errors can show so it can be tough to find (api console output, browser console output, browser error page).

The release notes and [docs](https://redwoodjs.com/docs/services#skip) do tell you how to `skip()` and [state](https://redwoodjs.com/docs/services#securing-your-services) that you need to export a `beforeResolver` from your service...the docs don't specifically say "each and every service," but all of the code examples show it being used at the top of an individual service, not in some shared location, so it felt clear that you'd do the same in every service?

And even if you ignored all of that I feel like the error messages basically walk you though getting things working:

1. If you have no `beforeResolver` at all, you'll see a error message at startup when the GraphQL function is being built
2. If you haven't authorized a specific service (either by a call to `add` or `skip`) you'll get an error message telling you that it wasn't authorized and a code snippet telling you how to authorize it

You do *not* get a message telling you how to blanked `skip()` everything, but that's intentional—you really shouldn't do that. 

The error messages could include a link to the docs URL? What else would be helpful here?

**Comment by noire-munich** [comment]
@cannikin the message in itself is clear enough as to what causes the issue and how to solve it - at least, to me it's pretty clear, with the doc and with the message. This was the case while bumping into it already, but it raised some questions.

What is left unclear to me is:
- Why does the error message target an `index.d.ts` file? This is a type declaration file AFAIK, my instinct would consider it as not a service file at all, but as a file containing types and sometimes some constants, but no business logic. Is this a wrong assumption?

- Where should I put utility methods relevant exclusively in the scope of a service? Let's consider that code should not be used outside of the service, should be found in separate, maintainable files. With `beforeResolver` I cannot separate these methods because it will trigger this error message. What options do I have in this regard?

**Comment by cannikin** [comment]
How it actually works in the code:

1. Your graphql function imports all services from all files in `api/src/services`: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/src/functions/graphql.ts#L7
2. It gives them to the `makeServices()` function internal to Redwood: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/src/functions/graphql.ts#L14
3. `makeServices()` loops through that collection of services and returns a *new* collection where each service function is prepended by a call to the `spec.verify()` function (which is what adds up your rules in `beforeResolver` and determines whether or not they all pass): https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeServices.ts
4. If the service exports no `beforeResolver` then it'll throw the error you saw in your original post: https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeServices.ts

So, if you have an `index.d.ts` (or any file) that lives in the root of `api/src/services` this code will assume it contains services and therefore require it to export a `beforeResolver`. The way Redwood services work is that you have one named for a model in your DB...we really had no concept of an `index` file for those (likewise, the code that maps the GraphQL SDL to your service functions as resolvers wouldn't know what to do with an `index` file in the root of `api/src/services`). 

So, it seems like we should ignore the root of `api/src/services` completely so that you could put an `index.js` or `index.d.ts` there, as well as any files that contain code you want to import and share among your services. And it looks like that would be a pretty simple fix, just changing the glob pattern here, but I don't know what pattern says "include files in all subdirectories, but not in the root of this directory itself": https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/src/functions/graphql.ts#L7 It would probably be more backwards compatible to just do the exclusion in the loop in `makeServices()` itself: https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeServices.ts#L19

What do you think? Sound like it'll fix your problem?

**Comment by cannikin** [comment]
The structure of `services` after being imported in graphql.js ends up looking like:

```json
{
  addresses_addresses: {
    beforeResolver: [Function: beforeResolver],
    addresses: [Function: addresses],
    address: [Function: address],
    createAddress: [AsyncFunction: createAddress],
    deleteAddress: [AsyncFunction: deleteAddress],
    Address: { network: [Function: network], holdings: [Function: holdings] }
  },
  index: { 
    shared: [Function: shared] 
  },
  networks_networks: {
    beforeResolver: [Function: beforeResolver],
    networks: [Function: networks],
    network: [Function: network],
    createNetwork: [Function: createNetwork],
    Network: { addresses: [Function: addresses] }
  }
}
```

So it looks like we can just look for an `_` to make sure that the service is from an actual subdirectory and not the root!

**Comment by Tobbe** [comment]
> as well as any files that contain code you want to import and share among your services

Isn't that what we have the /src/lib folder for?

**Comment by cannikin** [comment]
I'm not a Typescript guy, so maybe this is not normal, but @noire-munich created a `index.d.ts` file in the root of `api/src/services` for his types. Just by virtue of the file existing, the `makeServices()` code was looking in there to see if it exported `beforeResolver()`.

Is that a common place to define types, or would those go in `api/src/lib` as well?

Either way, anything in the root of the services dir wouldn't be mapped to GraphQL resolvers so the code in `makeServices()` shouldn't be caring about files in there. So even if the solution to @noire-munich's problem is "put those in `api/src/lib` I still think this is a correct code change to make.

**Comment by noire-munich** [comment]
Thanks a lot for the elaborate answer @cannikin , it does shed some light on my questions ( some I've had for a long time actually! ).

I'm not much a typescript guy either ( learning to be though ).
What I saw however is that files corresponding to `**.d.ts` are Declaration files, when processed those files are stripped of any code that is not type declaration, which means they should not contain services per Typescript requirements, we should consider them as C/C++ headers ( for instance ).

The pattern in itself is quite permissive: in order for a header file to be automatically loaded by a file, both files:
- should share the same location
- should have the same name
- header file's name is appended by a `.d`

According to this and the fact that `MissingBeforeResolver` happens due to my `.d.ts` files I think that this line https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/src/functions/graphql.ts#L9 loads more files than it should. A Typescript project **should** be able to have `**.d.ts` files written anywhere, according to [doc](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) ( or more worrying [here](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#templates-for-modules) )

This being said, it could also be a matter of design choice. For the moment I'm experimenting with putting my `*.d.ts` files in `api/types/**.d.ts`, it's not too much troubles but I think we would benefit a lot from someone more experienced in Typescript, who could tell us if that's a pattern worth enforcing.


Back to the solution proposed and the question, 
> What do you think? Sound like it'll fix your problem?

Not sure, according to Typescript declaration file pattern and what we want to do with services, I think [this line](https://github.com/redwoodjs/redwood/blob/main/packages/api/src/makeServices.ts#L19) should ignore any and all `*.d.ts` files.

I'm left puzzled about code that is not a service in itself but part of services and that can be exclusive to a service scope - and in different files. That code should not be forced to implement `beforeResolver` because it would be impossible to use outside of services. What should we do with that? I'm not sure all of these fit into `api/src/lib`, if so directory structure of `lib` will to some extent mirror the one of `services`.

**Comment by cannikin** [comment]
Okay, we've got a new PR #3091 that will ignore `index.d.ts` files, and I added a section to the docs describing what to do about shared code in services: https://redwoodjs.com/docs/services#a-note-about-shared-code

**Comment by noire-munich** [comment]
Thanks a lot @cannikin 
Eventually we began moving a lot of code that was in /services to /lib, which gives us a cleaner structure and let us integrate `beforeResolver` for v1.
Side effect is that when we need to write tests for lib code, we also write scenarios manually - which is not a complaint though.

Also regarding types, since RW now generates graphql types we've been able to remove a lot of the custom types we wrote for our endpoints. Less code to maintain!
