### ISSUE TITLE
requireAuth role vs roles

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#2898]
Should it be `role` or `roles`?

The comment suggests `roles`, but the code uses `role`

```js
/**
 * ...
 * @param {string=} roles - An optional role or list of roles
 * @param {string[]=} roles - An optional list of roles
 * @returns {boolean} - If the currentUser is authenticated (and assigned one of the given roles)
 *
 * ...
 */
export const requireAuth = ({ role } = {}) => {
```

The [services docs](https://redwoodjs.com/docs/services.html#more-complex-scenarios) uses both 🙈 

![image](https://user-images.githubusercontent.com/30793/123515087-7d445200-d696-11eb-821b-0893457da512.png)
![image](https://user-images.githubusercontent.com/30793/123515115-88977d80-d696-11eb-8a7e-66386360502d.png)

The RBAC cookbook uses `roles`

![image](https://user-images.githubusercontent.com/30793/123515233-c7c5ce80-d696-11eb-8987-a2c6710d6745.png)

I was going to do a couple of other tweaks to this file and wanted to fix this along with the rest.
Personally I prefer `roles`.

**Comment by jtoar** [comment]
@Tobbe agree that `roles` makes more sense. @cannikin what do you think?

**Comment by jtoar** [comment]
^ don't mind me 😅

**Comment by cannikin** [comment]
Yeah let's go with `roles`.

I was going to go down a whole Ruby/Rails rant about allowing both and worrying about consolidating them into a single datatype behind the scenes, but I realized that `requireAuth` is a function that the user owns, not us, and it'd be kinda ugly to generate `api/src/lib/auth.js` with a bunch of code in there that turns one into the other. Nevermind!

I must have already been in that mode when writing these docs because a Ruby hashrocket slipped into the code example, whoops!  `{ roles => ['admin'] }`

![image](https://user-images.githubusercontent.com/300/123676465-d3c9a180-d7f8-11eb-8356-ea94639bf6db.png)

**Comment by dthyresson** [comment]
@Tobbe and @cannikin I am working on a draft for https://github.com/redwoodjs/redwood/pull/3006 and can make the change from `role `to `roles` but then if a single string role is given, then `roles: 'admin'`.

**Comment by Tobbe** [comment]
@dthyresson I added issues for the other small fixes I wanted to make to auth.ts as well (as I know you've seen).

Do you think you could fix them all in your PR?
#2898 (this one)
#3024 
#3025

**Comment by jtoar** [comment]
@dthyresson I brought this up with @mojombo and he agreed with Rob that it should be roles over role. Would it be more idiomatic for it to require an array, even if there's only one element in it?

**Comment by cannikin** [comment]
Because I'm sure everyone wants to know, this is what I'd do in my Ruby brain... 😃

Turn the argument into an array, and then flatten it. So, if the user passed a single string, it's turned into an array, and if they pass an array, it's still an array, and if they don't use the option at all, it's just an empty array. Saves you from a bunch of gross conditionals:

```javascript
const requireAuth({ roles }) => {
  const requiredRoles = [roles].flat().filter(r => r != null)  // removes null AND undefined
  // ...
}
```

Making this Typescript-compatible is probably ugly as hell, but makes for a nice developer experience IMHO because it doesn't matter what you pass, it just works (probably the opposite intention of using Typescript in the first place).

**Comment by dthyresson** [comment]
Agreed. I used to do that as well all the time - string to carry then `flatten().compact()`.dostuffsto also remove nulls.

But I think https://github.com/redwoodjs/redwood/pull/3107 does close out this issue.

**Comment by thedavidprice** [comment]
@Tobbe can you please confirm this is fixed? Close out if so!

**Comment by Tobbe** [comment]
Yup, looks good!
