### ISSUE TITLE
Does dbAuth support JSON Web Token?

### ISSUE THREAD

**Issue by zwl1619** [redwoodjs/redwood#3057]
> 
> Server-side sessions come with pros and cons. Some users prefer the tradeoffs/benefits provided by client-side sessions (e.g. JWT).
> 
> This also makes it easier to choose alternative data stores (such as those unsupported by Prisma) without having to modify the auth system.
> 
> 

Does dbAuth support JSON Web Token?

**Comment by brunoprietog** [comment]
Could refresh tokens also be considered? I'm thinking of a mobile app, where you keep a refresh token in the secure keychain storage, and update it from time to time. At the moment the only way I can think of would be that, connecting to the Graphql api.

**Comment by thedavidprice** [comment]
Looping in @cannikin

**Comment by cannikin** [comment]
> Does dbAuth support JSON Web Token?

See answer here (short answer is "no"): https://community.redwoodjs.com/t/dbauth-is-here-host-your-own-authentication-the-old-fashioned-way/2267/24?u=rob

**Comment by cannikin** [comment]
> Could refresh tokens also be considered?

One of the main reasons I created dbAuth was specifically because of issues I had with refresh tokens! I kept getting logged out of an app using one of our other auth providers (that shall remain nameless) and I was ready to drive my car off a cliff in frustration. I never want to be logged out of anything EVER!!!!  AAAGGGGHHHHH

![200](https://user-images.githubusercontent.com/300/126247906-e31e959a-1907-41a9-a137-51b85267210e.gif)

Whew, okay, had to get that off my chest.

That being said, `loginExpiresAt` effectively acts as a refresh token: each time you hit the api-side and it checks that your cookie is still valid, it sets the cookie header again. This resets the timer for the life of the cookie to whatever you set as that value. So if you wanted to simulate a 60 minute refresh token (dear god, why) just set `loginExpiresAt: 60 * 60` (the value is set in seconds).

But don't blame me when your users all delete their accounts because they kept getting logged out of your app. 😉
