### ISSUE TITLE
`yarn rw dev --fwd="--open=false"` no longer works

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#3116]

**Comment by thedavidprice** [comment]
This might have something to do with an API change to the upgraded webpack-dev-server v4. Passing --fwd might require updates.

**Comment by peterp** [comment]
I'm wondering if we can try to use the same approach as we do in `yarn rw prisma` and `yarn rw test`? So not having a `--fwd` flag, but rather just passing everything "non-standard" along.

**Comment by thedavidprice** [comment]
I think it's worth evaluating, but at first glance, two things intimidate me a bit:
- keeping ability to target web _or_ api
- `jest --help` has a _lot_ of options... hard to imagine all of them will work (but is this something we need to be concerned with)?

Definitely feels worth evaluating. Doesn't feel like the same as a the prisma CLI passthrough we do 'cause a lot more happening on this one to create more of a "test suite" that uses Jest.

Maybe there's just a better way to parse anything that's passed after `--forward`? My work on that option is kinda rough around all the edges.

**Comment by thedavidprice** [comment]
Again, the main issue at the moment is breaking changes in the soon-to-be release version of webpack-dev-server v4. We have to use the v4 release candidate due to bugs between v3 and webpack (go figure). However, the current dev server docs on the webpack site only reflect v3 — have to look through change logs and release notes at this time. And they're a bit messy.

**Comment by peterp** [comment]
Root issue is fixed now.
