### ISSUE TITLE
[v0.36 bug] Storybook is not picking up new Tailwind config

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3149]
# Reproduce
1. upgrade a project to canary
2. run `yarn rw setup tailwind`
3. use a pre-built TailwindUI snippet; copy+paste into new page (https://tailwindui.com)
4. compare differences between `yarn rw dev` and `yarn storybook`

## dev server screenshot
<img width="847" alt="Screen Shot 2021-07-30 at 9 48 27 AM" src="https://user-images.githubusercontent.com/2951/127686563-c8e7b6c0-6cf5-41c0-a0f6-af899c72d8ab.png">

## Storybook story screenshot
<img width="585" alt="Screen Shot 2021-07-30 at 9 48 56 AM" src="https://user-images.githubusercontent.com/2951/127686592-e6a5f98d-e3d5-4951-b304-5b3a7c140d5f.png">

## Tailwind snippet for testing
```
/* This example requires Tailwind CSS v2.0+ */
const people = [
  {
    name: 'Leslie Alexander',
    role: 'Co-Founder / CEO',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  // More people...
]

export default function Example() {
  return (
    <div className="bg-white">
      <div className="mx-auto py-12 px-4 max-w-7xl sm:px-6 lg:px-8 lg:py-24">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-3 lg:gap-8">
          <div className="space-y-5 sm:space-y-4">
            <h2 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Meet our leadership</h2>
            <p className="text-xl text-gray-500">
              Libero fames augue nisl porttitor nisi, quis. Id ac elit odio vitae elementum enim vitae ullamcorper
              suspendisse. Vivamus fringilla.
            </p>
          </div>
          <div className="lg:col-span-2">
            <ul className="space-y-12 sm:grid sm:grid-cols-2 sm:gap-12 sm:space-y-0 lg:gap-x-8">
              {people.map((person) => (
                <li key={person.name}>
                  <div className="flex items-center space-x-4 lg:space-x-6">
                    <img className="w-16 h-16 rounded-full lg:w-20 lg:h-20" src={person.imageUrl} alt="" />
                    <div className="font-medium text-lg leading-6 space-y-1">
                      <h3>{person.name}</h3>
                      <p className="text-indigo-600">{person.role}</p>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
```

**Comment by jtoar** [comment]
The reason for this is that the new setup tailwind command adds the tailwind css import to App.js, not to index.css (the old setup tailwind command added the tailwind directives to index.css): 

https://github.com/redwoodjs/redwood/blob/d16ba9c4a995da18d53984f7139b401716b6f26f/packages/cli/src/commands/setup/tailwind/tailwind.js#L33-L36

But storybook only looks at index.css for what to include, so it misses tailwind entirely:

https://github.com/redwoodjs/redwood/blob/d16ba9c4a995da18d53984f7139b401716b6f26f/packages/testing/config/storybook/main.js#L42-L50

It seems like we should probably revert the behavior of the setup command to add the tailwind directives to index.css. I'm not sure what the pros/cons are, or if there even are any—there's several ways to include tailwind in your app. I went with the `import tailwindcss/tailwind.css` in App.js because it was unobtrusive, but that totally outweighs things not working in storybook. And we don't want to set up a custom storybook.main.js just so the new tailwind import style works with storybook; it'd be cleaner to just handle things in index.css

**Comment by jtoar** [comment]
Here's the relevant section of the tailwind docs for completeness: https://tailwindcss.com/docs/installation#include-tailwind-in-your-css. Tailwind just isn't being included in storybook's css.
