### ISSUE TITLE
Integration with OpenFaas?

### ISSUE THREAD

**Issue by khusseini** [redwoodjs/redwood#3179]
Hello there,

I am currently building an Faas framework, however the project I am working on focuses on cluster operations, rather than on the application side. Simply put, the framework is a bunch of ansible playbooks which deploy common components, such as an faas provider, identity service, auth and authz.
Here is the first prototype: https://gitlab.com/faasaf/faasaf
It also provides an interface to the application developers to manage application operations (make, ansible etc.)
Here is a sample implementation with react of the prototype: https://gitlab.com/faasaf/petshop
Installed is also an implementation of a graphql-gateway, which is a graphql server that can be configured with yaml to proxy queries an mutation to other http backends and an operator which deploys graphq-gateways by reading openfaas functions annotations.

Just now I stumbled upon redwood/redwoodjs (last night i found redwood/redwood) this project and first thought this could easily replace mine, however I realized then there a big differences in the focus of the projects and might be able to complement each other perfectly.

I could answer my question myself by just looking at redwoodjs' code, however maybe someone could answer me this, is redwoodjs built in a way that the actual function backend can be switched out?

**Comment by ajcwebdev** [comment]
Welcome to the Redwood community @khusseini! 👋

It definitely sounds like there are a lot of interesting compatibilities that could be explored between the intersection of Redwood and the work you have been doing. In regards to this question:

> Is redwoodjs built in a way that the actual function backend can be switched out?

In the past Redwood was architected specifically for AWS Lambda, but with the introduction of Envelop we are moving to more of a plugin architecture that can support multiple different function backends.

I do not currently see Open FaaS listed on their [supported integrations](https://www.envelop.dev/docs/integrations) at this time, however it is possible that @dotansimha and the Guild have some knowledge about the feasibility of adding Open FaaS. I'll tag @alexellis as well since he's the keeper of the Open FaaS project as far as I know.

**Comment by khusseini** [comment]
Thank you @ajcwebdev for the kind reply.
I never heard about Envelop before. This looks also very interesting.
