### ISSUE TITLE
GraphQL Playground URL isn't correct in development

### ISSUE THREAD

**Issue by cjdenio** [redwoodjs/redwood#3208]
Hello! According to [the documentation](https://learn.redwoodjs.com/docs/tutorial/saving-data#graphql-playground), the GraphQL Playground should be available at `/graphql`, but it's actually at `.redwood/functions/graphql` by default (at least in development).

I've also noticed a related discrepancy in the docs where [this page](https://redwoodjs.com/cookbook/custom-function) and [this page](https://redwoodjs.com/docs/serverless-functions.html) make different claims about the default location of serverless functions (the first one is correct).

**Comment by dthyresson** [comment]
Hi @cjdenio, just to clarify the reproducible steps -- how are you starting up your dev server?

I ask because:

Via `yarn rw dev`

![image](https://user-images.githubusercontent.com/1051633/128275562-f9adaa96-adbd-48f2-ba69-e1be55887d29.png)


Via `yarn rw api serve`

(No GraphQL playground enabled)

![image](https://user-images.githubusercontent.com/1051633/128275422-0b0f0e03-797d-4dcb-8d27-1df66c704efa.png)


Via `yarn rw serve`

Also, playground isn't enabled but the function lives in my app example at `/.netlify/functions/graphql` because my `redwood.toml` defines that:

```
 [web]
  port = 8910
  apiProxyPath = "/.netlify/functions"
```

![image](https://user-images.githubusercontent.com/1051633/128275666-9ae247de-8beb-4085-bcf8-874b553a4da5.png)

The documentation is likely written from the perspective of `yarn rw dev` which is the most common way to launch the dev server.

So, would you recommend that the documentation be updated to include:

* if using `yarn rw serve`
* functions (and graphql) are available at the `apiProxyPath` defined in your `redwood.toml`

?

If that makes sense, let's create an issue in the https://github.com/redwoodjs/redwoodjs.com/issues repo.

Thanks.

**Comment by cjdenio** [comment]
Thanks for the quick response! I can reproduce this issue by generating a project with `yarn create redwood-app ./redwood-test` and running `yarn rw dev`. (in a non-bare project, it shows a 404 instead of the welcome page) Not 100% sure whether this is a documentation issue or a bug, but it seems like a mixture of both.

<img width="942" alt="Screen Shot 2021-08-04 at 9 39 16 PM" src="https://user-images.githubusercontent.com/34525547/128277514-8c645fc2-3868-42c5-a487-c9993b9642e3.png">

**Comment by Tobbe** [comment]
@cjdenio Notice the port. It's :8910 for the web stuff, and :8911 for api. So you need to use :8911 to access /graphql

**Comment by cjdenio** [comment]
My bad, thanks for clarifying!
