### ISSUE TITLE
[Internal] Refactor and cleanup webpack configs

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3212]
The webpack configs in redwoodjs/core (used in the web side) need a bit of TLC.

Tasks:

- [ ] Remove storybook specific config from shared webpack settings https://github.com/redwoodjs/redwood/blob/ec04a2bfe455dd6def37c5a15160fcb6a75b9595/packages/core/config/webpack.common.js#L143
- [ ] Restructure webpack configs to be clearer how they are shared

**Suggested structure**
- core/config/webpack.shared.ts 
  This houses all the plugins/presets/code that is shared between dev and prod side
- core/config/dev
  - Houses all the webpack config related to "dev time" settings i.e. dev + storybook
  - Also includes additional settings like perf and stats
- core/config/prod
   Only has config that is used for the production bundle

**Comment by thedavidprice** [comment]
I'd really like to see this happen, I'm just not sure if we should poke the proverbial bear before v1. TBD

Other aspects that make our Webpack hard to manage and comprehend:
- It is very challenging to understand which config/settings are being applied within a given context due to the use of conditionals. Honestly, I'd rather have more distinct files (with helpful names) than have to parse through conditionals.
- It's also challenging to manage dependencies that are Webpack specific. E.g. offhand, do you know if `babel-loader` is for babel or webpack (or both)? This was a particular pain point upgrading to Webpack v5 and having to find all the dependecies and determine which specific version(s) of a dependency were v5 compatible. For this reason, I've wondered if Webpack should be it's own Redwood package, e.g. `@redwoodjs/webpack` 

I actually think Webpack is a great tool. In order to make it more long-term maintainable, I just think we need to enforce better conventions and even constrain how/where we use it.
