### ISSUE TITLE
Cannot find module '@babel/runtime-corejs3/core-js/object/define-property' 

### ISSUE THREAD

**Issue by leoalbin** [redwoodjs/redwood#3216]
Hey guys, we are getting an error after deployment: 

`Cannot find module '@babel/runtime-corejs3/core-js/object/define-property' Require stack: - /var/task/src/node_modules/@redwoodjs/api/dist/index.js - /var/task/src/api/dist/functions/graphql.js - /var/task/s_graphQL.js - /var/runtime/UserFunction.js - /var/runtime/index.js`

Some hints:
- It is not happening in the local environment just after deploying to AWS.  
- It is fixed if we downgrade to rw version 0.26.0
- It seems the core-js module is not being included in /api/dist/node_modules
- We have a custom deployment flow using zip-it-and-ship-it and serverless.yml. We have a serverless.yml inside /api and after running a zip-it-and-ship-it we include the artifact like this:

```
graphQL:
    handler: src/api/dist/functions/graphql.handler
    package:
      artifact: zipball/graphql.zip
    ...etc
```

Any insight would be great, thanks a lot! :) 

Leo

our package.json root:

```
{
  "private": true,
  "workspaces": {
    "packages": [
      "api",
      "web",
      "integrations/*"
    ]
  },
  "devDependencies": {
    "@redwoodjs/core": "^0.35.2",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "git-last-commit": "^1.0.0",
    "minimist": "^1.2.5",
    "serverless-prune-plugin": "^1.4.3"
  },
  "eslintConfig": {
    "extends": "@redwoodjs/eslint-config"
  },
  "engines": {
    "node": "14.x",
    "yarn": ">=1.15"
  },
  "scripts": {
    "wmx-push": "node ./scripts/push_and_deploy",
    "web-server": "cd web && yarn run webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js",
    "api-server": "cd api && yarn run dev-server",
    "build-web-sls": "yarn rw build web && node ./scripts/createIndexHtml.js"
  }
}
```

our package.json API:
```

{
  "name": "api",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@redwoodjs/api": "^0.35.2",
    "@sentry/node": "^5.20.0",
    "activecampaign": "^1.2.5",
    "aws-sdk": "^2.725.0",
    "cuid": "^2.1.8",
    "dayjs": "^1.10.1",
    "exchange-rates-api": "^1.0.2",
    "fetch-retry": "^4.0.0",
    "js-yaml": "^4.0.0",
    "lodash.flatten": "^4.4.0",
    "lodash.uniq": "^4.5.0",
    "moment": "^2.26.0",
    "node-fetch": "^2.6.0",
    "qs": "^6.9.4",
    "serverless": "^2.11.0",
    "serverless-layers": "^2.2.4",
    "serverless-webpack": "^5.3.3",
    "stripe": "^8.64.0",
    "webpack-node-externals": "^2.5.0",
    "yargs": "^15.4.1",
    "@babel/runtime": "^7.14.8",
    "@babel/runtime-corejs3": "^7.14.9"
  },
  "devDependencies": {
    "@netlify/zip-it-and-ship-it": "^2.1.3",
    "chalk": "^4.1.0",
    "serverless-dotenv-plugin": "^3.0.0",
    "serverless-layers": "^2.2.4",
    "serverless-plugin-ifelse": "^1.0.5",
    "serverless-prune-plugin": "^1.4.3"
  }
}
```

**Comment by ajcwebdev** [comment]
Do you have `esbuild` set to `true` in your `redwood.toml`? If so try changing it to `false` and redeploying.

**Comment by ajcwebdev** [comment]
This is the third time I've seen this bug crop up and it's making me feel like Ahab and this is my white whale. Here's some links and notes so the future generations of programmers who are also trying to fix opaque bugs in Babel (along with probably myself a month from now) might find some breadcrumbs.

## What's a `babel/runtime` anyway?

[`@babel/runtime`](https://babeljs.io/docs/en/babel-runtime) is a library that contains Babel modular runtime helpers and a version of `regenerator-runtime`. Sometimes Babel may inject some code in the output that is the same across files, and thus can be potentially re-used. This is meant to be used as a runtime `dependency` along with the Babel plugin [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime) which will replace the reference to the function to the `@babel/runtime` version.

## What's `core-js`?

[`core-js`](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md) is a polyfill of the JavaScript standard library that is tightly integrated with `babel` and (allegedly) allows for many optimizations of `core-js` imports. It supports:
* The latest ECMAScript standard.
* ECMAScript standard library proposals.
* Some WHATWG / W3C standards (cross-platform or closely related ECMAScript).

## What's the deal with `core-js` vs `core-js@3`?

In Babel version [7.4.0](https://babeljs.io/blog/2019/03/19/7.4.0), both `@babel/preset-env` and `@babel/transform-runtime` added support for `core-js@3`. Instance methods such as `"foobar".includes("foo")` will only work with `core-js@3` . If you need to polyfill them, you can directly import `"core-js"` or use `@babel/preset-env` 's `useBuiltIns` option.

## What's the deal with `@babel/plugin-transform-runtime`?

Babel uses very small helpers for common functions such as `_extend`. By default this will be added to every file that requires it. With `@babel/plugin-transform-runtime`, all of the helpers will reference the module `@babel/runtime` to avoid duplication across your compiled output. The runtime will be compiled into your build.

If you directly import [`core-js`](https://github.com/zloirock/core-js) or [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) and the built-ins it provides such as `Promise`, `Set` and `Map`, those will pollute the global scope. While this might be ok for an app or a command line tool, it becomes a problem if your code is a library which you intend to publish for others to use or if you can't exactly control the environment in which your code will run. The transformer will alias these built-ins to `core-js` so you can use them without having to require the polyfill.

By default, `@babel/plugin-transform-runtime` does not inject polyfills for proposals and use entry points which do not include them but, exactly as you can do in `@babel/preset-env` , you can set the `proposals` flag to enable them: `corejs: { version: 3, proposals: true }`.

## Is `@babel/plugin-transform-runtime` the same as `@babel/transform-runtime`?

Great question!!! No idea, but apparently the [`transform-runtime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime#technical-details) transformer plugin does three things:

* Automatically requires `@babel/runtime/regenerator` when you use generators/async functions (toggleable with the `regenerator` option).
* Can use `core-js` for helpers if necessary instead of assuming it will be polyfilled by the user (toggleable with the `corejs` option)
* Automatically removes the inline Babel helpers and uses the module `@babel/runtime/helpers` instead (toggleable with the `helpers` option).

## Babel 8 changes?

In Babel [v8](https://babeljs.io/docs/en/roadmap#move-babelpreset-env-into-babelcore), `@babel/preset-env` will be moved directly into `@babel/core`. This looks like a [huge headache](https://babeljs.io/docs/en/roadmap#continue-developing-the-babel-polyfills-project) with multiple different potential directions that the team could go in 2021. Thankfully this shouldn't have anything to do with this bug since we're on 7, but this stuff could get potentially much worse in v8.

## This seems pretty confusing, how is the entire JavaScript ecosystem built on this stuff?

I know right? Sure would be weird if this was being downloaded [7 million times a week](https://www.npmjs.com/package/@babel/runtime-corejs3).

**Comment by ajcwebdev** [comment]
## Reproduction on Netlify

[GitHub Repo](https://github.com/ajcwebdev/rw-broken-deploy)
[Netlify Logs](https://app.netlify.com/sites/rw-broken-deploy/deploys/610e24ffb5f0760007c3d3a1)
[Broken GraphQL endpoint](https://rw-broken-deploy.netlify.app/.netlify/functions/graphql)

You can test the app and see it working locally with the following:

```bash
git clone https://github.com/ajcwebdev/rw-broken-deploy.git
cd rw-broken-deploy
yarn
yarn rw dev
```

Open `localhost:8911/graphql` and run the following query

```graphql
query REDWOOD_VERSION {
  redwood {
    version
  }
}
```

You'll get back

```json
{
  "data": {
    "redwood": {
      "version": "0.35.2"
    }
  }
}
```

**Comment by leoalbin** [comment]
Hey @ajcwebdev , thanks for your insights were super helpful to find a solution. 

We finally solved it by installing @babel/plugin-transform-runtime as dev dependencies and @babel/runtime as dependencies on the API side. Not sure if it is a default we overwrite in the past or if it was a manual code change we missed in some upgrade. 

More details here --> https://babeljs.io/docs/en/babel-plugin-transform-runtime#installation

**Comment by ajcwebdev** [comment]
The whale is slain.

![brNZ509](https://user-images.githubusercontent.com/12433465/128605973-77d8be38-19c9-4285-b55c-8a8393b34799.jpeg)

Now we just need to figure out why we're also getting this error when turning on `esbuild`...

**Comment by ajcwebdev** [comment]
@peterp @thedavidprice @dthyresson @dac09 despite the work arounds we are finding for this bug this is a pretty huge gotcha, especially for people who don't know how to futz around with the `redwood.toml` or Babel plugins. Should we:

1. Open an issue on Babel's and/or Esbuild's repo?
2. Document the work arounds?
3. Try to fix it by hacking around inside the Redwood internals?

**Comment by dthyresson** [comment]
> Do you have `esbuild` set to `true` in your `redwood.toml`? If so try changing it to `false` and redeploying.

I experienced this issue with an app last week with Netlify, and the solution (as noted) was to disable `esbuild` in the `redwood.toml`.

What might be happening is on build, uses rebuild and then when Netlify builds its functions via https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/ it over "shakes" (if that's a term) and dependencies get out fo whack.

That was my workaround, but I should let Netlify know about this issue.

**Comment by dthyresson** [comment]
> 2\. Document the work arounds?

Definitely document.

Probably here for Netlify deploy, with a callout: https://redwoodjs.com/docs/deploy#netlify-deploy

And here for rebuild tool config: https://redwoodjs.com/docs/app-configuration-redwood-toml.html#esbuild

**Comment by dthyresson** [comment]
Or I wonder @dac09 or @thedavidprice if this config setting could be automatically set to false when deploying to Netlify. 

If `netlify.toml` exists?

Or maybe check if this envier exists?

https://docs.netlify.com/configure-builds/environment-variables/#build-metadata

> NETLIFY: Always true. Can be used to check if the build is running on Netlify.

And if so, then disable esbuild somehow from 

https://github.com/redwoodjs/redwood/blob/7e663d1cd9790dd9457961f1b67172a0fefda2e2/packages/internal/src/config.ts#L96

when deploy/building on Netlify?

**Comment by leoalbin** [comment]
In our case was failing with both esbuild = false and true. The only solution was to add dependencies to the API side.

**Comment by dthyresson** [comment]
> In our case was failing with both esbuild = false and true. The only solution was to add dependencies to the API side.

Oh interesting. I'll update that documentation issue with this info. Thanks!
