### ISSUE TITLE
[v0.37] Full deprecation of .babelrc.js

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3245]
_Continues work from #3231_

Current implementation that shipped with v0.36:
- only applicable to API, i.e. `api/.babelrc.js`
- deprecates but does not throw or warn if file exists in an app

From Peter P:
> I want this to be a breaking change if you have custom babel transformations. The reason I want it to be a breaking change is because I want to discourage people from adding their own babel transformations because I would like to move our own transformations to a faster toolchain and would not like babel to make that process difficult.

# Next Steps
- Full deprecation: required to delete api/.babelrc.js and/or to convert it to api/babel.config.js and remove the "extends" part.
- Add tests:
    - Test that <side>/.babelrc.js is not imported
    - Test that <side>/babel.config.json can be imported if it's available.
- Resolve conversation here about rw alias plugin and supporting custom aliases: https://github.com/redwoodjs/redwood/pull/3231/files#r687869806
- TBD: also include Web `web/.babelrc.js`?

**Comment by peterp** [comment]
We use babel in 3 different scenarios:

1. Pre-build: we transpile the magic out of the code, and turn it into ordinary JS code.
2. Type generation/ Babel plugins: we "read" the user's source code to determine what's inside some file: _Is it a Cell? Is it a directory-named-module? Does it have exports?_
3. Real-time run-time transpilation of files: We convert your TypeScript code into beautiful runnable JavaScript code in memory (in the same node process). We use this for pre-rendering, "console", and data-migrate.

Each one of these function calls needs to use ✨_THE SAME CONFIGURATION_✨ because if we're do 1 thing in pre-build, and it doesn't work in real-time people are going to loose their minds. (If we don't loose them first.)

So... I propose that we come up with unit tests for those babel entry points above to confirm that we're not modifying their configuration in ways that make them inconsistent with each other.

**Comment by thedavidprice** [comment]
@dac09 nudge on this one, high priority for v0.39
