### ISSUE TITLE
I want to alias ‘yarn rw’ so badly 

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#328]
Hypothetically, if our installation script prompted users:
“Would you like to alias command line ‘yarn rw’ to ‘r’? y/n”

Would that really be so bad?

Talk me in/out of this ‘cause I’m feeling motivated.

😉 

## The Rules
1. we only use `yarn`
2. we only install package locally via [`package.json` bin executable](https://docs.npmjs.com/files/package.json#bin)
3. we do **not** make system settings changes without users' awareness and action (preferrably require a user to decide + act through simple, transparent step)
4. our goal is DX; we want the effect to be a net positive happiness increase

**Comment by mojombo** [comment]
Just `r` is pretty ambitious, but I could certainly be convinced that aliasing to `rw` would be suitable. Do you know of a reliable way to do this across shells and OSes?

**Comment by thedavidprice** [comment]
I do not, but I'm willing to do some research! To that point might end up being too complicated to cover all cases. Maybe inspect for a limited number of shells/OS's and then gracefully decline if current "not recognized".

We could recommend alias, e.g. "rw", but then let the user input their choice.

The easiest way forward --> within "Next Steps" message after successful CRA installation, make a suggestion for users to manually set up themselves.

**Comment by arjunv27** [comment]
`yarn workspace` commands should be aliased as well.

**Comment by weaversam8** [comment]
`npm` lets users install and invoke binaries supplied by local packages by name, by installing them in `node_modules/.bin`... does `yarn` not also do this?

If it does, we could just put a `rw.sh` and `rw.bat` or something in `node_modules/.bin` that simply invokes `yarn rw`.

**Comment by peterp** [comment]
@weaversam8 This is exactly what yarn does. They're talking about invoking the commands with having to prefix it with `yarn`: https://classic.yarnpkg.com/blog/2017/06/19/adding-command-line-aliases-for-yarn/

**Comment by weaversam8** [comment]
No sorry, I meant that NPM already has the ability to add commands without prefixing it with Yarn. When you install `gatsby-cli` with NPM globally, it'll enable the ability for you to run `gatsby new` instead of `npm r gatsby new`.

I'm pretty sure this should also work if you install `gatsby-cli` in a local project, you can execute `gatsby new` in that project folder.

This functionality is provided by [the `bin` key in `package.json`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/package.json#L6-L8), which is documented [here](https://docs.npmjs.com/files/package.json#bin).

**Comment by peterp** [comment]
Thanks for the clarification @weaversam8.

A bit more about how this works. Globally installed packages are added to a place where they're available in your path:
```bash
echo $PATH
/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

which gatsby
/usr/local/bin/gatsby
```

We do this for our CLI over here:
https://github.com/redwoodjs/redwood/blob/583ca4060a37202b642180a7f13f31b2ed514e58/packages/cli/package.json#L6-L9

But, we prefer not to have people install our CLI globally since we update the CLI fairly frequently and would like to pin it to the redwood projects where you're invoking it from. We imagine you might have several Redwood projects with different versions.

For people that hate typing `yarn rw` we could suggest two things:
1. Add an alias: `alias rw="yarn rw"`
2. We could ask people to install a different package globally (`@redwoodjs/cli-global-alias`) that installed `rw` and would attempt to call `yarn rw` from the current working directory.

**Comment by weaversam8** [comment]
> We could ask people to install a different package globally (`@redwoodjs/cli-global-alias`) that installed `rw` and would attempt to call `yarn rw` from the current working directory.

Is there any reason we couldn't roll this into the normal CLI package anyways? That way if someone installs it globally, it'll search first for a local version when executed?

**Comment by thedavidprice** [comment]
Thanks for chiming in here with discussion and adding clarity + specifics. 

I did edit the original comment by adding “The Rules” section —> there are important design choices that require the `yarn rw …` (which, imho, really isn’t that bad). This discussion isn’t about rolling back those decisions. It’s just about whether or not there’s value in giving the users an option to alias during the installation process (and/or just providing instructions about _how_ to alias themselves as a next step).

**Comment by thedavidprice** [comment]
@arjunv27 If I understand you correctly, I’m not sure this will be possible. Could you give me an example? That will help me make sure I understand and I could also better explain my thinking.

**Comment by arjunv27** [comment]
@thedavidprice 
Sure: 
`yarn workspace add web netlify-identity-widget` -> 
`rw add web netlify-identity-widget`

**Comment by thedavidprice** [comment]
@arjunv27 Ah, thanks for the example. I can see how/why people will alias for this case. But for me it’s not a commmon command I need so wasn’t thinking the same way. More importantly, from a Redwood installation perspective, we won’t address this because it’s specific to using yarn / yarn tooling.

But, again, not that it isn’t something you and many others many very well want to do!

**Comment by thedavidprice** [comment]
To research:
https://github.com/magic/bash-alias

Wondering what they’re doing under the hood.

**Comment by pickleat** [comment]
Not sure if this will add much to the discussion, but `alias rw=`yarn rw` in zsh is working great so far here.

**Comment by thedavidprice** [comment]
@pickleat Nice! I think the trick on this would be to figure out how to support the top 3-4 shells across Linux/Mac and Windows: bash, zsh, PowerShell, etc. During installation could check shell environment and, if support, prompt user if they want to make life much radder.  

Totally doable. And I think totally worth it! (Just need 36 hours in a given day to get it done... )

Anyway, thanks for chiming in 😁

**Comment by peterp** [comment]
@thedavidprice Are we OK to close this one off now?

**Comment by thedavidprice** [comment]
This can be accomplished via #3094
