### ISSUE TITLE
[error] deploy aws serverless : @netlify/zip-it-and-ship-it is not installed

### ISSUE THREAD

**Issue by coleea** [redwoodjs/redwood#3284]
```
my system

CPU : i7-2600
OS : ubuntu 20
```

hello.
I'm trying to deploy by referring to the document ' https://redwoodjs.com/docs/deploy '.
when I type 'yarn rw deploy aws serverless --side api'  , I encountered the error

```
lkb@lkb-System-Product-Name:~/project/redwood-blog-2$ yarn rw deploy aws serverless --side api
yarn run v1.22.5
$ /home/lkb/project/redwood-blog-2/node_modules/.bin/rw deploy aws serverless --side api
  ❯ Checking pre-requisites
    ✔ Checking if Serverless framework is installed...
    ✖ Checking if @netlify/zip-it-and-ship-it is installed...
      → Looks like @netlify/zip-it-and-ship-it is not installed. Either run `yar
…
    Building and Packaging...
Command failed with exit code 1: yarn zip-it-and-ship-it --version
error Command "zip-it-and-ship-it" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Looks like @netlify/zip-it-and-ship-it is not installed. Either run `yarn rw setup aws-serverless` or add it seperately as a dev dependency in the api workspace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

so I run 
```
yarn rw setup aws-serverless
```
the result is 
```
lkb@lkb-System-Product-Name:~/project/redwood-blog-2$ yarn rw setup aws-serverless
yarn run v1.22.5
$ /home/lkb/project/redwood-blog-2/node_modules/.bin/rw setup aws-serverless
Done in 2.02s.
```

after setup, I restart 
```
yarn rw deploy aws serverless --side api
```
but error is the same. I think @netlify/zip-it-and-ship-it is not installed.
about this, Is there anyting I can try or Can I contribute something about it ?
thank you.

Also, It is my first github issue. so maybe I mistake something. please understand.

**Comment by coleea** [comment]
thank you  @thedavidprice .  I did what you are mentioned. now It works correctly.  I think It is important issue, so official docs have to be updated. Is there way that I can update this document ?

**Comment by thedavidprice** [comment]
@coleea Absolutely and that would be a welcome, huge help! 

Here's the doc file on the `redwoodjs.com` repo:
https://github.com/redwoodjs/redwoodjs.com/blob/main/docs/deploy.md

Just open a PR with the changes and feel free to loop me in. I'll make sure to review and help get it merged.

**Comment by coleea** [comment]
while write a document, I have some question.
1. it seems to be deployed to s3(app-dev-serverlessdeploymentbucket) and lambda (app-dev-graphql), but not connected to cloudfront.
2. if so, Couldn't I access to this site via any url?

**Comment by thedavidprice** [comment]
Hi @coleea Sorry for the delay here! I should be able to provide much more timely replies now.

Also looping in @hemildesai who authored the original PR adding this deployment!

For reference, I have created a GitHub Gist with the code for the the `serverless.yml` file generated with `yarn redwood setup deploy aws-serverless`:
- [Gist for serverless.yml](https://gist.github.com/thedavidprice/ac67656b1a3e2b32f31799cd4fb7cbec#file-serverless-yml-L40)

## Your questions
> it seems to be deployed to s3(app-dev-serverlessdeploymentbucket) and lambda (app-dev-graphql), but not connected to cloudfront.

^^ This is correct about the current contents of serverless.yml. The serverless framework will deploy the files to the S3 bucket. And then Cloudformation will run and deploy the files to AWS Lambdas

> if so, Couldn't I access to this site via any URL?

^^ I'm not sure what you are referring to here ("this site")? After you run the Redwood setup command, you still need to setup the AWS CLI and credentials — required to deploy. So access is secured. Here's the message after you run the command:

> You are ready to deploy to AWS using the Serverless framework!                                                                                         │
>     │   To configure AWS credentials, see https://www.serverless.com/framework/docs/providers/aws/guide/credentials/                                        │
>     │   For a more detailed way to configure the credentials using the AWS CLI, see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html│
>     │   To deploy, see https://redwoodjs.com/docs/deploy#aws_serverless  

The functions will have an IP of some sort (I'm unfamiliar). By default, functions are public and not secure (however, Redwood provides ways for functions to be secure by default, including the GraphQL API).

## Next Steps
After looking at the generated code and the docs for Serverless, there's a lot of work to do here!

### The current YML file needs updating
Take a look at my comments on the Gist I created. There are several things that need to be addressed relating to Prisma and Functions.
- [Comment with topics](https://gist.github.com/thedavidprice/ac67656b1a3e2b32f31799cd4fb7cbec#gistcomment-3897679)

### Adding Cloudfront
Here are the docs for Cloudfront configuration, which will need to be added to the `serverless.yml`:
- https://www.serverless.com/framework/docs/providers/aws/events/cloudfront

Additionally, this will need to be included in the deployment steps:
- yarn `yarn rw build` (includes Web/)
- package up the `web/dist` files (probably zip or tarball)
- deploy packaged file to Cloudfront

I didn't read through the Cache policies — effectively the deployed assets should stay live until the next deployment, at which time all previous should be invalidated.

### Updating `yarn rw deploy ...`
Lastly, the Redwood deploy command will need to be updated to include the web/dist files on Cloudfront. That command lives here:
https://github.com/redwoodjs/redwood/blob/f359de4059f6b78226e332424447b637fba163e0/packages/cli/src/commands/deploy/aws.js

----

@coleea there is a lot of complexity here. If you are interested and available in working on this, your help would be tremendous! But there's no pressure for you to do it.

Documentation is a critical first step (which is why I outlined the steps here) and will allow others to help. Ultimately, we'd like to have all this working via updated code.

**Comment by coleea** [comment]
Thanks a lot.  I think the first thing I should do is 

- package up the web/dist files (probably zip or tarball)
- deploy packaged file to Cloudfront

if these can be done, everything works fine. In order to do this, knowledge about how serverless framework works is needed. In my search, Serverless API Cloudfront (https://www.serverless.com/plugins/serverless-api-cloudfront) fits this work. In fact, I have tried some stuff for 3 days. now I'm struggling with some error about this. If my work could be success, I will  write some progress here about this

**Comment by thedavidprice** [comment]
Moving this over to #3686
