### ISSUE TITLE
Consider fastify for api server

### ISSUE THREAD

**Issue by kibertoad** [redwoodjs/redwood#3374]
I would like to make a case for switching to fastify from express:

1. Express is pretty much on lifesupport now. Last release was two years ago.
2. Fastify is [4 times faster](https://www.fastify.io/benchmarks/);
3. Fastify has proper promise support out-of-the-box;
4. Fastify has powerful plugin system and flexible lifecycle hooks.

Considering that there is very little server code in redwood, migration should be pretty straightforward.

**Comment by peterp** [comment]
Hey @kibertoad,

Thanks for the suggestion! I would be very interested in doing this. We originally started building RedwoodJS with the idea that it was "for the JAMStack" which, like you've mentioned, meant we hid the server code.

But, we've expanded our footprint a bit and I think most people, in production, run RedwoodJS on a serverfull environment. So I would like to lead part of this discussion into the realm where we design a way to expose the "server code" to the developer so that they feel like they're in control.

This what I do on my application to control the server stack:

```ts
// api/src/server.ts

import express from 'express'

import { requestHandler } from '@redwoodjs/api-server/dist/requestHandlers/awsLambda'
import { handler as graphQLHandler } from './functions/graphql'

const app = express()

app.all(
  '/graphql',
  text({
    type: ['text/*', 'application/json', 'multipart/form-data'],
    limit: process.env.BODY_PARSER_LIMIT,
  }),
  raw({
    type: '*/*',
    limit: process.env.BODY_PARSER_LIMIT,
  }),
  (req, res) => requestHandler(req, res, graphQLHandler)
)

const port = process.env.RWJS_API_PORT
app.listen(port, () => {
  console.log(`http://localhost:${port}`)
  process.emit('message', 'snaplet.dev started')
})
```

The main part here is translating the "aws request and response" into something that express can understand. 

So, if I had to break this down into actionable tasks we can try the following:

Phase 1: Replace Express for Fastify
1. Create a aws-request-response handler for fastify.
2. Replace the `api-server` with fastify instead of express.

---

Phase 2: Give user's more control.
1. Allow user to control entire stack: Make `yarn rw serve` look for `api/src/server.ts` and use that instead of `api-server`
2. Figure out a way to make `yarn rw dev api` use `api/src/server.ts` instead of `api-server`.

Phase 2 Discussion points:
1. Should we officially sanction a way for people to "escape" the api-server? @dac09

**Comment by kibertoad** [comment]
Do you mean something like https://github.com/fastify/aws-lambda-fastify?

**Comment by peterp** [comment]
I think this may do the opposite:

It translates an aws-request -> fastify-request
and a fastify-response -> aws-response.

What we need to do is the opposite: 
fastify-request -> aws-request, 
and aws-response -> fastify-response.

Does that make sense?

**Comment by kibertoad** [comment]
@peterp Gotcha. So basically an equivalent of `https://github.com/redwoodjs/redwood/blob/main/packages/api-server/src/requestHandlers/awsLambda.ts` for fastify.

**Comment by peterp** [comment]
Yup!

**Comment by thedavidprice** [comment]
Hi @kibertoad As a part of our roadmap to Redwood v1, we would like to make the transition from Express to Fastify. However, given the current list of tasks assigned to core team maintainers, we're not sure if this is something we'll be able to add to our list.

Would you be interested in helping with this PR given help + guidance from @peterp? No pressure at all as we understand either way. Thanks!

**Comment by kibertoad** [comment]
Would be happy to.

**Comment by peterp** [comment]
@jeliasson Absolutely, I'll write down the instructions, but I think we should open a PR that makes `rw dev api` look for the existance of `api/src/server.ts` which runs that instead.

Here are the steps to running your own api-server instead of relying on Redwoods:
1. Create a `dev` script in `api/package.json`:
```json
"scripts": {
    "dev": "NODE_ENV=development yarn rw prisma generate; yarn nodemon -w src -e ts,js --exec 'yarn rw build api --no-db; node dist/server.js'"
  }
```
2. Install `nodemon`: `yarn workspace api install -D nodemon`
3. Add a `dev` command to the root `package.json` file:
```json
"scripts": {
    "dev": "yarn workspace api dev & yarn rw dev web"
  }
4. Now instead of running `yarn rw dev` you'll run `yarn dev`
```

How does this work?

Nodemon monitors the `api/src` folder for changes. When it detects a change it'll rebuild the api using `yarn rw build api` and then it'll launch the build `dist/server.js` file.

**Comment by jeliasson** [comment]
@peterp Works great, thank you! 

A minor typo on `yarn workspace api add -D nodemon` (`install` instead of `add`) but otherwise 👌

> I think we should open a PR that makes `rw dev api` look for the existance of `api/src/server.ts` which runs that instead.

Agreed.

**Comment by thedavidprice** [comment]
@dthyresson could you take a look at this one for you to work on for v0.39? I'd like to prioritize this for inclusion in v1-rc.

@kibertoad greatly appreciate your offer to help! Given that we're down to a couple of weeks window to get this into v1 (and assuming your time is limited), would you be able to help review and direct a PR if we can get one going? If that feels most efficient for you as well, let's proceed forward that way!

**Comment by kibertoad** [comment]
I still have some time to start working on it today, let me try to take first swing at it.
