### ISSUE TITLE
Current GitPod + Redwood Issues

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#3430]
cc @dac09 @mikenikles

GitPod test with current v0.37.0 release branch:
http://gitpod.io/#https://github.com/redwoodjs/redwood/tree/release/minor/v0.37.0

## API Port: broken proxy
After startup with `yarn rw dev` seeing this console error, which breaks API in the Test-project.
```
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8910/graphql to http://[::1]:8911/ [EADDRNOTAVAIL] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
<img width="398" alt="Screen Shot 2021-09-25 at 11 24 42 AM" src="https://user-images.githubusercontent.com/2951/134782474-6abc0992-95db-40b4-90bf-22c68e108797.png">

My best guess is this is due to changes in the Webpack-dev-server API (upgraded to v4 in Redwood v0.36): https://webpack.js.org/configuration/dev-server/

I can't find applicable settings in GitPod to manage this.

## Safari Console: output is hidden
In the screenshot below, you can see the output is available (highlighted block), but the font is styled so that it doesn't display:
<img width="889" alt="Screen Shot 2021-09-25 at 11 26 36 AM" src="https://user-images.githubusercontent.com/2951/134782507-52b14d86-054c-496f-8812-eeaf8a3d77e5.png">

##

**Comment by mikenikles** [comment]
It turns out the IPv6 proxy target causes the issue. It was first introduced in https://github.com/redwoodjs/redwood/commit/431b32a758ce5c33c987c36e4ba74795f7fe3a64 together with additional headers that are no longer there from what I can see in the latest code.

If I use the following, it works on Gitpod:

```
target: `http://localhost:${redwoodConfig.api.port}`,
```

**Caution:** IPv6 was introduced for a reason, but given the other part of that commit no longer exists, maybe `localhost` is fine. This needs to be tested though.
