### ISSUE TITLE
Option to create scaffolds with Tailwind styling

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3554]
As requested by @mojombo: if you have Tailwind configured, let's create the scaffold/dbAuth templates with Tailwind classes instead of using all of the `rw-` custom classes. This makes it more likely that you'll want to take the time to customize them and keep them around. 

Should include:

* Scaffolds
* Login/Signup/ResetPassword/ForgotPasswordPages from dbAuth

~This means we could skip creating the `scaffold.css` file altogether. Any other generator that checks for the existence of this file needs to check for Tailwind config instead, and generate Tailwind-supported versions of themselves (currently just the dbAuth pages).~ As we further fleshed out the idea in the comments below, we'll keep `scaffold.css` and just update the styles from raw CSS rules like `margin: 0 auto` to Tailwind's `@apply` directives, like `mx-auto`. This gives us once place to go to make changes to all scaffolds, but those changes are still just Tailwind classes.

Could also include a flag to force Tailwind: `yarn rw g scaffold User --tailwind` and one to *not* use Tailwind if it otherwise would: `yarn rw g scaffold User --no-tailwind`

**Comment by cjreimer** [comment]
Rob, I like this idea.  As a user of tailwind, one of the things I try to avoid is to keep repeating the same long lists of utility classes over and over in my application.  I try to avoid className repetition through common component creation.

This is a potential concern on the scaffolds, on the forms for example.  For every TextField and every NumberField on every form, we likely could have the same long list of tailwind utility classes.  

Are you thinking of just repeating the long className lists or some form of component encapsulation?

What would you think about Redwood creating a set of standard components for NumberField, Textfield, etc in the user's source files as user-editable files?  That way, if the user wants to edit the tailwind styling, they just have to in one spot rather than updating all the component instances on every form.  More DRY code.  There are a few different ways to attack this problem, but simple component creation might be the easiest for new users.

Thoughts?

**Comment by KrisCoulson** [comment]
I've been thinking about this for a while that it be really nice to have those be utility classes. Could we do something like in scaffold.css mimic tailwind utility classes if someone were run the tailwind command just remove the scaffold.css file? I guess that might break down if people made edits to the scaffold.css file wonder if we could code mod update existing scaffolds to tailwind. Just putting random thoughts on the topic.

**Comment by orta** [comment]
+1 to the component classes technique, feels like a scalable way to handle there still being one template file but with different behaviors depending on what you use
