### ISSUE TITLE
[Scaffold] Fields which are not required in prisma.schema are being required in the scaffold form

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#3580]
Given the following model:

```
model Product {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  age   Int?
  price Float?
}
```

Generating a scaffold for this model should only have `email` as a required field. However, *every* field is being required in the requisite form inputs:

```jsx
<TextField
  name="name"
  defaultValue={props.product?.name}
  className="rw-input"
  errorClassName="rw-input rw-input-error"
  validation={{ required: true }}
/>
```

![image](https://user-images.githubusercontent.com/300/137522287-555099ba-8d98-4e34-b410-2e48ab6080d4.png)

I noticed that the default options for an input are that it is required: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/scaffold.js#L375 and the logic farther down in that method uses that default validation if it isn't defined in the schema itself: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/scaffold.js#L395-L397  I think this is the source of the problem. It should be that there is *no* validation by default, and only if the column is required would validation then be added. I'm not 100% sure this is the fix, but is a good place to start investigating!

**Comment by aggmoulik** [comment]
Hey @cannikin, I found the mistake i.e, When we use the type as `String` it takes the default values which looks sensible here as the only type that remains is `String`. So, it makes sense to have default values that are by default okay for the `String` type. 

But, the component generation columns are not taking models value into consideration before applying to the default values. So, I am thinking to use the model-defined values instead of directly assigning the default values as the models have the full context of the column.
