### ISSUE TITLE
Docs syncing

### ISSUE THREAD

**Issue by macovedj** [redwoodjs/redwood#3607]
If I understand correctly [this list](https://redwoodjs.com/docs/redwood-router) determines whether docs built for redwoodjs.com come from the redwood package README.md or from the markdown defined in the docs folder in the `redwoodjs.com` repo.  Is there a reason not to have all of them come from either github or that folder?  Also... I expected there to be a network request that got the list of docs... was surprised to see it's hardcoded.  Does it make sense to move the network requests that are currently occurring in the website build to the client?

**Comment by thedavidprice** [comment]
> Is there a reason not to have all of them come from either github or that folder?

^^ It's just historical reasons. Docs started in this repo. We migrated most over. Some stayed here because originally we thought the packages would be helpful to other projects (like the Router and Auth) — because the package specific README is used on the related NPM page (and included in the published package), we needed to keep them together.

But that's not the case, so now we're just moving them over to .com. Whenever we have time + impetus.

To be clear, it's really easy to keep them wherever from a "build" perspective — just link to the path. But because we currently just queue up all the PRs with docs for the _next_ release, and then manually merge all at once, it's a workflow hassle. (In the future we'll have a better process for doc versions.)

> Also... I expected there to be a network request that got the list of docs... was surprised to see it's hardcoded. Does it make sense to move the network requests that are currently occurring in the website build to the client?

Not exactly sure which context you're referring to here. But I'll take a stab at what I understand your question to be.

It's true the docs are just .md files in a specific directory (for 90% of the case). But there are some cases where we need to set a specific, alternate title (for SEO or characters), or might need other doc-specific config. So that's why we have a list of docs to be built and not just an automatic "find and build every .md in this directory" process. Lastly, some of those .md files are placeholders or READMEs.

Helpful? If so, please close this issue. Or ask away!
