### ISSUE TITLE
Add built-in type defs for SVG imports

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3710]
### What? 
Currently importing `.svg` files throws a TS error, because SVGs don't have types.

### Solution
Include this ambient override

```
declare module '*.svg' {
  import React = require('react')
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>
  export default ReactComponent
}

```

### [SVGs in Redwood](https://s.tape.sh/Vw1SvHKc)
[![Img](https://s.tape.sh/api/thumbnail?tapeSource=https://tapes.tape.sh/ckihmf0eh00050ujpe7lot4mt/S3XHYvd-7sTi1KWl3D4ci.mp4)](https://s.tape.sh/Vw1SvHKc)

**Comment by jacobarriola** [comment]
@thedavidprice I'm happy to get started on this task - seems simple enough for my first contribution. lmk!

**Comment by dac09** [comment]
Go for it @jacobarriola! Assigning to you :)

**Comment by jacobarriola** [comment]
Thanks, @dac09 - I'll get started this weekend!

**Comment by jacobarriola** [comment]
Hey @dac09 - I started working on this tonight and am having a little trouble finding the solution. Can you provide any insight on how to move forward?

I watched your screen share and have an understanding of what to do; however, I don't know the approach I should take within the RW framework as it's a bit overwhelming

Steps taken to get set up (no issues):
* 📺 watched the contributor getting started video
* Forked the repo
* Created a test project via `yarn build:test-project`
* Synced my test project to the forked repo. Seems to be synced up because it recompiles after I make changes to the framework repo

Steps taken to attempt to fix the TS errors (no success)
* 👎🏽  create the `declare module` block in the forked repo (framework) -> /packages/web/ambient.d.ts
* 👎🏽 create a new file called `/packages/web/svg.d.ts` and added the `declare module` block; updated the `includes` array in `/packagesweb/tsconfig.json` to include the new file

Both options still render the error in my test project, so perhaps I'm not approaching this problem the correct way.

**Comment by dac09** [comment]
Looks like a good first attempt @jacobarriola! I think your contributor workflow seems to be working ok! 🚀

But the issue you're seeing is because you are adding the declarations to the framework, and not into the test project. 

In order to make sure these declarations are loaded into the users project here's what I suggest:
1. create svg.d.ts in packages/web/src/svg.d.ts
2. import this file in packages/web/src/index.ts

An example of us doing this is in this declaration here `packages/web/src/global.web-auto-imports.ts`

While you're doing this would please also check if we need to do anything similar for jpg, gifs, bmps etc.? Thanks 👍

**Comment by jacobarriola** [comment]
Ok, thanks @dac09. I'll give it another try tonight. Thanks!

**Comment by jacobarriola** [comment]
Thanks again for the help, @dac09 👏🏽 . You made the contribution experience for a first-timer a delight 🍦!

**Comment by dac09** [comment]
Glad I could be of help! Hope to see more of you around here - are you on our discord? https://discord.gg/redwoodjs

Ping me over there (`@danny` on there) will add you to the contributors group!
