### ISSUE TITLE
Add Support for Serverless Stack Framework

### ISSUE THREAD

**Issue by aggmoulik** [redwoodjs/redwood#3870]
Hi @thedavidprice @jtoar, Recently I found a serverless framework startup, [Serverless Stack](https://serverless-stack.com/), It is trying to fix the serverless environment with a good way of writing tests.

We already support serverless for AWS and It is an extension to the AWS SDK, I suppose it is not hard to add support for it.

Would love to get your view on it.

**Comment by ajcwebdev** [comment]
I've checked this out a little bit, seems like a cool tool and definitely worth looking at. I believe it's a wrapper on top of [CDK](https://aws.amazon.com/cdk/) along with the AWS SDK.

I would be curious if it would make more sense to first figure out deployment with just the CDK since that will give us more fine grained control, and then we can make a more informed decision about how the DX of SST compares to vanilla CDK.

**Comment by tejans24** [comment]
We've been using a lot of CDK, it would be awesome to add vanilla CDK support to redwood. Both for deploying and introducing other AWS services into the mix.

**Comment by thedavidprice** [comment]
Agreed about vanilla CDK support! We won't be able to prioritize that for the near-term but would most definitely welcome a community contributor taking the lead in which case we'll support and guide as best we can.

Note: there will be some extra steps here to handle building and bundling functions. But the work has been done before and can be replicated for CDK.

For reference, here's the implementation for Serverless:
- Setup Deploy command: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/deploy/providers/serverless.js
- Docs: https://redwoodjs.com/docs/deploy#serverless-deploy
