### ISSUE TITLE
[deploy: serverless]  Serverless CI/CD integration

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#3988]
Serverless projects can be built and deploy through the serverless ci/cd platform: https://www.serverless.com/ci-cd

Following convention of the other `setup deploy` commands, we should verify that the serverless.yml and configurtion generated by our setup command will work out of the box on serverless ci/cd.

**Comment by ajoslin103** [comment]
Personally I dislike using their dashboard - maybe this could be optional?

thanks
Al;

**Comment by cannikin** [comment]
@ajoslin103 have you setup CI/CD with serverless just through their CLI command? The dashboard contains a bunch of options, which I *guess* would be possible to set and change through the CLI, but would involve a ton of typing and --help checking to get the syntax right!

**Comment by ajoslin103** [comment]
@cannikin I've a few projects deploying via serverless -- none of which are Redwood, and none of which are deploying thru CI/CD -- frankly I won't be doing that again.

Now that docker & redwood is on-deck I'll be using that.  My AWS guy has been waiting for that so he can run me in his Kubernetes area -- I have enough to deal with and would like to just hand code to him.

**Comment by cannikin** [comment]
Uh oh, is there something bad about Serverless CI/CD deploys that I don't know about??

**Comment by ajoslin103** [comment]
not to my knowledge, I just haven't gotten them to work

I know that others have and that was about a year ago when I was trying -- so it should be do-able by now.

my reluctance to go back to it is because Redwood is filling all my needs

My needing to use it was that I wanted AWS Lambda's -- they worked ok with Serverless (I didn't like having to put my environ vars into the .serverless.yml file -- but I know better now.

Frankly, I just want to get that Redwood Docker thing working and give my code to my AWS guys so he can deal with scaling and everything -- Netlify got me here, but they won't get me where I need to be.

**Comment by dac09** [comment]
Closing this ticket, as we added a new `--pack-only` flag to `yarn rw deploy serverless` in https://github.com/redwoodjs/redwood/pull/4159. 

The process will be added to the docs:
![image](https://user-images.githubusercontent.com/1521877/152394552-af50febd-b264-4160-809c-b0f06e3d3b8a.png)
