### ISSUE TITLE
`rw-test-app` improvements

### ISSUE THREAD

**Issue by virtuoushub** [redwoodjs/redwood#4163]
cc @jtoar / @dthyresson /  @thedavidprice

I noticed while working on #3515 that the generated `jest` tests and `storybook` stories are broken.

For example, the generated `BlogPost.stories.tsx`, and `BlogPost.test.tsx` do not have the proper mock passed into them (see screenshot).

![image](https://user-images.githubusercontent.com/4303638/149624840-0289ffc3-0a93-4422-bef2-b5f711620c9f.png)

There is more, such as the wrong query from `'types/graphql'` being used in `BlogPostCell.tsx`. We try to `import type { FindBlogPostQuery } from 'types/graphql'` , but `FindBlogPostQuery` does not exist (there are types such as `BlogPostQuery` , and `FindPostById` but it is sort of unclear which to use [probably `BlogPostQuery`]).

---

Looking at some prior art in the codebase, I think the gist of what is needed to fix is updating some of the `codemods` in https://github.com/redwoodjs/redwood/tree/main/tasks/test-project, maybe leveraging https://github.com/redwoodjs/redwood/tree/main/tasks/e2e/cypress/integration/03-storybook/codemods ? 

---

Linked #3287

**Comment by dac09** [comment]
These are codemods in the test project and not in e2e tests :) 

They're located here: `tasks/test-project/codemods` -  and indeed its due to the codemods such as https://github.com/redwoodjs/redwood/blob/main/tasks/test-project/codemods/blogPostCell.js needing an update.

**Comment by virtuoushub** [comment]
@dac09 - thanks for clarifying.

- how prevalently are codemods used across the codebase?
  - Does it make sense to generalize them, so that there is a single source of truth? 
- Also regardless of whether to look into rearchitecting codemods; as the code there codemods affect changes how do we ensure this type of issue does not happen again?

**Comment by dac09** [comment]
> how prevalently are codemods used across the codebase? 
Well "codemods" currently mean 3 things:
1) The simple copy and replace changes we make in the e2e tests (which creates an entirely different project, following the tutorial).
2) The slightly more complex codemods we make when generating the test project
3) The codemods package, which is meant to give an easy way to upgrade users' projects when we have breaking changes.

I don't think there's anything in common between these really, apart from the fact that both (2) and (3) uses jscodeshift. They serve completely different purposes at the moment. So I don't think there's any reason to group them IMHO.

(2) Is where we need the fix, the easy way to prevent this from happening would be to make the codemods a little smarter. i.e. don't just insert blocks of code like it currently does, but to "surgically" change the code like we often do in the `@redwoodjs/codemods` package. 

I'm not 100% sure how much effort this will be right now - might just be a few renames here and there, or it could be a little more involved in making the codemods a little smarter. e.g. 
- instead of calling it `BlogPostQuery`, renaming it to `FindBlogPostQuery`,
- updating the corresponding mock in BlogPostCell.stories.tsx

> Also regardless of whether to look into rearchitecting codemods; as the code these codemods affect changes, how do we ensure this type of issue does not happen again?
These were created when a lot of our APIs were in flux, now that we're approaching v1, I expect things to be more stable. We are also evaluating how we're going to change the e2e tests (maybe use the same project, instead of using 2 different ones, etc.).

**Comment by dac09** [comment]
So I spent a bit of time looking at it, and while writing the codemod for the generated mocks was a little painful, overall wasn't too bad and even found a bug! @virtuoushub want to take #4180 for a spin? (just have to click the "open in gitpod" button)

**Comment by virtuoushub** [comment]
@dac09 - took a spin in gitpod and lgtm overall, thanks! 

one minor thing was the generated `BlogPost.stories.tsx`, and `BlogPost.test.tsx` still do not have a mock passed into them. While I think this is ok, as other components/stories/tests which use this component as subcomponent _do_ have proper mocks; it leaves the utility/usefulness of those generated `.test.tsx` / `.stories.tsx` files in question.
