### ISSUE TITLE
Make scaffold generators use `emptyAsUndefined`

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwood#4354]
The DMMF (Data Model Meta Format) we get from Prisma tells us if a field is a relational field to another model or not. We could use this information to set `emptyAsUndefined` on relevant form fields, instead of just relying on the "ends with `Id`"-naming convention.

This depends on https://github.com/redwoodjs/redwood/issues/4353 being implemented first.

For more context:
PR: https://github.com/redwoodjs/redwood/pull/4302
Issue: https://github.com/redwoodjs/redwood/issues/4297

**Comment by samthuang** [comment]
hello @Tobbe - I'd like to give this issue a try if no one is actively working on this 🙂

**Comment by thedavidprice** [comment]
@samthuang if you're still interested, it would be great to have your help! Just an FYI that @Tobbe is traveling this week but I'll loop him in to check when he's back.

Feel free to start with a draft PR. Do loop in myself and Tobbe.

Lastly, I'm assuming you want to take this so I'm assigning to you now. Let me know otherwise.
