### ISSUE TITLE
Don't blow up if a page is manually imported in Router

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#44]
Right now if you explicitly import a page in the Router you'll get an error in the browser:

![image](https://user-images.githubusercontent.com/300/72479966-be9ab780-37aa-11ea-94ab-76fff6df3fd4.png)

**Comment by mojombo** [comment]
I think instead of deleting any conflicting imports in the file, we should consider them overrides. This way you could optionally do a regular `import` instead of the default code-splitting `import()` if you wanted that route to be included in the main bundle. Webpack also has some cool preload behaviors you can request on the `import()` that people may want to use. You could do that by just doing the import yourself and it would override our default. Curious what @peterp thinks about that approach.

**Comment by peterp** [comment]
I really like this and I think it would feel intuitive to manually import something and expect it to win over the automatic import.

**Comment by peterp** [comment]
Closed in #104
