### ISSUE TITLE
Please add CLI: rw setup ui mui-emotion

### ISSUE THREAD

**Issue by ajoslin103** [redwoodjs/redwood#4599]
I'd love guidance on how to add this cli command

    `yarn rw setup ui mui-emotion` 

    (I think it's worth naming it what it is, since it uses these packages)
      @mui/material 
      @emotion/react
      @emotion/styled

I've cloned up the repo and found that tailwind & chakra-ui are sort of pushed together 

I'd like to re-organize along these lines and try to set us up for easily adding ui frameworks

A. segmented

<img src="https://raw.githubusercontent.com/ajoslin103/redwood/ajoslin103-images/Screen%20Shot%202022-02-27%20at%208.32.53%20PM.png" />

B. gathered

<img src="https://raw.githubusercontent.com/ajoslin103/redwood/ajoslin103-images/Screen%20Shot%202022-02-27%20at%208.43.56%20PM.png" />

thoughts?

Al;

**Comment by simoncrypta** [comment]
Look like you're in the right path to add the CLI command, does something else block you except the organization ?

I like your idea of how you organize things, I remember having a discussion with @dac09 about this, I think he has a reason on why is it like this ?

**Comment by dac09** [comment]
I think its best not to add another level of nesting @ajoslin103 - the setup script is setup in two ways:
1. Only look one level deep, so that it find the nested `setup ui` command here:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup.js#L13 (see comment)

2. The ui.js script is setup to only look in libraries, with no nesting. So only libraries/*.js will be picked up - I don't see a reason to change this, if you'd like to have code specific to a library, its probably best to keep them in the provider's file. If you need to split it up, its worth trying to make it generic and putting it into tasks. If not, just naming it so that its obvious, or putting it in a folder in tasks coudl work.

**Comment by dac09** [comment]
With regards to emotion and mui, I think it would be nice to have a `setup ui emotion` and then prompt the user (using https://www.npmjs.com/package/prompts, which already use in the CLI) if they want vanilla emotion, or mui or something else.

One thing to note re: emotion, I never got round to figuring out how to make storybook work with it. Do you have it working on your project?

**Comment by ajoslin103** [comment]
thanks for the insights 

I'll keep the current organization and clean up with filenames

I've not gotten mui+emotion installed - thanks for the heads-up on the emotion+storybook thing

I'm going to keep the mui+emotion to start, I think they may be coupled in mui

I like the idea of being able to install frameworks and styling separately, but I don't know how the go in together yet

My main focus right now is mutating cells 

I'll be lucky to get this and mutating cells in before my

**Comment by jtoar** [comment]
@ajoslin103 I'm gonna close this one since it's been a while, but if you were still interested in PRing this, you're welcome to! (No pressure though)
