### ISSUE TITLE
Add <Radio> field

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#464]

**Comment by vikash-eatgeek** [comment]
Could I take this task?

**Comment by cannikin** [comment]
That would be great, thanks! I haven't had a chance to look into how react-hook-form works with radios, but I was imagining that you can put several of them on the page and give them all the same name, and then whichever one is checked on is the value that's returned to `onSubmit`. I'm not sure how validation works though...can you put `required: true` on only one of them or do they all need it?

**Comment by vikash-eatgeek** [comment]
Thanks for assigning the issue. Yup, this is how it works. One of them is enough. If the user wants to put multiple radio buttons it won't cause any problem. Have required true for one Radio button or multiple radio buttons is the same.
I was thinking of putting `required: false` as default. because this is the default behavior of the radio button.  or we can just put `required: true` if it is consistent with our form design. thanks!! 🙂

**Comment by cannikin** [comment]
None of the other form fields are required by default so I would keep that same behavior with this one.

**Comment by vikash-eatgeek** [comment]
thanks!! I have started working on it. Still setting up the development environment. I will raise a pr soon.

**Comment by vikash-eatgeek** [comment]
I have opened the pr. Let me know if some improvement is needed. And after looking in `react-hook-form', it turned out that we need `required` true for all the radio buttons in a group. thanks!!
