### ISSUE TITLE
[Yarn 3] `rw-server` binary only spins up "api" side regardless of args

### ISSUE THREAD

**Issue by callingmedic911** [redwoodjs/redwood#4672]
With yarn 3, when we run `yarn rw-server` or `yarn rw-server api web`, it only runs api side. In yarn 3, this line:
https://github.com/redwoodjs/redwood/blob/fdb0990364061d991ea872944b42ba9b5f2f10ff/packages/api-server/src/index.ts#L31
is always evaluated to true, unlike in yarn classic.

Since `rw-api-server` is supposed to deprecate with v1, how about we remove handling for it and cleanup this check. It would result in something like:
```typescript
if (require.main === module) {
  if (
    (positionalArgs.includes('api') && !positionalArgs.includes('web'))
  ) {
    apiServerHandler(yargs.options(apiCliOptions).argv)
  } else if (
    positionalArgs.includes('web') &&
    !positionalArgs.includes('api')
  ) {
    webServerHandler(yargs.options(webCliOptions).argv)
  } else {
    bothServerHandler(yargs.options(commonOptions).argv)
  }
}
```

cc: @jtoar @thedavidprice

**Comment by jtoar** [comment]
@callingmedic911 you're running `yarn rw-server` directly right? Not via the Redwood CLI? Only reason I ask is I didn't have to make a bin proxy for `rw-server`, which basically means I didn't think about it. I did make a bin proxy for `rw-api-server-watch` since that's used by `yarn rw dev`. I'm guessing you install `api-server` in api, then run `yarn rw-server` (in the api directory)—that way the bin's available since it's top-level. But did I get that right? Is that the context?

**Comment by callingmedic911** [comment]
That's exactly right, I should have added the context. 

It's in the docker file, so as the last stage of the build I'm keeping only the API side with absolutely essential things.
