### ISSUE TITLE
Storybook should not run typescript checks by default

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwood#4676]
Currently storybook runs typescript by default if you have a typescript project. This prevents Storybook from compiling if you have a type error. This doesn't really align well with how Redwood functions. We do not type-check to run the app and Storybook should probably still be able to run even if you have an error. 

Additionally Storybook fails out of the box because of new TS projects have no SDLs.

We should 

- Turn off Type checks by default
- document how to turn on type-checking on if one wants it. Like below 

```
// add this to storybook.config.js
typescript: {
    check: false,
    // By default, the checker runs asynchronously in dev mode. Force it to run synchronously.
    checkOptions: { async: false },
  },
  ```
  
### Context
https://redwoodjs.slack.com/archives/G01JBDDU2CF/p1646495942235129

**Comment by KrisCoulson** [comment]
@jtoar you can assign this one to me. I am going to fix it this week. It stemmed from a conversation with @thedavidprice. I just wanted to make sure it was documented

**Comment by Tobbe** [comment]
> It stemmed from a conversation with @thedavidprice. I just wanted to make sure it was documented

Could you include relevant parts of that conversation for context? Thanks 🙂

**Comment by KrisCoulson** [comment]
@Tobbe added link to slack converation

**Comment by thedavidprice** [comment]
@KrisCoulson @Tobbe I'm going to personally prioritize this because of Storybook related marketing efforts in the near-term.

Ideally, we'd have a RW CLI options to togger the TS check in case of project being TS. Here's the simple config:
https://github.com/redwoodjs/redwood/blob/11fbb756ade201455ff13f0104e4f362a3bc6bfe/packages/testing/config/storybook/main.js#L143-L147

But there's not a related start-storybook option to pass. And I don't think it's worth the "we'll just add another env and check that in webpack...", especially when the root of all this happening is unrelated.

My suggested plan:
1. I'll remove the config above from storybook/main.js
2. Will hand-off the documentation for adding the config (if desired)

I'm planning to do step 1 today and include in RC.5. Will then hand off step 2, which is low priority.

Suggestions otherwise?

cc @virtuoushub

**Comment by rkmitra1** [comment]
FWIW. This change (turning typescript off on storybook) will be welcome. I have been banging my head on getting .mxd working. It is easy to make it work in the app but it broke Storybook (on my typescript rw app).

I have checked that it will be easy to turn Typescript check in Storybook back on by:
1. create web/config/storybook.config.js file
2.  add to this file

module.exports = {
  // https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration
  typescript: {
    check: true,
    checkOptions: { async: false },
  },
}

@thedavidprice My research was inspired by you nice Full-stack development video

**Comment by thedavidprice** [comment]
Hi all, the config has been removed in #4699 I'll be publishing a patch v0.49.1 to get this in.

Based on the behavior with types when a Cell exists but the Cell query does not (this will be very common in the "design-driven full-stack workflow), at this time I cannot recommend we even suggest projects enable Storybook type checking. I don't think we should update the docs.

I'll leave this open for discussion. Will close when/if there's agreement.

Thanks again!

**Comment by KrisCoulson** [comment]
@thedavidprice thanks for pushing this through so fast haven't had a chance to remove it. So thank you.

**Comment by thedavidprice** [comment]
@KrisCoulson @dthyresson 

At this point, I don't think it's worth keeping this open to figuring out a way forward, docs or otherwise. Suggestions either way?

**Comment by dthyresson** [comment]
I defer to @KrisCoulson but ok by me.

**Comment by Tobbe** [comment]
> However, if I generate a Cell and then generate types, Storybook build will still fail because there can't be any types on a Cell if no SDL file exists.

@dthyresson was this the same issue you ran into with (thing) that prompted you to just go build out the entire backend first, before returning to SB?
