### ISSUE TITLE
[RFC] Multiple Web Projects share one API

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#480]
Many companies have the use case of two clients that would share one API. 
such as marketplaces that could have a buyer client and a seller client that would share one API and not necessary want to be in the same package

Would redwood be a good fit for these kind of companies without having to build their own mono-repo. 
To what i understand this is not currently supported from what i can see in the docs.

these are the problems i for-see with he implementation 
### Problem 1 - redwood.toml
redwood toml would need tweaking to defined that there are multiple clients that use the api, example below;
```
[web]
  name="Client 1"
  port = 8910
  apiProxyPath = "/.netlify/functions"
[web]
  name="Client 2"
  port = 8912
  apiProxyPath = "/.netlify/functions"
[api]
  port = 8911
[browser]
  open = true
``` 
### Problem 2 - netlify.toml
each client would potentially need their own netlify.toml. 
One solution would be to allow the Netlify toml file to be able to be ran from one of the clients. 

### Problem 3 - Should redwood support multiple web clients?
This is more a question of responsibility of redwood without even thinking of tech.
I think that because redwood also helps make and control the API.
It would be make sense if redwood could have multiple clients that could connect to the same API.

 Would like to hear what other people think of this?

**Comment by thedavidprice** [comment]
Hi @Burnsy Great idea! We’re big believers in having one API to “rule them all”. And it turns out this is built into the concept of Redwood’s Sides. 🚀 But you're correct, it’s not currently supported as envisioned, however, it in in progress and you can follow the work here: 
https://github.com/redwoodjs/redwood/pull/355

Given that this has already been decided, I’m going to close out this issue in favor of moving discussion/questions to the PR. When/if needed, we can open this up again.
