### ISSUE TITLE
[Docs] Add note to baremetal deploy docs about interactive ssh sessions and .bashrc

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#4949]
Make sure that .bashrc isn’t skipping setup on non-interactive sessions!

**Comment by zpeters** [comment]
Im not sure if this is helpful but i struggled with this from using nvm on my target server.  All commands ran when logged in through ssh, but failed when i tried to run a deploy.

Ended up that the default for ubuntu (maybe others) is that it will  ignore .bashrc in a non-interactive session.  THis was confusing.  My understanding was that bash_profile was only read for interactive, but bashrc should run for any session.

Anyway the fix for me was to edit bashrc and comment out the statement about *not* running in in *non-interactive* session


```
# If not running interactively, don't do anything
#case $- in
#    *i*) ;;
#      *) return;;
#esac
```

**Comment by cannikin** [comment]
Me too, and I knew I had to remind myself so I created this issue right away. We've been busy with launch week, but I'll see if I can add this to the docs today!

**Comment by cannikin** [comment]
Me too, and I knew I had to remind myself so I created this issue right away. We've been busy with launch week, but I'll see if I can add this to the docs today!

**Comment by zpeters** [comment]
let me know if i can help, i know y'all are busy!

**Comment by thedavidprice** [comment]
@zpeters please do if you're up for it! Loop @cannikin in on the PR.

**Comment by zpeters** [comment]
Happy to do this.  Thank you.  will look at it over the weekend

**Comment by zpeters** [comment]
Added pr #5091 for review
