### ISSUE TITLE
Auth: Auth0 getPublicKey is undefined / TypeError: Cannot read property 'getPublicKey' of undefined

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwood#5079]
both @twodotsmax and @[aaronvanston](https://community.redwoodjs.com/u/aaronvanston) reported seeing an exception in the Auth0 decoder where an error of `TypeError: Cannot read property 'getPublicKey' of undefined`.

See: https://community.redwoodjs.com/t/auth0-getpublickey-is-undefined/2914/10

This causes an unhandled exception when decoding rather than requiring an unauthenticated user.

Aaron is unsure why this is happening, but it could be that some clients are sending tokens that are invalid for the JWKS (the set of keys that can verify the token) and thus causing many api errors.

Suspect that some defensive checks in the way the header and key is handled can help resolve this:

https://github.com/redwoodjs/redwood/blob/bfb7898ae3a17caaea3dac5c7dd395a5d5feca14/packages/api/src/auth/decoders/auth0.ts#L43

For example, adding defined checks in:

```ts
   jwt.verify(
      bearerToken,
      (header, callback) => {
        client.getSigningKey(header?.kid as string, (error, key) => {
          callback(error, key?.getPublicKey())
        })
      },
```

And ideally the error will then later get rejected and return a null decoded token.

https://github.com/redwoodjs/redwood/blob/bfb7898ae3a17caaea3dac5c7dd395a5d5feca14/packages/api/src/auth/decoders/auth0.ts#L57

**Comment by twodotsmax** [comment]
any progress? haven't had the time to help but this kills my api server regularly, probably will just contain it

**Comment by aaronvanston** [comment]
I've been able to patch this successfully using `yarn patch`, so I wanted to document the process for anyone else to have this issue before the official patch.

# Requirements:

- Yarn 3: You will need to be using Yarn 3 to utilise `yarn patch`; if you're on RedwoodJS version v0.48.0 or higher, you should already have this set up. 
- Local copy of RedwoodJS

The fix/ guard for this issue is somewhat trivial to prevent it from crashing the function, it possibly does not handle the underlying error correctly, but it will prevent it from hanging. 

As @dthyresson  has pointed out, all we need to do is update the callback where it executes `key.getPublicKey()` and use optional chaining to make sure `key` is defined before calling `getPublicKey`

As seen on this line:
https://github.com/redwoodjs/redwood/blob/bfb7898ae3a17caaea3dac5c7dd395a5d5feca14/packages/api/src/auth/decoders/auth0.ts#L44

```diff
-- callback(error, key.getPublicKey())
++ callback(error, key?.getPublicKey())
```

# Applying the patch

## 1. Cloning a local version of RedwoodJS

Open the RedwoodJS repo locally, if you're not on the latest version of RW you will need to move this back in time to the tagged release. For me, I'm on version 0.48.0, so I needed to run:

`git checkout tags/v0.48.0 -b 48-patch`

This checkouts the  0.48.0 version of redwood and creates a local branch of `48-patch` for you to work on.

Confirm that the tag checkout has worked correctly, by loading one of the package.json files and seeing if a peer redwood dependency is on 0.48.0. For example, opening `packages/api/package.json` has a dev dependency of `"@redwoodjs/auth": "0.48.0",`, make sure this is the same as the RW dependencies within your local application.

From here, make sure to run `yarn` to install all the dependencies.

## 2. Apply the fix

We need to now locate and apply the patch. Open `redwood/packages/api/src/auth/decoders/auth0.ts` and on line 44 as documented above, add the "?" on the `getPublicKey()` call.  

## 3. Build the `api` redwood package

We now need to build redwood to compile the code down to as it would be if it was a package within node_modules. to do this, simply run `yarn build` in the root of the repo. This will build all packages, we only really need the `api` package for this patch, however. 

After the build happens, a new `dist` directory will appear in `redwood/packages/api/dist`, you can locate the file we just patched under `redwood/packages/api/dist/auth/decoders/auth0.js`

The line we edited will now look something like the following after its been through the build steps:

```js
callback(error, key === null || key === void 0 ? void 0 : key.getPublicKey());
```

## 4. Create the patch

Create the patch in your application. Now open your application locally within the terminal, and run the following:

`yarn patch @redwoodjs/api`

It will return something like:

```
yarn patch @redwoodjs/api                                                    ⬢ v16.5.0
➤ YN0000: Package @redwoodjs/api@npm:0.48.0 got extracted with success!
➤ YN0000: You can now edit the following folder: /private/var/folders/zr/321c2cp953160v7ry44t12p40000gn/T/xfs-a5a11d73/user
➤ YN0000: Once you are done run yarn patch-commit -s /private/var/folders/zr/321c2cp953160v7ry44t12p40000gn/T/xfs-a5a11d73/user and Yarn will store a patchfile based on your changes.
➤ YN0000: Done in 0s 49ms
```

Open the temp directory in your editor. This will just include the api package for redwood, locate the file we edited within redwood

`dist/auth/decoders/auth0.js`

Overwrite this entire file with the recently built file from the dist, making sure the new guarded callback is included, save tthe file.

Complete the patch by running the command it provided when creating the patch, in my case: `yarn patch-commit -s /private/var/folders/zr/321c2cp953160v7ry44t12p40000gn/T/xfs-a5a11d73/user`
 
Run `yarn` to regenerate the lock file. 

This step will have created a file within `.yarn/patches/@redwoodjs-api-npm-0.48.0-780fe6a99c.patch`

and it should look like:

```diff
diff --git a/dist/auth/decoders/auth0.js b/dist/auth/decoders/auth0.js
index 45cfbd4016e96d82e4c93b8d0a4b36e403634a4c..5348d330810496f06b856512c5fc2df495049d19 100644
--- a/dist/auth/decoders/auth0.js
+++ b/dist/auth/decoders/auth0.js
@@ -54,7 +54,7 @@ const verifyAuth0Token = bearerToken => {
 
     _jsonwebtoken.default.verify(bearerToken, (header, callback) => {
       client.getSigningKey(header.kid, (error, key) => {
-        callback(error, key.getPublicKey());
+        callback(error, key === null || key === void 0 ? void 0 : key.getPublicKey());
       });
     }, {
       audience: AUTH0_AUDIENCE,
```



The patch should also be referenced within the root package.json of your application under resolutions.

```
  "resolutions": {
    "@redwoodjs/api@0.48.0": "patch:@redwoodjs/api@npm:0.48.0#.yarn/patches/@redwoodjs-api-npm-0.48.0-780fe6a99c.patch"
  },
```

## 5. Deploy

You can now deploy this. with the new patch, It will now throw 

## Note:
You will need to roll this back when updating redwood, you will need to revert both the patch file within `.yarn` and the resolution reference and re-run a yarn install.


## Big Thanks

A big thanks to @thedavidprice for walking me through the yarn patch and @dthyresson for jumping on this and debugging this!

This should tie myself anyone else over till an official patch is out.
