### ISSUE TITLE
ESLint error on `roles` param in JS project

### ISSUE THREAD

**Issue by skiabox** [redwoodjs/redwood#5101]
Eslint error inside api/src/lib/auth.js

--> 'roles' is defined but never used

**Comment by simoncrypta** [comment]
Hi @skiabox and welcome to RedwoodJS. :smile: 

I cannot reproduce this Eslint error. Is it while doing the tutorial ? If not, more context about how you use `roles` will help us.

Thanks !

**Comment by jtoar** [comment]
In TS projects, this doesn't error because we generate the correct ESLint ignore directive:

https://github.com/redwoodjs/redwood/blob/c234350e496c9c0b05998d38db2cba67b5af5617/packages/create-redwood-app/template/api/src/lib/auth.ts#L21-L25

What we need to do is add the correct directive for JS projects:
```
// eslint-disable-next-line no-unused-vars
```

**Comment by standup75** [comment]
https://github.com/redwoodjs/redwood/pull/6037
