### ISSUE TITLE
Fresh Typescript Project Throws Errors

### ISSUE THREAD

**Issue by brettdoyle44** [redwoodjs/redwood#5189]
Overview:

When creating a new redwoodjs typescript project it throws errors in multiple files in VSCode. The two biggest are on Router and App.tsx. I have tried to use David's solution in the following forum post, but as soon as I spin up dev the errors return: https://community.redwoodjs.com/t/i-see-red-squiggles-how-to-fix-type-warnings-in-vs-code/2961.

Current versions:
Node v16.13.0
Yarn v1.22.18

Steps to replicate:

1. yarn create redwood-app typescript-test --typescript
2. cd into project and run yarn rw dev
3. go into project in VSCode
4. errors show like below:

![Screen Shot 2022-04-15 at 10 11 41 AM](https://user-images.githubusercontent.com/8421096/163581964-a813007c-a1ee-431d-ac2a-ba26f899a4d5.png)
![Screen Shot 2022-04-15 at 10 11 50 AM](https://user-images.githubusercontent.com/8421096/163581965-f2fd33af-6dc8-43e5-9390-a8935e5dce8a.png)

**Comment by jtoar** [comment]
Hey @brettdoyle44, thanks for reporting this! Would you mind running two commands and pasting the output here to confirm some things? I think this may be the same issue as https://github.com/redwoodjs/redwood/issues/5104 which means our latest fix here https://github.com/redwoodjs/redwood/pull/5165 didn't work.

```
yarn rw --version
yarn why @types/react-dom
```

The output I see is:

```
# First command
1.0.1

# Second command
├─ @redwoodjs/testing@npm:1.0.1
│  └─ @types/react@npm:17.0.40 (via npm:17.0.40)
│
├─ @types/react-dom@npm:17.0.14
│  └─ @types/react@npm:18.0.5 (via npm:*)
│
├─ @types/react-dom@npm:18.0.1
│  └─ @types/react@npm:18.0.5 (via npm:*)
│
└─ @types/react-syntax-highlighter@npm:11.0.5
   └─ @types/react@npm:18.0.5 (via npm:*)

```

**Comment by thedavidprice** [comment]
Thanks for reporting @brettdoyle44 Turns out the whole of the internet using React + TS is experiencing this, but I did have it resolved — apparently not for all cases. There are a lot of Issues open on DefinitelyTyped. I'm following this one by the Microsoft Team: https://github.com/microsoft/DefinitelyTyped-tools/issues/433

Gah, this behavior is so frustrating... 🤬

Also, it works after upgrading to canary. Why?!?

## Reproduction steps to resolve with Canary version
1.  Fresh install: `yarn create redwood-app my-dir --ts`
2. `cd my-dir && yarn rw type-check` [FAILS]
3. `yarn dedupe && yarn rw type-check` [FAILS]
4. `yarn rw upgrade -t canary && yarn rw type-check` [PASSES]

The canary version has the same dep resolution as the latest. The upgrade command runs `yarn dedupe` or the Yarn 1 `npx yarn-deduplicate` equivalent. But what else would be different here such that is resolves correctly for upgrade canary but not on a new project?

Ah, there might be a more recent version of the packages... I could try that as well.

And/or there might be something else about canary that makes it resolve correctly -- I'll find out with an RC today.

**Comment by thedavidprice** [comment]
got it. will fix via 1.0.2 coming asap

**Comment by brettdoyle44** [comment]
@thedavidprice Upgrading the project to Canary worked for me. I am just starting on my project, so should I wait for v1.0.2 to start fresh project?

**Comment by jtoar** [comment]
Hey @brettdoyle44 `1.0.2` is out now. It's different from the canary because we only cherry picked the changes we needed, so it may be more stable to skip to `1.0.2` if possible.
