### ISSUE TITLE
Type errors on cell generation in newly created redwood apps

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwood#5538]
To reproduce:
- make a new project
- generate a cell

```
$ yarn create redwood-app my-redwood-app
$ cd my-redwood-app
$ yarn rw g cell post
  ✔ Generating cell files...
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.mock.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.test.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.stories.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.js`
  ⠙ Generating types ...

Error: Could not generate GraphQL type definitions (web)
AggregateError: GraphQL Document Validation failed with 2 errors;
  Error 0: GraphQLDocumentError: Unknown type "Int".
    at /Users/dom/prjcts/rwprj/rwprj/web/src/components/PostCell/PostCell.js:1:26

Error 1: GraphQLDocumentError: Cannot query field "post" on type "Query".
    at /Users/dom/prjcts/rwprj/rwprj/web/src/components/PostCell/PostCell.js:2:3
    at Object.checkValidationErrors (/Users/dom/prjcts/rwprj/rwprj/node_modules/@graphql-tools/utils/index.js:1252:15)
  ✔ Generating cell files...
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.mock.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.test.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.stories.js`
    ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.js`
  ✔ Generating types ...
```

It doesn't seem to matter if there's a model or not.

**Comment by jherdman** [comment]
I can confirm this too.

**Comment by dac09** [comment]
@jtoar and I identified, that this error happens when you're trying to generate a Cell before you have SDLs for that model.

The solution, for anyone reading this - is to generate your SDLs first with `yarn rw g sdl Model`. The reason type generation fails, is because when it tries to find the types defined in the Cell query - it errors out, because the Graphql schema doesn't define those types.

**Suggested solution:** improve the error messaging, by detecting if SDLs for that cell have been generated. We can skip type generation if it hasn't, and inform the user that they have to generate the SDL to properly use the Cell and for the red squiggles to go awya.

**Comment by jherdman** [comment]
I believe this means that the Redwood tutorial needs updating. I ran into this bug when following along through the [Cells chapter](https://redwoodjs.com/docs/tutorial/chapter2/cells#our-first-cell).

**Comment by razzeee** [comment]
Yeah, I've also tried to do the tutorial and got stuck there.

I do think I have a valid sdl created, as there's only a Post model and I do have an sdl for that. Running `yarn rw g sdl posts` yields an error, due to that existing.

**Comment by razzeee** [comment]
Changing `ArticlesQuery` to `FindPosts` seems to get me around that problem in the tuturial.
