### ISSUE TITLE
scaffold generator with relation

### ISSUE THREAD

**Issue by hos200sa** [redwoodjs/redwood#5662]
hello everyone.
I love using redwood so far.
if a model lets say shelf and it have many relation with book if run command g scaffold shelf it generated successfully but can't a create book directly in shelf page.
is there a command or have to do it manually.

**Comment by jtoar** [comment]
Hey @hos200sa, glad to hear you're liking redwood so far! And as to your question, unfortunately you'll have to do that manually at the moment.

But if you scaffold `Book`, there should be a `Shelf` field, cause a book can only ever be on one shelf so that's easy for us to generate a field for. But I'm pretty sure we don't have support for the other way around at the moment.
