### ISSUE TITLE
yarn rw deploy serverless gives this error if there's a custom function 'Cannot access package artifact at "dist/zipball/myFunction.zip"

### ISSUE THREAD

**Issue by asaf-stafflink** [redwoodjs/redwood#5675]
Using redwoodjs 1.5.1

'yarn rw deploy serverless' gives this error if there's a custom function 

'Cannot access package artifact at "dist/zipball/myFunction.zip" (for "myFunction"): ENOENT: no such file or directory, access '<Project DIrectory>/api/dist/zipball/myFunction.zip

The only zip that is created in zipball during build is the 'graphql.zip' file

**Comment by asaf-stafflink** [comment]
It's working in version 1.2.1 and broke in 1.3.0 - could be related to 'Remove nested function post processing during build'? https://github.com/redwoodjs/redwood/pull/4813/commits/00ebb798d844a03a6322c61817f6535a4be7f154

**Comment by jtoar** [comment]
Hey @asaf-stafflink thanks for your patience, I was able to confirm this locally. @dac09 I haven't had a closer look yet but do you it could be related to what @asaf-stafflink suggested?

**Comment by asaf-stafflink** [comment]
Thank you, @jtoar and @dac09 I can verify as soon as you have a branch/PR to test

**Comment by dac09** [comment]
Hi @asaf-stafflink - thanks for reporting this, and sorry for the delay in getting the fix out. 

The fix is now in PR - you are more than welcome to try it if you're familiar with our contribution workflow, but it may be easier to wait for it to be merged, then give it a go with the canary version (upgrade with `yarn rw upgrade -t canary`).
