### ISSUE TITLE
Show authentication errors in <FormError>

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#568]
Now that we have authentication we need to update the logic in `<FormError>` that tries to determine what GraphQL error occurred and format it nicely for display. Apparently this is a new kind of error completely because the error box shows but is empty:

![image](https://user-images.githubusercontent.com/300/82381244-b2d03380-99de-11ea-9a6b-93c6eb89993d.png)

The error in the web inspector looks like:

```json
{
  "errors": [
    {
      "message": "",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPost"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "AuthenticationError: ",
            "    at requireAuth (/Users/rob/Sites/redwoodjs/hammerblog/api/src/lib/auth.js:9:11)",
            "    at Object.createPost (/Users/rob/Sites/redwoodjs/hammerblog/api/src/services/posts/posts.js:15:3)",
            "    at createPost (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/@redwoodjs/api/src/makeMergedSchema/makeMergedSchema.js:29:11)",
            "    at field.resolve (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at resolveFieldValueOrError (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:434:16)",
            "    at /Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/execution/execute.js:244:18",
            "    at /Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/jsutils/promiseReduce.js:23:10",
            "    at Array.reduce (<anonymous>)",
            "    at promiseReduce (/Users/rob/Sites/redwoodjs/hammerblog/node_modules/graphql/jsutils/promiseReduce.js:20:17)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by Terris** [comment]
@cannikin Hi there. It looks like we could pass a message to the AuthenticationError() we throw in the generated auth.js file.

So [this](https://github.com/redwoodjs/redwood/blob/1e93469d5c2687c4f9add17d532159e825c4bcb5/packages/cli/src/commands/generate/auth/templates/auth.js.template#L17) could become:
```javascript
export const requireAuth = () => {
  if (!context.currentUser) {
    throw new AuthenticationError("Take a hike, buddy!")
  }
}
```

This will only get us a `rootMessage` while `messages` will still remain empty. I could insert some conditional rendering before the messages <ul> to check for messages.length so that everything gets rendered but the list. That doesn't feel clean and I can foresee this code getting even more convoluted as new fields are added and the usage of apollo-server evolves within the app.

Another related issue is that, (assuming auth was generated á la the tutorial) when I try to delete a record while unauthenticated, I should probably see an authentication error there too. But presently there's no standard component to display such a message.

I wonder what you think about two things: 1) a `web` adjacent lang module through which we pass all errors and spit out redwood-approved, component-ready error objects and 2) a flash component not unlike the one that ships with Rails.

**Comment by cannikin** [comment]
Interesting...I thought maybe the AuthenticationError was somehow a separate error from the two types I'm currently catching here: https://github.com/redwoodjs/redwood/blob/master/packages/web/src/form/form.js#L96-L113 but sending a string when throwing the error will set `rootMessage` in that code? Nice! And yes, having a conditional to not render the `<ul>` would be great.

Your suggestion for improved error handling sounds great to me. I've also thought about adding a Rails-like flash thing, but didn't know where to start when it came to doing that in React. Rails stores it in session and either renders on the next request, or the current one (with `flash.now`) but I just don't know enough about the React lifecycle yet to get that same functionality working. Maybe setting the message in state and then clearing it out after you display it?

Were you thinking of a `<Flash>` component that you could import from @redwoodjs/web and it would render itself if that state had a value?

**Comment by Terris** [comment]
Great! Seems like there are a few actionable items here which I'm happy to initiate with PRs if you'd like.

- Conditionally render the messages list inside the formErrors component
- Add a message string in the generated auth.js file. Maybe something like, "You don't have permission to do that." Err, something...?
- The auth tutorial section on redwoodjs.com should probably be updated to reflect the above change.

Just sketching out loud here; for the Flash feature, I'm imagining it would be ideal to utilize a Context/Reducer/Provider pattern as a store for global messaging (possibly even tap right into RedwoodProvider). From there we could use the useContext hook to read and write messages to and from anywhere. Yep, exactly, we could have an importable <Flash> component too, which would handle the ui for messaging. It could listen for router events and dismiss on location change and we could build in a little actions api so that you could `dismiss` a message programmatically (like, say, onClick).

Whatcha think? I could also open a PR to prototype this feature so we can see it in action.
