### ISSUE TITLE
Feature Request: yarn rw serve

### ISSUE THREAD

**Issue by AryanJ-NYC** [redwoodjs/redwood#604]
`yarn rw build` exists but there is no local way to see what the production build looks like.

A `yarn rw serve` to stand up the built code would help debug production problems without the need of deploying out to Netlify or whereever.

**Comment by navidmesbah** [comment]
I want to also ask for a **feature request**:

It would be great if we could **deploy** to traditional microservices environments, like **Heroku** dynos!

Thanks

**Comment by peterp** [comment]
@AryanJ-NYC This is a great idea and I think fairly straightforward to achieve. We've been modifying the `dev-server` to become a standalone `redwood-http-server` by splitting out the "watch and reload" functionality.

It does not support serving static content, and I wanted the focus to be purely about serving serverless functions, since I believe most people would actually serve the static content from nginx or something edge ready, and simply proxy to the serverless functions.

Buuut, since it's express maybe it's easy enough to add this functionality to `redwood-http-server`.

**Comment by thedavidprice** [comment]
@bcoe just wanted to loop you in on this one as I believe you are working on something similar for container implementation. Wondering out loud if you and Peter's work here has potential overlap.

**Comment by bcoe** [comment]
I think I just swapped out apollo-server-lambda for apollo-server-express, I'm guessing in my testing on GCP we were running the dev server for the frontend?

**Comment by thedavidprice** [comment]
> I'm guessing in my testing on GCP we were running the dev server for the frontend

Yeah, that would make sense. Aaaaand that also might have explained some of the performance issues 🤔

Thanks, Ben!

**Comment by jtoar** [comment]
It's a thing https://github.com/redwoodjs/redwood/pull/2217, https://github.com/redwoodjs/redwood/pull/2234.
