### ISSUE TITLE
[Bug]: Scaffold generator creates a big block of whitespace in Form component

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#6097]
### What's not working?

The form generated by the scaffold generator creates a big block of empty white space:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/300/182209053-20e3dc28-12a3-4975-9c14-978fe1582d20.png">

You can see an example in this PR: https://github.com/redwoodjs/redwood-tutorial/pull/71/files/173c7dc26b2c7ed6f238c5c4a8fcd4d8a6edda08#diff-7cfe9b38c881909d5686dfa09774aa22db5605acb9a0a8c53e9e2eb3c49ae412 which corresponds to this section of the generator template: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template#L31-L42 

Looks like the number of lines of whitespace will depend on the number of editable columns in your model. If one or more are an enum column then some code will be generated, but if not then it will result in one more lines of whitespace instead.

Maybe this could be rectified by just running the generated file through Prettier? Is that something we can even do?

### How do we reproduce the bug?

Generate a scaffold for a model, preferably with no enum columns.

### What's your environment? (If it applies)

```shell
Any recent version of Redwood would exhibit this behavior.
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Tobbe** [comment]
> Maybe this could be rectified by just running the generated file through Prettier? Is that something we can even do?

Would be great if we could lint --fix and prettier format all our generated code! I think that's the only sustainable way forward here, rather than trying to manually fix all our templates, and then keeping them that way.

**Comment by Philzen** [comment]
I also recently contemplated about how to avoid templates producing code that violates linting rules, as this comes up over and over again. I can only assume currently there must be numerous templates that still produce code that doesn't comply since the new import order sort rule was introduced in 2.0. 

Running lint --fix after *every* generator command may be an easy fix, but it would (1) add to the execution time and (2) sometimes there are cases which aren't auto-fixable, which i encountered during upgrading our project's code base to 2.x.

I wondered: isn't `create-redwood-app` part of the CI pipeline? If not, maybe we can add it, generating a plain project, then trying out all generator commands that are not XOR (such as the `auth` or `setup ui` stuff) and then running `yarn rw lint`. If it doesn't come back with exit code 0, the pipeline fails and we have identified a todo :tada:  … The XOR stuff could then be tested step by step in the same fashion.

**Comment by samthuang** [comment]
Hello, first-time contributor here. I'd like to try this issue if no one is currently working on it. 🙂 

I noticed the extra white spaces in Form only occur when the redwood project is in TypeScript. Is there a difference in how the `generate` command is run between JavaScript and TypeScript? I wonder whether the bug has to do with that.

_(Investigating: some time has passed…)_

Following the above observation. I found the prettify function is run twice for a JavaScript redwood project.

First, when we create the template with the `generateTemplate,` then again through the `transformTStoJS` function in formatters [here](https://github.com/redwoodjs/redwood/blob/99c38b3cf58b4d60b93ff265f20d8ad10835f86f/packages/cli/src/commands/generate/scaffold/scaffold.js#L240-L287). I verified that by returning just the `code` without the prettify function in `transformTStoJS`, the JavaScript redwood project’s scaffold-generated Form has the same whitespace bug as the TypeScript redwood project [here](https://github.com/redwoodjs/redwood/blob/99c38b3cf58b4d60b93ff265f20d8ad10835f86f/packages/cli/src/lib/index.js#L252).

```js
// return prettify(filename.replace(/\.tsx?$/, '.js'), code)
return code
```

I attempted to wrap the formatter in scaffold.js with the prettify function, but to no avail, because the [parser](https://github.com/redwoodjs/redwood/blob/99c38b3cf58b4d60b93ff265f20d8ad10835f86f/packages/cli/src/lib/index.js#L80-L84) in the prettify function is undefined, and I have been stuck at this step. https://github.com/redwoodjs/redwood/pull/7820

@cannikin - I have yet to try running the generated code through prettier first in the [writefile()](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/lib/index.js#L128-L147), and will look into that next. In the meantime, what do you think about why a JS redwood project does not share the same bug as a TS redwood project? thank you.

**Comment by cannikin** [comment]
It seems like that second run through prettify is the key...so prettify is only being run once in `generateTemplate` if you make a TS project? I wonder why it wouldn't fix that extra whitespace...unless for some reason it thinks that its significant white space, and is there on purpose, so it keeps it?

You could try editing the template itself, and look for a loop that's generating extra newlines. If you can remove those then it shouldn't generate the extra whitespace at all.

**Comment by samthuang** [comment]
Instead of editing the template itself, it seems like updating the prettify function resolved the issue! No changes to scaffold.js needed, so no second run needed. https://github.com/redwoodjs/redwood/pull/7820

**Comment by thedavidprice** [comment]
@aUsABuisnessman thanks for asking:
1. If it's a problem with your custom implementation, ask for help on the Forums: https://community.redwoodjs.com
2. If it's a problem with the Redwood code/functionality, report it as an Issue here: https://github.com/redwoodjs/redwood/issues

Not sure which is accurate? I'd suggest starting a discussion on the Forums and, once describing and showing what's going on, asking for suggestions about the right first step. You can go ahead and open an Issue. Just know that on GitHub the Core Team has to prioritize bugs and can't help with implementation support.
