### ISSUE TITLE
[Tests] Improve internal `paths.ts` test coverage and cases

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#613]
Redwoods' CLI commands are increasingly dependent on these helpers, and we are way behind on test coverage, which is resulting in errors and workarounds.

- increase coverage of functions, especially `getPaths()`
- increase coverage of all properties, e.g. `getPaths().api.base`
- test for multiple path cases
    - spaces
    - Windows, Linux, etc.
    - special characters (TBD)

**Comment by jtoar** [comment]
This one's definitely still a priority! Here's the function:

https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/paths.ts#L153

We'd just have to add another test here:

https://github.com/redwoodjs/redwood/blob/main/packages/internal/src/__tests__/paths.test.ts#L10

If anyone's interested let me know. This one's a little tricky because you have to be in a rw project to test it, but it's not too hard since we have fixtures in the framework.
