### ISSUE TITLE
Ship with some validation on the api side

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwood#617]
This how validations work in rails

```ruby
class Person < ApplicationRecord
  validates :name, length: { minimum: 2 }
  validates :bio, length: { maximum: 500 }
  validates :password, length: { in: 6..20 }
  validates :registration_number, length: { is: 6 }
  validates :name, uniqueness: { case_sensitive: false }
  validates :email, 
                    :presence   => true,
                    :format     => {  with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                    :uniqueness => { :case_sensitive => false 
end
```

Now react form and graphql omit some these validations, I still however think on the api side it should ship with some validations.

**Comment by cannikin** [comment]
You're thinking more of the length/format validations? GraphQL will enforce the type and existence checks, of course, so any mutations would fail long before they get to the services layer.

I'm not a GraphQL expert but after a quick check it seems like length/format validation (outside of being the proper type) is expected to happen in the resolvers? Which for us means the services.

We can't do class-level method calls like `validates` since the services aren't classes, just a collection of functions. In order to implement this in a clean way for the user (developer) we'd need to somehow wrap calls to `db` in our own code so that we can validate each and every field before passing it on to Prisma. This is completely off the top of my head but maybe something like this could work?

```javascript
import { redwoodDb, validates } from '@redwoodjs/api'

validates('image', 'title', { length: { max: 255 } })

export const createImage = ({ input }) => {
  return redwoodDb('image', 'create', { data: input })
}
```

We'd build up an array of validations every time `validate` is called and then `redwoodDb()` would perform checks on the incoming data before passing on the call to `db.image.create()`.

I'm not loving that syntax (passing 'image', and 'create' as strings) but I don't know how else you'd do this in Javascript without doing what Prisma does: analyze the database structure and generate all the code needed to enable normal chained function calls like `redwoodDb.image.create()`. In fact that string passing syntax is probably a deal-breaker. Hmmm...anyone else have ideas as to how this could be cleanly implemented?

**Comment by jtoar** [comment]
Implemented in https://github.com/redwoodjs/redwood/pull/3532.
