### ISSUE TITLE
[Docs] Add destroy command to CLI documentation

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#625]
@jtoar I don't believe this happened when the PR was merged. But the `yarn rw destroy help` info is good and can probably be copy+paste into documentation.

Anything else I might be missing here?

**Comment by jtoar** [comment]
@thedavidprice I think you got it all--I'll add positionals for consistency since that's what's happening in #594 (I'll add it to there). It'd just be adding something like this to [`createYargsForComponentDestroy`](https://github.com/redwoodjs/redwood/blob/master/packages/cli/src/commands/destroy/helpers.js#L20):

```
builder: (yargs) => {
  yargs.positional('name', {
  desc: `Name of the ${componentName}`,
  type: 'string',
})
```

**Comment by thedavidprice** [comment]
duplicate https://github.com/redwoodjs/redwoodjs.com/issues/197
