### ISSUE TITLE
[Bug?]: TS: QueryResolvers/MutationResolvers types sometimes wraps in promise twice

### ISSUE THREAD

**Issue by dac09** [redwoodjs/redwood#6495]
### What's not working?

When writing scenario/service tests, we sometimes want to look inside the properties of a findMany.

e.g. We have a service for post, which returns many posts

```ts
export const posts: QueryResolvers['posts'] = () => {
  return db.post.findMany()
}
```

And in your test you write something like:

```ts
    const result = await posts()
    expect(result[0].authorId).toEqual('bazinga')
```

You will get a TS error claiming `authorId` does not exist (which is not true)

<img width="1166" alt="Screenshot 2022-10-03 at 15 42 20" src="https://user-images.githubusercontent.com/1521877/193606126-0d3481ff-bcd3-4e74-bddf-0ea83ac60f58.png">

--- 

**Analysis**

This seems to be a problem _sort of_ with graphql-codegenerator in the type

```ts
export type ResolverTypeWrapper<T> = Promise<T> | T;
```

For some reason, only in the findMany cases it wraps it in promises twice. This isn't in a problem with the findUnique resolvers.

### How do we reproduce the bug?

See above. Can be reproduced in test project generator.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by dac09** [comment]
It looks like this issue has been resolved on its own (possibly by graphql-codegen or TypeScript)

**Comment by c-ciobanu** [comment]
Hi, this issue is still happening, at least for me.
If you try to use a service from another service you will get the same TS problem as described above.
I saw that there is a PR for it so it might be good to get that in if it fixes the issue.

**Comment by Philzen** [comment]
> This seems to be a problem sort of with graphql-codegenerator in the type
>
>     export type ResolverTypeWrapper<T> = Promise<T> | T;
> For some reason, only in the findMany cases it wraps it in promises twice. This isn't in a problem with the findUnique resolvers.

I'm also seeing this issue in RW 8.x and yes, this exact type seems to be the culprit. Interestingly, removing the wrapper (effectively `type ResolverTypeWrapper<T> = T`) as a test worked fine for both findMany and findUnique.

Wonder if this is a feasible solution?

On another note (and why the above doesn't seem to cut it): my assumption is that all service methods that return prisma method calls also return a promise, but when consuming my service methods in tests for example, typescript won't offer any `.then() / .catch() / .finally()` completion – this is for findMany methods, all findUnique types seem to be typed correctly as promise (that is completely independent of the method being marked as `async` or not).
Or, speaking of the actual types in question (rather than Prisma find* terminology):
- :heavy_check_mark: `Resolver<Maybe<ResolversTypes['Post']>, …, …, …>` is fine 
- :x: `Resolver<Array<ResolversTypes['Post']>, …, …, …>` isn't

Just getting rid of the `ResolverTypeWrapper` doesn't solve that typing issue.
