### ISSUE TITLE
[Bug?]: Errors in defining scenario data for tests are silently swallowed

### ISSUE THREAD

**Issue by rmzg-ll** [redwoodjs/redwood#6809]
### What's not working?

An example scenario file with something like:

```
  export const standard = defineScenario<
    | Prisma.ExpenseTypeItemCreateArgs
    | Prisma.ExpenseItemCreateArgs
    | Prisma.PipelineCreateArgs
    | Prisma.StageCreateArgs
    | Prisma.VehicleCreateArgs
    | Prisma.PersonCreateArgs
  >({
[...]
    dealFinanceQuote: (scenario) => ({  
      data: {
        downPayment: 1365,
        customerDealId: scenario.customerDeal.closeTest.id,
      },
    }),
  })
```

Where `dealFinanceQuote` is the name of a model will execute *without* error and *without* actually producing a `dealFinanceQuote` entry (the error is that `dealFinanceQuote` needs a child key whose value is the `(scenario) =>` callback)

Similarly if everything else is correct but your model name is incorrect, it will again execute without error and not tell you of your mistake.

### How do we reproduce the bug?

Create a scenario file with errors. Run a test. Fail to get errors.

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Hey @rmzg-ll, @dac09 and @KrisCoulson will take a look at this in the next few days. Possible you could expand the `[...]` part of the code block? Do you define `customerDeal` there?

**Comment by dac09** [comment]
Hey @rmzg-ll - looks like the reason you're facing issues is because the syntax in your scenario definition is wrong. TS should be telling you this! 


```
// Wrong syntax 👇
defineScenario({
modelName: (scenario) => { ...}
})

// Correct syntax ✅
defineScenario({
 modelName: {
   scenarioKey: (scenario) => {...} 
 }
})
```

The difference is that your scenario "definition" function has to be nested in a key, not just the model name. 

Please let us know if this helps, and feel free to reopen the issue with more details if it doesn't!

---

That being said we found TS issue with the function format, which will be resolved by this PR: https://github.com/redwoodjs/redwood/pull/6915
