### ISSUE TITLE
As per the Readme on a generated redwood app, Prisma2 is ready

### ISSUE THREAD

**Issue by davidrhoderick** [redwoodjs/redwood#688]
In the Readme of a freshly generated redwood app, it states 

    HEADS UP: RedwoodJS is NOT ready for use in Production. It relies heavily on Prisma2, which is currently in testing with an expected production release coming soon. See status at "Is Prisma2 Ready?"

with a link that redirects to https://www.notion.so/Is-Prisma-2-Ready-8b3fba3eaf5b4bf3ab7102fd94f56148, which now states that Prisma 2 is ready for production.  May I suggest removing or amending this line in the Readme?

**Comment by jtoar** [comment]
@davidrhoderick Totally! @thedavidprice Should we still mention that prisma migrations are an experimental feature?

**Comment by thedavidprice** [comment]
Hi All! We are working internally on this and the language to update both current status and Redwood "readiness". And we don't want to overstate the "readiness" part.

Correct, Prisma v2 was a big step. But, I think, I little misleading because migrations are still experimental.

TBD. But we are working on it. Thanks!

**Comment by thedavidprice** [comment]
Done! #958
