### ISSUE TITLE
Scaffold generator not generating scalar arrays in SDL

### ISSUE THREAD

**Issue by mikedklein** [redwoodjs/redwood#740]
So I am not sure if I am doing something wrong or if this is an issue. When I generate a scaffold for one of my types called a farm see schema:

```
model Farm {
  createdAt               DateTime    @default(now())
  description             String?
  farmers                 String?
  founded                 Int?
  id                      Int         @id @default(autoincrement())
  laborSource             String?
  name                    String      @unique
  otherCertifications     String
  partnerSince            Int?
  safetyCertifications    String
  size                    String?
  sustainabilityPractices String
  updatedAt               DateTime    @default(now())
  url                     String?
  city                    String
  lat                     Float?
  lng                     Float?
  state                   String
  street                  String
  zip                     Int
  logo                    String
  images                  String[]
  Inventories             Inventory[] @relation(references: [id])
}
```

The resulting SDL does acknowledge the string array:

```
export const schema = gql`
  type Farm {
    createdAt: DateTime!
    description: String
    farmers: String
    founded: Int
    id: Int!
    laborSource: String
    name: String!
    otherCertifications: String!
    partnerSince: Int
    safetyCertifications: String!
    size: String
    sustainabilityPractices: String!
    updatedAt: DateTime!
    url: String
    city: String!
    lat: Float
    lng: Float
    state: String!
    street: String!
    zip: Int!
    logo: String!
    images: String      // <----- This should be an array
    Inventories: Inventory
  }
...
```

This causes the error 

```
TypeError: String cannot represent value: ["https://res.c ..."]
```

Is this expected behavior and we should modify the sdl manually? Could I have setup something incorrectly?

Manually changing the SDL to:

```
...
images: [String]
...
```

fixes this for me.

You will also notice the generated Inventories field based on related model behaves similarly.

**Comment by jtoar** [comment]
> Link to the [topic](https://community.redwoodjs.com/t/scaffold-generator-not-generating-array-in-sdl/794/2) in the forum

@mikedklein I think the reason is because we built our generators around SQLite and SQLite doesn't natively support scalar lists. What you could do instead is turn the field you're tying to make an array into its own model, and make a one-to-many relationship. Let me know if I misunderstood your problem though!

**Comment by cannikin** [comment]
> the reason is because we built our generators around SQLite and SQLite doesn't natively support scalar lists

I wish I could say that was the reason the SDL generator isn't creating array syntax here, but really it's because I didn't even realize that WAS valid syntax until this issue! See my response here: https://community.redwoodjs.com/t/scaffold-generator-not-generating-array-in-sdl/794/4?u=rob

I'm not really sure what to do here...on the one hand we do start with SQLite and want a zero-config experience when first creating a Redwood app, but once you get past a certain point in your experience you'll probably be running Postgres or MySQL locally to mimic your production environment and the generators shouldn't be limited to only ever generating SQlite-compatible code. On the other hand, I don't want to keep a list of database-compatible generation features that we need to maintain forever. :(

My first instinct is to always generate the SDL based on what's in `schema.prisma`, and the developer needs to know that if they plan to use SQLite then there are certain types they just can't use (scalar arrays, JSON, etc). Prisma may already warn users about this when creating migrations when the syntax doesn't match the `provider` in `schema.prisma`?

**Comment by mikedklein** [comment]
One thing to note here is this is only valid for Postgres in general. MySQL doesn't even support this. Link, as provided by @jtoar, in the forum post [https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#lists](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#lists)
