### ISSUE TITLE
Sdl generator inputs mandatory even if they have defaults

### ISSUE THREAD

**Issue by FiveBoroughs** [redwoodjs/redwood#766]
It could be interesting for the SDL Generator to recognize if a Schema Model field has an `@default()` attribute, 
and if so not make the field mandatory with `!` in the sdl.js file.

For example: 
```prisma
model User {
  id         Int      @id @default(autoincrement())
  createdAt  DateTime @default(now())
  updatedAt  DateTime @default(now())
  email      String   @unique
  name       String
}
```
Will generate :
```javascript
input CreateUserInput {
  updatedAt: DateTime!
  email: String!
  name: String!
}
```
But the desired out put would be :
```javascript
input CreateUserInput {
  updatedAt: DateTime
  email: String!
  name: String!
}
```

**Comment by cannikin** [comment]
In this specific case we should probably just add `updatedAt` to the list of ignored fields (currently includes `id` and `createdAt`)—ones that the SDL will not include in Input types for because it assumes Prisma and/or the database is handling those for you. I wrestled with adding it at the time I wrote the generator and decided not to. Whoops! 😅

But I agree we should add that functionality to catch other fields with a `@default` that aren't in this list!

**Comment by Rosenberg96** [comment]
I took a shot at this without success. @cannikin you might have more luck given your insight. I will leave some notes here, if some one wants to pick this up. You could also add `good-first-issue` label here. 


From `@prisma/client/runtime/dmmf-types.d.ts`

```
interface Field {
        kind: FieldKind;
        name: string;
        isRequired: boolean;
        isList: boolean;
        isUnique: boolean;
        isId: boolean;
        type: string;
        dbNames: string[] | null;
        isGenerated: boolean;
        hasDefaultValue: boolean;
        default?: FieldDefault | string | boolean | number;
        relationToFields?: any[];
        relationOnDelete?: string;
        relationName?: string;
        documentation?: string;
        [key: string]: any;
}
```

The property `hasDefaultValue` is true when the `@default(...)` decorator is set in the `schema.prisma`. However, the tricky fact is also that id fields, indicated by `isId` also has this as `true` when using `@default(cuid())` or similar. My efforts failed by not fully understanding what logical combination of the properties should be used.  

If working on this, one has to consider the `createInputDSL` and `updateInputSDL` functions, that made it more tricky for me at least.

The main function to change is `modelFieldToSDL` https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/sdl/sdl.js#L25

**Comment by cannikin** [comment]
I don't have the code in front of me but I imagine a check for `isRequired && !hasDefaultValue` should append the `!` on the type. 

Right now we're automatically ignoring fields named `id` and don't add them to the `createInputSDL` and `updateInputSDL` but that should probably be updated to just look at that `isId` boolean instead. 

And if we wanted to get rid of the manual ignore list altogether we could also exclude `DateTime` fields that have a default of `now()` or `updatedAt()` since you're probably counting on the database and Prisma to manage those values for you.

**Comment by thedavidprice** [comment]
Looping in @Rosenberg96 and @turadg from #951 (related to Scaffold, but the same topic about generated code).

And also adding this relevant Forum thread: https://community.redwoodjs.com/t/scaffold-and-default-values/1026/3

@cannikin please take a look at this issue:
- do you still think your comment above about a solution is a good approach? And would there be any different between handling the Scaffold vs. the standalone SDL generator?
- any other thoughts about how someone could move this forward in a PR?

And for everyone else, is there interest in contributing a PR to help move this forward? No pressure, but it would be a huge help!

**Comment by cannikin** [comment]
Yep I think it should still be good to go.

We're ignoring fields with certain names here: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/sdl/sdl.js#L50

We should just make that check more robust and rather than a hardcoded list, be smart about the fields and their contents. If it's the ID column, we're not going to be setting that manually, and if the column has a default value of `now()` or `updatedAt()` then assume that usually we want Prisma or the DB to set that for us as well, and don't bother including in the SDL. Someone can always manually edit the SDL and add them back if that works for their use case.

I think it will work fine for the scaffold as those same parameters should apply there as well. It's a little more annoying to update the entire scaffold if a field is missing, but I think that will be an edge case.

**Comment by mtfoley** [comment]
I was trying this out. Other than `yarn build` are there any compile steps to take in making sure that changes to `packages/cli/src/commands/generate/sdl.js` work their way in? I would have thought I'd break the tests by updating that file if it had taken effect, but it doesn't seem to be. I'm getting errors when I try following the instructions here: https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#testing-the-cli-in-your-project

**Comment by jtoar** [comment]
Given the model in the original post, the `CreateUserInput` generated by `yarn rw g sdl user` looks like:

```js
  input CreateUserInput {
    email: String!
    name: String!
  }
```

Which makes me think we can close this issue. We have others open for filtering out other fields from other parts of the SDL already.

@mtfoley Sorry we never got back to you; `yarn build` should be all you need, and you can get your changes into a Redwood project with either a `RWJS_CWD` env var or by using the `rwfw` command. I'll update those instructions to be more informative.
