### ISSUE TITLE
[Bug?]: I can't customize graphql

### ISSUE THREAD

**Issue by alirezaRaisSattari** [redwoodjs/redwood#7671]
### What's not working?

@redwoodjs/graphql-server
I can't customize graphql directive and scalar and use library like graphql-constraint-directive 

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by jtoar** [comment]
Mind sharing a reproduction of what you tried that didn't work?

**Comment by dthyresson** [comment]
Hi @alirezaRaisSattari since the RedwoodJS GraphQL server is powered by Yoga, it supports envelop plugins and from what I can see about `graphql-constraint-directive` is that in has an envelop plugin:  https://github.com/confuser/graphql-constraint-directive#envelop

You should be able to import the plugin per those docs and then add as an `extraPlugins` to your `createGraphQLHandler` in `api/functions/graphql.ts`.

Let me know if that works for you.
