### ISSUE TITLE
[Bug?]: Improve dbAuth frontend error handling

### ISSUE THREAD

**Issue by gilliardmacedo** [redwoodjs/redwood#8051]
### What's not working?

Hi!

We got a session in our production app like this:
![Screenshot 2023-04-17 at 17 02 06](https://user-images.githubusercontent.com/26877564/232598895-3aa22038-2a52-45a4-84be-9100c8af7ecd.png)

At some moment the user failed to get the token (Looks like a browser fail, but it can't be CORS since we are requesting same domain. Message: "TypeError: Failed to fetch"). Then, all requests fail with backend error (in our logs, "Exception in getAuthenticationContext: The `Authorization` header is not valid.")

It makes sense. After fail to get the token, authorization is invalid in the next graphql request. But we've been wondering how could we prevent and/or recover sessions with the same. Because the user became logged out while navigating private routes. If the request failed, doesn't make sense to redo and/or, at least, not clean the previous token? There were 7 graphql requests failing after the failed getToken request.

We are using dbAuth.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by thedavidprice** [comment]
@gilliardmacedo if you're willing to improve this, we'd welcome the help! Please take it away.

It's not clear to me based on your post if you already have an idea/solution in mind. Either way, I'm looping in @cannikin as a resource if/as needed.

Lastly, for situations such as this, I encourage you to try the new experimental Redwood Studio with OpenTelemetry (shipping very soon with v5).
- https://community.redwoodjs.com/t/redwood-studio-experimental/4771
- https://community.redwoodjs.com/t/opentelemetry-support-experimental/4772

**Comment by cannikin** [comment]
I haven't seen this behavior in my own apps...are you doing anything unusual with the dbAuth function or GraphQL queries?

I'd be interested to see how you'd like to recover from this, without sacrificing security. Currently if the session is found to be invalid (most likely because of the user tampering with the cookie) the cookie is immediately removed, which logs out the user. If you're now saying that an invalid cookie is actually okay, and to just retry the request...that seems a little scary. 😬

**Comment by standup75** [comment]
@cannikin It seems to me that if I lose connection and the connection comes back up, all subsequent request will fail. Just made the test, and that's the case. How can we avoid that?

**Comment by cannikin** [comment]
When you say the connection is lost, can you be more specific? Is this in local dev, and you stop the API server? Are you getting *no* response from the server, as if it didn't even exist any more? Or is the server returning a 500 error? Do you have polling requests that are periodically hitting the GraphQL endpoint (which would force a call to the `getToken` endpoint to make sure you're still logged in).

I just did a test locally where I'm logged into my and browsing around. Then I stop the API server, and try to navigate somewhere else, which fails (because the API can't respond to the `getToken` request or any GraphQL queries). Then I start the API server up and continue browsing again, still logged in, as if nothing happened.

The only thing I can think of is that when you're saving changes to files, Redwood will restart the API server, and it can't respond to requests for a tiny amount of time. Is it possible a `getToken` request is firing off during this downtime? But I don't see why it would just pick up where it left off on your *next* request, just like with my server restart above...

**Comment by standup75** [comment]
I just go offline, either switching off my wifi or in devTools swithcing throttle to offline (for localhost)
I just try to simulate a user going through a tunnel.

**Comment by standup75** [comment]
Here is the sequence @cannikin 
Uploading Screen Recording 2023-05-03 at 12.35.54 PM.mov…

And thank you 🙏

**Comment by cannikin** [comment]
Great work, thanks for this fix!
