### ISSUE TITLE
[Bug]: DbAuthHandler doesn't allow renaming User model

### ISSUE THREAD

**Issue by antonmoiseev** [redwoodjs/redwood#8743]
### What's not working?

DbAuthHandler explicitly references `user()` model in a Prisma query which doesn't allow renaming Prisma `User` model into anything else. This is where it's happening (line 810):
https://github.com/redwoodjs/redwood/blob/2a42df9de2bcb34f368cfc5cbc882967d4a7d3c9/packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts#L806-L810

Instead it should use `authModelAccessor` to access the table.

### How do we reproduce the bug?

1. Rename the User model
2. Add a user to the database
3. Start the app and try to login into it

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 13.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - /private/var/folders/fn/8llygws922d451wc05087z4r0000gn/T/xfs-b6f22933/node
    Yarn: 3.5.0 - /private/var/folders/fn/8llygws922d451wc05087z4r0000gn/T/xfs-b6f22933/yarn
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5.1
  npmPackages:
    @redwoodjs/auth-dbauth-setup: 5.3.2 => 5.3.2
    @redwoodjs/core: 5.3.2 => 5.3.2
```

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Thanks @antonmoiseev! I just reproduced this following your instructions. 

I quickly noticed that this line appears to be related too:
https://github.com/redwoodjs/redwood/blob/bbe222615c596e47c973ea80fbb396d96bdb5369/packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts#L970

I'm happy to help out some more if you still want to try out a PR for this. Otherwise I'll probably try to pick this up myself soon.
