### ISSUE TITLE
[Bug?]: Remount of parent <Set /> on navigation leads to flickering

### ISSUE THREAD

**Issue by dennemark** [redwoodjs/redwood#9105]
### What's not working?

I have the following Routes and sets:
```
    <Router>
      <Set wrap={FirstLayout}>
        <Route path="/" page={HomePage} name="home" />
        <Set wrap={ScaffoldLayout} title="Posts" titleTo="posts" buttonLabel="New Post" buttonTo="newPost">
          <Route path="/posts/new" page={PostNewPostPage} name="newPost" />
          <Route path="/posts/{id:Int}/edit" page={PostEditPostPage} name="editPost" />
          <Route path="/posts/{id:Int}" page={PostPostPage} name="post" />
          <Route path="/posts" page={PostPostsPage} name="posts" />
        </Set>
      </Set>
      <Route notfound page={NotFoundPage} />
    </Router>
```
When I navigate from home to posts and back the FirstLayout gets remounted. 
This does not happen, when I navigate from posts to post/editPost/newPost, since we are already within a ScaffoldLayout.

This leads to unwanted issues like flickering. Or in my case refs for portals within FirstLayout are suddenly null after navigation.

This happens on  Redwood v6.1

### How do we reproduce the bug?

Here is a repository for reproduction: https://github.com/dennemark/redwood-route-rerender
In console logs you will see `firstLayout` and `scaffold Layout`, when navigating from Home to Posts. The only appear on mount:
`useEffect(()=>{console.log("firstLayout")},[])`

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by taivo** [comment]
I'm seeing this situation as well and would like to report an additional observation that may be related to the same root cause. For the following setup:

```
<Set wrap={NavbarAndFooterLayout}>
   <Route path="/" page={HomePage} name="home" />
   <Set wrap={WithSidebarLayout}>
   ...
   </Set>
   <Set wrap={NoSidebarLayout}>
   ...
   </Set>
</Set>
```
We have 3 groups of routes: the `HomePage` group, the `WithSidebarLayout` group, and the `NoSidebarLayout` group. Route transition within each group has no issue. However, when transition across groups, the parent-level `NavbarAndFooterLayout` gets unmounted and remounted, which causes flickering.

The additional observation I'd like to add is this: when going to the HomePage, it seems that the entire `Routes` component from `Routes.tsx` gets recreated. This can be seen by adding a console.log in the `Routes` component prior to `return`. Perhaps the root path is being treated as special somehow?

**Comment by raph90** [comment]
Hi, are you explicitly importing your page components into the Routes file? I've found that that clears up a lot of flickering issues

**Comment by dennemark** [comment]
Hi,
this might not work well with lazy loading of pages I guess?

**Comment by dac09** [comment]
Hey @dennemark thanks for issue and the reproduction. This is on my list this week - at the very least I can come back with some observations for discussion, if not a fix.
