### ISSUE TITLE
Add "rw storybook --open"

### ISSUE THREAD

**Issue by aldonline** [redwoodjs/redwood#916]
* When you click on the storybook item on the VSCode outline, all you get is a notification that says "not implemented yet".

<img width="976" alt="Screen Shot 2020-07-30 at 6 25 38 PM" src="https://user-images.githubusercontent.com/154884/88990581-2b7f2600-d293-11ea-9dd2-4f74698ac7b4.png">

* This is on purpose. Instead of implementing it in a hacky way, I thought it was better if this was provided by the CLI

# Basic Feature

* The behavior I suggest is the following:

```sh
$ yarn redwood storybook --open
```
Will have the following effect (pseudocode):

```js
// 1. only start if it needed
if (!storybook_is_running) start_storybook()
// 2. open the URL
open("http://localhost:xxxx/")
```

Once this feature is implemented, the "information message" can be removed [here](https://github.com/redwoodjs/redwood/blob/ffed13f62826b6b725c971bd0dcd6d346de6878d/packages/structure/src/language_server/commands.ts#L57)

# Advanced?

Not sure if this is possible (depends on how storybook is organized). But it would be great if we could pass a value to the `--open` parameter. This value can be the name of a component, layout, or page.

```sh
$ yarn redwood storybook --open=MyComponent

or 

$ yarn redwood storybook --open=/path/to/component.js
```

* If the value for the `--open` parameter is a string, then the CLI should use it to guess what page to focus on when opening storybook.
* This will enable some cool IDE features:
  * In the Command Palette ("Open Storybook for this Component")
  * In the Outline we can add an icon to "jump to storybook" for each component/layout/etc
  * In the code itself, via CodeLens (a small link above the React Component name)

**Comment by alvincrespo** [comment]
Hmm. I'd love to check this one one out. Where would be a good start?

**Comment by peterp** [comment]
Hey @alvincrespo I actually left the wrong comment in a different PR.

We start storybook over here:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js#L24-L37

You would need to create a `--open` flag and then conditionally set `--ci` in this file. Let me know if you need any help.

**Comment by alvincrespo** [comment]
@peterp Awesome. Going to look into this this morning

**Comment by alvincrespo** [comment]
@aldonline I was curious how you get the RedWoodJS panel in VSCode? Is that an extension?

**Comment by alvincrespo** [comment]
Ah figured it out: [Decoupled Studio](https://marketplace.visualstudio.com/items?itemName=decoupled.studio)

**Comment by pranshuls12** [comment]
hi

**Comment by pranshuls12** [comment]
is this issue still open

**Comment by thedavidprice** [comment]
Hi @pranshuls12 This issue is still open and we could use your help!

Please know there are three aspects to this:
1. The VS Code Extension which is developed by @aldonline: https://marketplace.visualstudio.com/items?itemName=decoupled.redwoodjs-ide
2. ...which relies on the Redwood [packages/structure](https://github.com/redwoodjs/redwood/tree/main/packages/structure)
3. ...and will use the Redwood CLI [commands for Storybook](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/storybook.js)

Please confirm that you'd like to work on this and I'll assign it to you.

**Comment by pranshuls12** [comment]
Yes,I will work on it

**Comment by pranshuls12** [comment]
can you guide how should i proceed will be a big help

**Comment by thedavidprice** [comment]
Great! I've assigned it to you. And I'm happy to help as much as I can. But you can also connect with the Redwood community if and when needed as well! There's a lot of people who might be able to assist. If you haven't read this yet, make sure you start here:
- https://github.com/redwoodjs/redwood/issues/1266
- and be sure to connect on the Forums and Chat as well if needed

Since there are multiple steps to this Issue, I recommend you break it into a few PRs, starting with adding the new option `--open` to the CLI command `yarn redwood storybook`. 
- Make sure you understand how to set up a local dev environment: https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#local-development
- And then understand how we build the CLI. There's a specific README for contributing to the CLI here: https://github.com/redwoodjs/redwood/tree/main/packages/cli
- In `packages/cli/src/commands/storybook.js`, it looks like the Redwood CLI command is passing `start-storybook` with `--ci`, so you'll need to add an option to Yargs (library for our CLI) to override this. 
- Lastly, it looks like it would also be helpful if you allowed for passing an option to set the port as well. It should default to 7910. (Not required but would be helpful)

We'll help you along the way. Don't hesitate to create a draft PR once you have some code — it's helpful to ask questions from the PR.

**Comment by jvanbaarsen** [comment]
I took the liberty to pick up this issue, please let me know if someone already made progress on this because in that case I'll close my PR.
