### ISSUE TITLE
getCurrentUser swallows exceptions

### ISSUE THREAD

**Issue by peterp** [redwoodjs/redwood#925]
This makes this function particularly difficult to debug during development. It would be a great if we threw these again during development.

**Comment by dthyresson** [comment]
@peterp This issue is from ~ a year ago, but thought I'd have a look since I am in GraphQL world. 

> getCurrentUser swallows exceptions

For example, let's say I create this artificial exception llke:

```js
export const getCurrentUser = async (
  decoded,
  { _token, _type },
  { _event, _context }
) => {
  if (decoded) {
    return undefined.toString()
  }
  return { ...decoded, roles: parseJWT({ decoded }).roles }
}
```

I do get:

![image](https://user-images.githubusercontent.com/1051633/128539892-fc25a62c-66d4-4011-8a44-a51ba1f3b59c.png)


and the response is

```js
{
    "errors": [
        {
            "message": "Cannot read property 'toString' of undefined"
        }
    ]
}
```

But strangely, the stack trace is not in my dev server logs:

```terminal
api with envelop | POST /graphql 200 1.008 ms - 71
api with envelop | INFO [2021-08-06 16:10:02.350 +0000] (graphql-server): GraphQL execution completed
api with envelop |     tracing: {
api with envelop |       "parse": 0.10715,
api with envelop |       "validate": 0.400028,
api with envelop |       "contextFactory": 0.088362
api with envelop |     }
api with envelop |     query: {}
```

Is this the behavior you mean by swallowing the exception?

To be honest, I am using envelop with masked errors turned on, so this is not the behavior I expect at all.  I would have expected a "Something went wrong" error that doesn't show the underlying error message.

**Comment by dthyresson** [comment]
Chatted with Guild and currently the `useMaskedErrors` plugin only handles errors during the execution phase.

They will upgrade this plugin to handle the ContextBuilding and Subscription phases and also look to see what errors (if any) should be dealt with in the Validation and Parse phases.

Once that feature is added to the plugin, will revise this issue.

**Comment by thedavidprice** [comment]
@dthyresson checking in about this one as we had it as a possible addition to v0.37 release. y/n/maybe?
