### ISSUE TITLE
[Bug?]: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by BenCherif** [redwoodjs/redwood#9276]
### What's not working?

i'm using your Dockerfile.dev to run the app :
strapi version : 4.14.3
and i got this error:
`error strapi@0.1.0: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.18.0"`

when i change this line FROM node:18-alpine  to FROM node:16-alpine it works  with nodejs 16

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by Josh-Walker-GM** [comment]
Hey @BenCherif 👋

Do you know why this particular version `strapi@0.1.0` is appearing? Perhaps `yarn why` could help determine this? We do occasionally get these types of issues where peculiar version of dependencies produce similar problems. I don't know an exact solution but wiping out the `yarn.lock` and `node_modules` and performing `yarn install` again would be my first suggestion.

It would be good if we could get to the bottom of this for you because we don't really support node 16 anymore and so moving you back up to node 18 would be best. There could be other incompatibility issues you start to face if you have your project on node 16 going forward.

**Comment by BenCherif** [comment]
Bro thanks for your reply it was my mistake,i just need to increase node version in my package.json file .
Kind regards

**Comment by Josh-Walker-GM** [comment]
Thanks! I'll close this for just now then but if you run into this again feel free to reopen and we can discuss again.
