### ISSUE TITLE
Authentication: Expose the Netlify Identity Widget's 'signup' functionality

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwood#963]
https://github.com/redwoodjs/repeater-issues/issues/2

**Comment by peterp** [comment]
We can append it to this PR: https://github.com/redwoodjs/redwood/pull/783

**Comment by dthyresson** [comment]
Since `login` can accept `options`, could `login({signup: true})` instead invoke `open('signup')` instead?

https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/netlify.ts#L14

```
  login: () => {
      return new Promise((resolve, reject) => {
        let autoClosedModal = false
        client.open('login')
        client.on('login', (user) => {
          // This closes the modal which pops-up immediately after you login.
          autoClosedModal = true
          client.close()
          return resolve(user)
        })
        client.on('close', () => {
          !autoClosedModal && resolve(null)
        })
        client.on('error', reject)
      })
    },
```

Instead of adding a new "signup" to the AuthProvider?

**Comment by cannikin** [comment]
Hmmm for Netlify maybe, since Sign Up and Log In are sort of just two views of the same widget, but other providers might have a totally different flow. Seems like they should both get a top-level function to me.

**Comment by dthyresson** [comment]
@peterp Same as https://github.com/redwoodjs/redwood/pull/783.

Should re reuse `login` or define a new top level `signup`?

Assume that signup by default will just invoke login for those that don't have provider-specific logic (like with Auth0 universal login not certain the signup tab can be selected by default).

**Comment by cannikin** [comment]
Is it weird to only have those providers that support a signup flow actually expose a `signup` function that you can destructure from `useAuth()`? Not sure if that's expected in JS world. Or maybe they all expose `signup` but if you actually call it from a provider that doesn't support it you just get a noop and a console message saying it isn't supported?

It feels weird to me to have a function `signup` that doesn't sign you up, just takes you to login. But maybe that's just me? @mojombo?

**Comment by dthyresson** [comment]
Auth0 supports defaulting to Sign Up as well as Netlify. 

See: https://auth0.com/docs/universal-login/new-experience


> You can make users land directly on the Signup page instead of the Login page by specifying the screen_hint=signup parameter when redirecting to /authorize. Note that this can be combined with prompt=login, which indicates whether you want to always show the authentication page or you want to skip if there's an existing session.

![Screen Shot 2020-08-25 at 21 37 27](https://user-images.githubusercontent.com/1051633/91244775-36ef3100-e71b-11ea-9a17-32cf695e4182.png)

Also example here:

https://community.auth0.com/t/how-do-i-link-users-directly-to-the-hosted-signup-page/42520

Note: probably want to support the "New" Universal vs "Classic" Universal.

@peterp and @cannikin Can we decide if 

* add `signup()` 
* add options to `login()` like `{signup: true}` or `{show: 'signup'}`

I think I would prefer to have an explicit `signup()` because I won't remember the options.

The auth client itself would implement. It might just call `login` with some extract params.

**Comment by dthyresson** [comment]
Also see issue: https://github.com/redwoodjs/redwood/issues/725 to document login/logout options.

**Comment by peterp** [comment]
My vote is for a `signUp` function, so that it feels like it matches our current `logIn` and `logOut` functions.
