### ISSUE TITLE
Diagnostics: add check for .env or .env.defaults

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#971]
A developer reported problems due to their project not having a `.env` or `.env.defaults` file. Based on experience with other frameworks, the developer assumed those were example files and unnecessary. However, in a Redwood default installation, the `schema.prisma` file requires a `DATABASE_URL` env var. If not found, the dev server will fail and deployments will fail.

@aldonline Do we have the capability to add 'Warnings' and/or recommendations vs. 'Errors'? Or is there a way to create a Diagnostic check that will examine the project for use of `process.env` and the `schema.prisma` for `env()`, and, if found, check to make sure those env vars exist in `.env` or `.env.defaults`? The latter seems hard. The former seems like a more simple warning with explanation -- the "magic" to be explained is that Prisma by default needs an env var.

**Comment by aldonline** [comment]
Hi David.

I love this issue. It is exactly what diagnostics are good for :)
Saving people time by making the tooling smarter.

> Do we have the capability to add 'Warnings' and/or recommendations vs. 'Errors'?

Yes, via `DiagnosticSeverity.Warning`. See [this line](https://github.com/redwoodjs/redwood/blob/fb21e01f3a6f7b060366c2a2803fed3b871c7520/packages/structure/src/model/RWCell.ts#L81) for an example.

```ts
if (!this.queryOperationName) {
        yield {
          uri: this.uri,
          diagnostic: {
            range: Range_fromNode(this.queryStringNode!),
            message: 'We recommend that you name your query operation',
            severity: DiagnosticSeverity.Warning,
          },
        }
      }
```

> Or is there a way to create a Diagnostic check that will examine the project for use of process.env and the schema.prisma for env(), and, if found, check to make sure those env vars exist in .env or .env.defaults?

Yes it is possible.
As you say, it is easier with prisma since 1. It is just one file and 2. the `env()` expression is very "standard".
But the former is also easy. We just need to parse all JS/TS files and search for `process.env`.
Of course, this will only work if the key is a literal, like `process.env["SOMEENVVAR"]`, but it wouldn't know what to do with `const name = "SOMEENVVAR" ; process.env[name]`. 
Still a good check to add since most people use the literal form anyway.

**Comment by thedavidprice** [comment]
@aldonline First off, huge thanks for this 🚀

Given the new checks/warning in #987 this seems resolved to me. Checking for the existence of these specific files is secondary to the main point, which is "Env var X is used in the code. Is env var X correctly defined and configured?" You've nailed this part.

Closing this one out. For the next steps, I've opened #1000
