### ISSUE TITLE
[Bug?]: FastifyError [Error]: The decorator 'urlData' has already been added!

### ISSUE THREAD

**Issue by SquirrelJimmy** [redwoodjs/redwood#9789]
### What's not working?

when build project, use api-server start  both-server(api&web) with cmd `@redwoodjs/api-server --port 8910` catch error `FastifyError [Error]: The decorator 'urlData' has already been added!`
This error catch above v6.6.0

### How do we reproduce the bug?

1. `yarn rw build`
2. `node ./node_modules/@redwoodjs/api-server/dist/index.js --port 8910`

`@fastify/url-data` plugin regist two times in [withWebServer](https://github.com/redwoodjs/redwood/blob/main/packages/api-server/src/plugins/withWebServer.ts) & [withFunctions](https://github.com/redwoodjs/redwood/blob/main/packages/api-server/src/plugins/withFunctions.ts)

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by tbay06** [comment]
I can confirm this issue is reproducible on a freshly installed app when using `yarn rw exp setup-docker` as well  - it seems to be happening in any implementation that uses the `rw-server` package directly, with the changes introduced here [#9714 ](https://github.com/redwoodjs/redwood/pull/9714/files) likely the culprit. See also [RedwoodJS deployment is not working](https://community.fly.io/t/redwoodjs-deployment-is-not-working/17429) and [Fly.io deployment help](https://community.redwoodjs.com/t/fly-io-deployment-help/5658)

**Comment by Josh-Walker-GM** [comment]
Thanks for the issue @SquirrelJimmy and the confirmation @tbay06! 

I'll take a look at this tomorrow (hopefully) and we can see about getting a fix merged and ready for release.
